package gh.nusashell.nusadesk.infrastructure.runtimehost;

import java.net.URI;
import java.net.URISyntaxException;

/**
 * Decides what happens when a loopback WebView is challenged for HTTP
 * credentials.
 *
 * <p>A registered web app is allowed to protect its own endpoint, so the host
 * has to be able to answer the challenge for that app and for no one else.
 * Answering is not a navigation, which means it is not covered by
 * {@link LoopbackNavigationPolicy} either: the WebView raises a challenge
 * against a socket the policy never sees, and the app's own document can make
 * a subresource request to a different loopback port.</p>
 *
 * <p>The rule this class encodes is therefore the strongest one the public
 * Android SDK actually supports:</p>
 *
 * <ul>
 *   <li>the challenge host must be the <em>exact</em> host this WebView owns.
 *       Every registered web app is generated as {@code http://127.0.0.1:<port>/}
 *       ({@code WebAppDefinition#getEndpointUrl()}), so the owned host is always
 *       the literal {@code 127.0.0.1};</li>
 *   <li>a challenge for any other host — another loopback listener, a LAN
 *       address, a public name — is refused and never answered, so a page
 *       cannot harvest a saved password by pointing a subresource at a host it
 *       does not own.</li>
 * </ul>
 *
 * <p><strong>Known platform limit.</strong> {@code onReceivedHttpAuthRequest}
 * supplies a host and a realm but no port, and the public
 * {@code android.webkit.HttpAuthHandler} exposes only {@code cancel()},
 * {@code proceed(String, String)}, and {@code useHttpAuthUsernamePassword()} —
 * there is no public accessor for the requesting host or port. A challenge
 * therefore cannot be pinned to the app's own port, only to the owned host. Two
 * registered apps share the host {@code 127.0.0.1}, so a page served by app A
 * that references a subresource on app B's port would be answered with A's
 * stored credentials. The practical exposure is limited — the referring page is
 * itself content the user installed inside their own guest, which could read
 * the same password off the guest filesystem — but the limit is real and is
 * recorded in ADR-0058 and {@code SECURITY.md} rather than papered over.</p>
 *
 * <p>Pure: no Android types, no I/O, no state. The Android glue in
 * {@link LoopbackWebViewClient} calls {@link #classify(String)} and then either
 * answers the challenge or cancels it.</p>
 */
public final class LoopbackAuthChallengePolicy {

    /** How a challenge is treated. */
    public enum Decision {
        /** The challenge names the owned host: it may be answered. */
        OWNED,
        /** The challenge names anything else: refuse it, never answer it. */
        REFUSED
    }

    private final String ownedHost;

    /**
     * @param ownedOriginUrl the exact origin this WebView owns, as generated by
     *                       {@code WebAppDefinition#getEndpointUrl()}
     * @throws IllegalArgumentException when the origin is not an absolute
     *                                  {@code http} loopback URL with an
     *                                  explicit port
     */
    public LoopbackAuthChallengePolicy(String ownedOriginUrl) {
        if (ownedOriginUrl == null) {
            throw new IllegalArgumentException("ownedOriginUrl must not be null");
        }
        // Reuse the navigation policy's own parsing and validation instead of
        // re-deriving what "the owned origin" means: one place decides it.
        this.ownedHost = hostOf(new LoopbackNavigationPolicy(ownedOriginUrl).getOwnedOrigin());
    }

    /** The host a challenge must name to be answerable. */
    public String getOwnedHost() {
        return ownedHost;
    }

    /**
     * Classifies a challenged host. Never throws; a null or blank host is
     * {@link Decision#REFUSED}.
     *
     * @param challengeHost the host passed to {@code onReceivedHttpAuthRequest}
     */
    public Decision classify(String challengeHost) {
        if (challengeHost == null) {
            return Decision.REFUSED;
        }
        String host = normalizeHost(challengeHost);
        return host != null && host.equals(ownedHost)
                ? Decision.OWNED
                : Decision.REFUSED;
    }

    private static String hostOf(String origin) {
        // Parse the origin rather than scanning for a colon: the navigation
        // policy has already validated it, and a scan misreads the bracketed
        // IPv6 form ("[::1]:8080" would yield "[") and any userinfo
        // ("user:pass@host:port" would yield "user"). Both would fail closed —
        // the app would be refused its own challenge — which is a silent
        // no-sign-in rather than an error anyone could see.
        try {
            String host = new URI(origin).getHost();
            if (host == null) {
                throw new IllegalArgumentException("owned origin must carry a host: " + origin);
            }
            return normalizeHost(host);
        } catch (URISyntaxException exception) {
            throw new IllegalArgumentException("owned origin is not a valid URL: " + origin);
        }
    }

    private static String normalizeHost(String host) {
        if (host == null) {
            return null;
        }
        String trimmed = host.trim();
        if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
            return trimmed.substring(1, trimmed.length() - 1);
        }
        return trimmed;
    }
}
