package gh.nusashell.nusadesk.infrastructure.proot;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Writes the product-owned, app-managed awareness bundle in the guest root.
 *
 * <p>The bundle is written when the guest session starts:
 * <ul>
 *   <li>{@code /root/README.md} — concise product overview with relative
 *       links into {@code docs/};</li>
 *   <li>{@code /root/docs/README.md} and the focused topic docs
 *       ({@code bridge.md}, {@code media.md},
 *       {@code battery-sensors-location.md}, {@code messaging-telephony.md},
 *       {@code calendar.md}, {@code termux-compat.md}) documenting the live
 *       loopback services, including the live-only camera + microphone media
 *       contract, the bounded calendar read/write contract, and the Termux
 *       command compatibility layer;</li>
 *   <li>{@code /usr/local/bin/nusadesk-android} — an executable Python 3 CLI
 *       that controls {@code media.start} / {@code media.status} /
 *       {@code media.stop}, the bounded calendar commands
 *       ({@code calendar list|add|update|delete}), and {@code bridge.info}
 *       over the authenticated loopback JSONL bridge;</li>
 *   <li>{@code /usr/local/bin/nusadesk-usb} — an executable Python 3 CLI
 *       for USB pass-through ({@code usb.list} / {@code usb.open} over the
 *       same bridge, plus an {@code SCM_RIGHTS} fd hand-off), generated by
 *       {@link GuestUsbCliWriter};</li>
 *   <li>{@code /usr/local/bin/nusadesk-usbd}, {@code /usr/local/bin/adb} and
 *       {@code /opt/nusadesk/libusb-shim.c} — the USB driver bundle
 *       ({@link GuestUsbDaemonWriter}, {@link GuestUsbShimWriter}): the
 *       wrapper makes the stock guest {@code adb} see devices attached to the
 *       host's USB port through the daemon and the LD_PRELOAD libusb shim;</li>
 *   <li>the {@code termux-*} command clients declared by
 *       {@link GuestTermuxCompatWriter} in the same bin directory, each also
 *       an executable Python 3 script over the same bridge.</li>
 * </ul>
 * Every file is intentional: generated by the Android host rather than
 * shipped as a mutable rootfs asset, carrying the APK version so an app
 * update replaces stale text on the next session start. The targets stay
 * normal writable guest files; this class does not bind them read-only or
 * make them immutable.</p>
 *
 * <p>Only fixed, app-managed paths are ever written and the parents must be
 * real directories: a symlink in {@code root}, {@code root/docs}, or
 * {@code usr/local/bin} fails closed with an {@link IOException} and nothing
 * is written outside the rootfs. A user-supplied destination path is never
 * accepted.</p>
 */
public final class GuestAwarenessReadmeWriter {

    /** Guest-relative path owned by NusaDesk. */
    public static final String GUEST_RELATIVE_PATH = "root/README.md";
    /** Guest-relative docs directory owned by NusaDesk. */
    public static final String GUEST_DOCS_RELATIVE_PATH = "root/docs";
    /** Guest-relative bin directory that receives the CLI. */
    public static final String GUEST_BIN_RELATIVE_PATH = "usr/local/bin";
    /** Guest-relative CLI path, executable on PATH. */
    public static final String GUEST_CLI_RELATIVE_PATH = "usr/local/bin/nusadesk-android";
    /** CLI file name inside the fixed bin parent. */
    public static final String CLI_FILE_NAME = "nusadesk-android";
    /** Guest session configuration pinned by the bridge. */
    public static final String GUEST_ENV_FILE_PATH = "/run/nusadesk/android-bridge.env";

    private static final String TEMP_PREFIX = ".nusadesk-";
    private static final String TEMP_SUFFIX = ".tmp";
    private static final String README_PERMISSIONS = "rw-r--r--";
    private static final String CLI_PERMISSIONS = "rwxr-xr-x";

    /** Outcome of an idempotent ensure operation. */
    public enum Result {
        UNCHANGED,
        UPDATED
    }

    private GuestAwarenessReadmeWriter() {
    }

    /**
     * Ensure the whole awareness bundle (README, docs index and topic docs,
     * and the executable CLI) matches the current app version.
     *
     * @param activeRootfs validated active rootfs directory
     * @param appVersion APK version name, not user input
     * @return whether any file was updated or everything was already current
     * @throws IOException when a fixed path is unsafe or cannot be written
     */
    public static Result ensure(Path activeRootfs, String appVersion) throws IOException {
        if (activeRootfs == null) {
            throw new IllegalArgumentException("activeRootfs must not be null");
        }
        String version = requireVersion(appVersion);
        Path root = prepareDirectory(activeRootfs, "root", "guest /root");
        Path docs = prepareDirectory(root, "docs", "guest /root/docs");
        Path bin = prepareDirectory(activeRootfs, "usr/local/bin", "guest /usr/local/bin");
        Path shimDir = prepareDirectory(activeRootfs, "opt/nusadesk", "guest /opt/nusadesk");

        boolean updated = false;
        updated |= ensureFile(root.resolve("README.md"),
                content(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("README.md"),
                docsIndexContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("bridge.md"),
                bridgeDocContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("media.md"),
                mediaDocContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("battery-sensors-location.md"),
                batterySensorsLocationDocContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("messaging-telephony.md"),
                messagingTelephonyDocContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("calendar.md"),
                calendarDocContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= ensureFile(bin.resolve(CLI_FILE_NAME),
                cliContent(version).getBytes(StandardCharsets.UTF_8), CLI_PERMISSIONS);
        updated |= ensureFile(bin.resolve(GuestUsbCliWriter.CLI_FILE_NAME),
                GuestUsbCliWriter.scriptContent(version)
                        .getBytes(StandardCharsets.UTF_8), CLI_PERMISSIONS);
        updated |= ensureFile(bin.resolve(GuestUsbDaemonWriter.DAEMON_FILE_NAME),
                GuestUsbDaemonWriter.scriptContent(version)
                        .getBytes(StandardCharsets.UTF_8), CLI_PERMISSIONS);
        updated |= ensureFile(bin.resolve(GuestUsbShimWriter.WRAPPER_FILE_NAME),
                GuestUsbShimWriter.adbWrapperContent(version)
                        .getBytes(StandardCharsets.UTF_8), CLI_PERMISSIONS);
        updated |= ensureFile(shimDir.resolve(GuestUsbShimWriter.SHIM_FILE_NAME),
                GuestUsbShimWriter.shimSource(version)
                        .getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureTermuxCompat(bin, docs, version);
        return updated ? Result.UPDATED : Result.UNCHANGED;
    }

    /**
     * Install the Termux command compatibility layer (ADR-0036): one generated
     * script per supported Termux command name, plus its documentation page.
     * The files are owned by this writer like every other generated guest
     * file, so an app update refreshes them and manual edits are overwritten.
     * A script this writer once installed but that is no longer in
     * {@link GuestTermuxCompatWriter#COMMANDS} is swept, so a shrinking command
     * set cannot leave a stale executable behind.
     */
    private static boolean ensureTermuxCompat(Path bin, Path docs,
                                              String version) throws IOException {
        boolean updated = false;
        for (String command : GuestTermuxCompatWriter.COMMANDS) {
            updated |= ensureFile(bin.resolve(command),
                    GuestTermuxCompatWriter.scriptContent(command, version)
                            .getBytes(StandardCharsets.UTF_8),
                    CLI_PERMISSIONS);
        }
        updated |= ensureFile(docs.resolve("termux-compat.md"),
                GuestTermuxCompatWriter.docContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= sweepStaleTermuxCompat(bin);
        return updated;
    }

    /**
     * Delete a previously generated Termux-compat script whose command is no
     * longer declared. Only a regular (never a symlink) file whose name starts
     * with {@code termux-} and whose content carries this writer's marker is
     * eligible, so a user file or another tool's file is never touched.
     */
    private static boolean sweepStaleTermuxCompat(Path bin) throws IOException {
        Set<String> declared = new HashSet<>(Arrays.asList(GuestTermuxCompatWriter.COMMANDS));
        boolean removed = false;
        try (DirectoryStream<Path> entries = Files.newDirectoryStream(bin)) {
            for (Path entry : entries) {
                String name = entry.getFileName().toString();
                if (!name.startsWith("termux-") || declared.contains(name)) {
                    continue;
                }
                if (!Files.isRegularFile(entry, LinkOption.NOFOLLOW_LINKS)) {
                    continue;
                }
                if (!carriesTermuxCompatMarker(entry)) {
                    continue;
                }
                Files.delete(entry);
                removed = true;
            }
        }
        return removed;
    }

    private static boolean carriesTermuxCompatMarker(Path file) throws IOException {
        // Open with NOFOLLOW so a symlink swapped in after the check above is
        // never read through; the marker is only ever in our own regular files.
        Set<java.nio.file.OpenOption> options = new HashSet<>();
        options.add(StandardOpenOption.READ);
        options.add(LinkOption.NOFOLLOW_LINKS);
        try (java.nio.channels.SeekableByteChannel channel =
                     Files.newByteChannel(file, options);
             BufferedReader reader = new BufferedReader(
                     new java.io.InputStreamReader(
                             java.nio.channels.Channels.newInputStream(channel),
                             StandardCharsets.UTF_8))) {
            for (int line = 0; line < 3; line++) {
                String text = reader.readLine();
                if (text == null) {
                    return false;
                }
                if (text.contains(GuestTermuxCompatWriter.MARKER)) {
                    return true;
                }
            }
        }
        return false;
    }

    /** Canonical README text, public for focused tests and documentation tooling. */
    public static String content(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# NusaDesk Linux",
                "",
                "NusaDesk provides:",
                "- Ubuntu Base ARM64 Linux guest through PRoot",
                "- Local guest terminal at 127.0.0.1:22022",
                "- Product-owned systemctl3 bridge (system and `--user` units)",
                "- Bounded `udocker compose` support",
                "- Best-effort Android battery bridge at `/sys/class/power_supply/battery`",
                "- Termux command compatibility clients in `/usr/local/bin`",
                "- Optional Android workspace at `~/nusadesk`",
                "- Android-owned lifecycle, DNS doctor, and session-temporary `/tmp`",
                "",
                "## Documentation",
                "",
                "Guest-facing documentation is generated and owned by the app:",
                "",
                "- [Guest documentation index](docs/README.md)",
                "- [Android capability bridge](docs/bridge.md)",
                "- [Live media (camera + microphone)](docs/media.md)",
                "- [Battery, sensors, and location](docs/battery-sensors-location.md)",
                "- [Messaging and telephony](docs/messaging-telephony.md)",
                "- [Calendar events](docs/calendar.md)",
                "- [Termux command compatibility](docs/termux-compat.md)",
                "",
                "> This file is managed by the NusaDesk Android app. It is writable in",
                "> the guest and may be regenerated after an app update.",
                "> App version: " + version,
                "",
                "This is a PRoot guest, not a VM or full Docker environment.",
                "",
                "") + "\n";
    }

    /** Canonical docs index text. */
    public static String docsIndexContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# NusaDesk Guest Documentation",
                "",
                "This directory is generated and owned by the NusaDesk Android app.",
                "Manual edits may be overwritten on the next session start.",
                "",
                "## Topics",
                "",
                "- [Android capability bridge](bridge.md)",
                "- [Live media (camera + microphone)](media.md)",
                "- [Battery, sensors, and location](battery-sensors-location.md)",
                "- [Messaging and telephony](messaging-telephony.md)",
                "- [Calendar events](calendar.md)",
                "- [Termux command compatibility](termux-compat.md)",
                "",
                "## Command-line tool",
                "",
                "`nusadesk-android` is installed at `/usr/local/bin/nusadesk-android`:",
                "",
                "- `nusadesk-android media start [--camera|--microphone]` - live",
                "  media session (camera, microphone, or both)",
                "- `nusadesk-android calendar list` - next seven days of events",
                "- `nusadesk-android calendar add --title TITLE --begin-ms EPOCH",
                "  --end-ms EPOCH [--all-day] [--location LOCATION]` - create one event",
                "- `nusadesk-android calendar update EVENT_ID [--title TITLE]",
                "  [--begin-ms EPOCH --end-ms EPOCH] [--all-day|--timed]",
                "  [--location LOCATION]` - change one event",
                "- `nusadesk-android calendar delete EVENT_ID` - remove one event",
                "- `nusadesk-android bridge info` - bridge discovery",
                "",
                "See [media.md](media.md) for the live stream contract,",
                "[calendar.md](calendar.md) for the calendar contract,",
                "[termux-compat.md](termux-compat.md) for the installed Termux",
                "command names, and",
                "[bridge.md](bridge.md) for the transport and protocol.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical bridge transport and protocol doc. */
    public static String bridgeDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Android capability bridge",
                "",
                "NusaDesk exposes a small, authenticated capability bridge to the",
                "guest for the active PRoot session. It is loopback-only, never bound",
                "to the LAN, and dispatches only fixed method names; it is not a shell",
                "and no guest-supplied method, class, or URI is ever dispatched. The",
                "envelope is param-free except for the calendar writes, which carry",
                "one bounded `params` object (see below).",
                "",
                "## Session configuration",
                "",
                "The address, port, protocol version, and session token are owned by",
                "the app and pinned in `/run/nusadesk/android-bridge.env`:",
                "",
                "- `NUSADESK_ANDROID_BRIDGE_ADDRESS=127.0.0.1`",
                "- `NUSADESK_ANDROID_BRIDGE_PORT=<ephemeral port>`",
                "- `NUSADESK_ANDROID_BRIDGE_TOKEN=<session token>`",
                "- `NUSADESK_ANDROID_BRIDGE_PROTOCOL=1`",
                "",
                "The token authenticates every request because loopback is only a",
                "reachability boundary, not an identity boundary. The token is never",
                "printed by `nusadesk-android`.",
                "",
                "## Protocol",
                "",
                "One connection carries exactly one newline-delimited JSON request and",
                "receives one JSON response on the same connection. The envelope is a",
                "flat object:",
                "",
                "- `v` - fixed protocol version (`1`)",
                "- `id` - bounded, unique per invocation",
                "- `token` - the session token",
                "- `method` - one fixed allowlist method",
                "- `params` - optional bounded object, only for the methods that",
                "  declare it",
                "",
                "## Bounded params",
                "",
                "Only `calendar.insert`, `calendar.update`, and `calendar.delete`",
                "declare parameters. `params` there is a flat object of at most 8 keys,",
                "each key at most 32 characters, string values at most 256 characters:",
                "",
                "- `calendar.insert` - `title` (required), `begin_ms` (required),",
                "  `end_ms` (required), `all_day`, `location`, `calendar_id`",
                "- `calendar.update` - `event_id` (required) plus at least one of",
                "  `title`, `location`, `all_day`, or the `begin_ms` + `end_ms` pair",
                "- `calendar.delete` - `event_id` (required)",
                "",
                "Nested objects, arrays, oversized keys or values, and control",
                "characters are rejected. A method that does not declare parameters",
                "answers `unsupported-parameter` when one is sent, so a request never",
                "carries input that is silently ignored; an unknown key inside a",
                "declaring method is `calendar-invalid-argument`.",
                "",
                "Responses are one flat JSON line: success carries `ok` = `true` plus",
                "method fields; failure carries `ok` = `false` plus a typed `error`.",
                "Frames are bounded (16 KiB), and the bridge applies a socket timeout",
                "and a bounded concurrency cap per session.",
                "",
                "## Methods",
                "",
                "- `bridge.info` - transport and capability list",
                "- `battery.status` - Android battery snapshot",
                "- `sensor.accelerometer`, `sensor.gyroscope` - one-shot reads",
                "- `location.get` - one foreground one-shot fix",
                "- `location.stream.start`, `location.stream.poll`,",
                "  `location.stream.stop` - one foreground pull stream",
                "- `contacts.list`, `calllog.list`, `sms.inbox`, `telephony.info`,",
                "  `telephony.cellinfo` - read-only, bounded row reads",
                "- `media.start`, `media.camera.start`, `media.microphone.start`,",
                "  `media.status`, `media.stop` - live media session",
                "- `calendar.list` - bounded read of the next seven days",
                "- `calendar.insert`, `calendar.update`, `calendar.delete` - bounded",
                "  writes into the user's own calendars",
                "",
                "## Client",
                "",
                "`nusadesk-android` wraps the envelope with a fixed allowlist:",
                "",
                "- `nusadesk-android bridge info` - discovery",
                "- `nusadesk-android media start [--camera|--microphone]`,",
                "  `media status`, `media stop` - live media control",
                "- `nusadesk-android calendar list`, `calendar add ...`,",
                "  `calendar update EVENT_ID ...`, `calendar delete EVENT_ID` -",
                "  bounded calendar access",
                "",
                "There is no `nusadesk-android call <method>`. The CLI never forwards",
                "a user-supplied method name, and it never forwards a raw JSON",
                "`params` object either: the calendar commands build the bounded",
                "parameters from typed flags, so an unknown key cannot be expressed.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical live media contract doc. */
    public static String mediaDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Live media (camera and/or microphone)",
                "",
                "Live media is the guest camera/microphone session. Android captures",
                "with Camera2 and AudioRecord, encodes H.264 video and AAC-LC audio",
                "with hardware encoders, and serves one loopback-only RTSP-over-TCP",
                "stream. The session is live-only: NusaDesk never writes a capture",
                "file, never persists recorded media, and exposes no artifact path.",
                "Save a file yourself from the stream if you need one.",
                "",
                "There are three track modes, one session at a time:",
                "",
                "| mode | tracks | command |",
                "| --- | --- | --- |",
                "| `both` | camera + microphone | `nusadesk-android media start` |",
                "| `camera` | camera only | `nusadesk-android media start --camera` |",
                "| `microphone` | microphone only | `nusadesk-android media start --microphone` |",
                "",
                "A camera-only session never asks for the microphone grant, and a",
                "microphone-only session never asks for the camera grant. Asking for",
                "another mode while a session runs returns `media-mode-conflict`;",
                "stop the running session first.",
                "",
                "## Lifetime",
                "",
                "The stream lives only while both of these hold:",
                "",
                "- the guest bridge session for this app is live, and",
                "- the user-visible foreground media service for the active mode runs.",
                "",
                "`media stop` stops the service; closing the bridge session also",
                "tears the stream down. Nothing is stored for resuming later.",
                "",
                "## Commands",
                "",
                "- `nusadesk-android media start` - start camera + microphone; on",
                "  success the JSON response reports `state` = `running` and the",
                "  `rtsp_url`",
                "- `nusadesk-android media start --camera` - start camera only",
                "- `nusadesk-android media start --microphone` - start microphone only",
                "- `nusadesk-android media status` - always ok; reports the explicit",
                "  `state` (`stopped`, `starting`, `running`, `failed`) and the",
                "  active `mode`",
                "- `nusadesk-android media stop` - idempotent; always reports",
                "  `state` = `stopped`",
                "",
                "## States",
                "",
                "| state | meaning |",
                "| --- | --- |",
                "| `stopped` | no live session |",
                "| `starting` | start accepted, pipeline coming up |",
                "| `running` | RTSP listening on loopback, the mode's encoders producing |",
                "| `failed` | session failed with a typed `error` |",
                "",
                "## Running response",
                "",
                "In the running state the response carries flat fields: `state` =",
                "`running`, `mode` (`both`, `camera`, `microphone`), `rtsp_url` =",
                "`rtsp://127.0.0.1:<port>/`, and `client_limit` = 2.",
                "",
                "Video fields appear only for a video mode: `video_codec` = `h264`,",
                "`video_width` / `video_height` (target at most 1280 x 720), and",
                "`video_fps` = 30.",
                "",
                "Audio fields appear only for an audio mode: `audio_codec` = `aac`.",
                "",
                "A microphone-only session therefore reports no video size, and a",
                "camera-only session reports no audio codec — the status never",
                "implies a track that does not exist.",
                "",
                "The stream binds only to `127.0.0.1` and serves RTSP over TCP with",
                "a bounded client cap (`client_limit`). It is never exposed on the",
                "LAN. The SDP advertises exactly the tracks of the active mode, and",
                "`SETUP` for a track the mode does not carry answers `404`.",
                "",
                "## Consuming the stream",
                "",
                "Use the `rtsp_url` from a successful start or a running",
                "`media status`:",
                "",
                "```sh",
                "ffplay -rtsp_transport tcp 'rtsp://127.0.0.1:<port>/'",
                "ffmpeg -rtsp_transport tcp -i 'rtsp://127.0.0.1:<port>/' -c copy out.mp4",
                "# microphone-only session: keep just the audio track",
                "ffmpeg -rtsp_transport tcp -i 'rtsp://127.0.0.1:<port>/' -vn -c:a copy out.m4a",
                "# camera-only session: keep just the video track",
                "ffmpeg -rtsp_transport tcp -i 'rtsp://127.0.0.1:<port>/' -an -c:v copy out.h264",
                "```",
                "",
                "OpenCV (C++ or Python) can open the same URL with the TCP transport.",
                "Saving is manual; NusaDesk does not persist the stream.",
                "",
                "## Permissions and foreground",
                "",
                "The bridge never opens a permission prompt. Each mode needs only its",
                "own grants: CAMERA for a camera mode, RECORD_AUDIO for an audio mode,",
                "both for the combined mode. A missing or denied grant is a typed",
                "`media-*` error, never a prompt. Capture is user-visible foreground",
                "work, and the notification names only the active mode's tracks.",
                "",
                "## Typed errors",
                "",
                "| error | meaning |",
                "| --- | --- |",
                "| `media-permission-required` | a grant the mode needs is missing, no denial on record |",
                "| `media-permission-denied` | a grant the mode needs was denied |",
                "| `media-foreground-required` | app not eligible to start the camera/microphone foreground service |",
                "| `media-unavailable` | platform cannot serve the stream |",
                "| `media-busy` | a start is already in flight or the camera is in use |",
                "| `media-mode-conflict` | another mode is already running; stop it first |",
                "| `media-encoder-unavailable` | a hardware encoder or codec metadata is not ready |",
                "| `media-start-failed` | start did not complete within its bound |",
                "",
                "## Retired artifact commands",
                "",
                "`camera.snapshot` and `mic.record` are retired. They are not exposed",
                "by this bridge, their artifact paths no longer exist, and no guest",
                "capture file is produced anywhere. The live-only session above is",
                "the camera/microphone surface.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical battery, sensors, and location doc. */
    public static String batterySensorsLocationDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Battery, sensors, and location",
                "",
                "## Battery",
                "",
                "- `battery.status` - one Android BatteryManager snapshot",
                "- `/sys/class/power_supply/battery` - a best-effort app-owned",
                "  projection refreshed every two seconds while the session is live.",
                "  It is not real kernel sysfs; treat it as an app snapshot and let",
                "  the app own it.",
                "",
                "## Sensors",
                "",
                "- `sensor.accelerometer` - one-shot accelerometer reading",
                "- `sensor.gyroscope` - one-shot gyroscope reading",
                "",
                "Unavailable and timeout states are typed errors.",
                "",
                "## Location",
                "",
                "- `location.get` - one foreground one-shot fix",
                "- `location.stream.start` - start one foreground pull stream at a",
                "  fixed 5 second interval",
                "- `location.stream.poll` - read the next fix with a bounded wait",
                "- `location.stream.stop` - idempotent stop",
                "",
                "Location is foreground-only and pull-based and lives only while the",
                "bridge session is live. The bridge never opens a background location",
                "and never surfaces an automatic permission prompt.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical messaging and telephony doc. */
    public static String messagingTelephonyDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Messaging and telephony",
                "",
                "Read-only, bounded guest surfaces:",
                "",
                "- `contacts.list` - contacts snapshot",
                "- `calllog.list` - call log snapshot",
                "- `sms.inbox` - SMS inbox snapshot",
                "- `telephony.info` - device telephony information",
                "- `telephony.cellinfo` - serving cell information",
                "",
                "All reads use fixed defaults and return bounded rows. The response",
                "reports `count`, and rows dropped by the byte bound set",
                "`truncated` = `true`. Permission, denial, unavailability, and",
                "no-telephony states are typed errors.",
                "",
                "Side-effecting operations are deliberately not offered:",
                "`sms.send` and `phone.call` are never dispatched and answer with a",
                "typed unsupported result.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical calendar read/write contract doc. */
    public static String calendarDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Calendar (read and bounded write)",
                "",
                "NusaDesk exposes the user's own Android calendars to the guest: a",
                "bounded read of upcoming events and bounded create, update, and",
                "delete calls. It never touches attendees, never writes an attendee",
                "row, and never sends an invitation, so a guest automation cannot mail",
                "other people on the user's behalf.",
                "",
                "## Permissions",
                "",
                "- `calendar.list` needs `READ_CALENDAR`",
                "- `calendar.insert` / `calendar.update` / `calendar.delete` need",
                "  `WRITE_CALENDAR`",
                "",
                "The app never opens a consent dialog from the guest. A missing grant",
                "is a typed error the script can report: `calendar-permission-required`",
                "when no decision was recorded, `calendar-permission-denied` when the",
                "user previously refused or revoked it. The grant is the user's own",
                "decision from Android App Info.",
                "",
                "## Reading upcoming events",
                "",
                "`nusadesk-android calendar list` reads the provider's instance table",
                "for a fixed window: from now to seven days later. The window and the",
                "row limit are owned by the host; the guest cannot widen them.",
                "",
                "Each event row carries:",
                "",
                "- `event_id`, `title`",
                "- `begin_utc_ms`, `end_utc_ms` - UTC milliseconds",
                "- `all_day` - an all-day event spans whole UTC days",
                "- `calendar_id`, `calendar_name`, `timezone`",
                "- `location` - only when the event has one",
                "",
                "The response also carries `count` and `truncated`. At most 50 rows are",
                "returned; `truncated` = `true` means more events fell inside the window",
                "than the read could return, so a bounded answer never looks complete.",
                "Because the read goes through the instance table, repeating events are",
                "expanded by the platform, including their exceptions.",
                "",
                "The description, attendees, organizer address, reminders, and every",
                "other provider column are never read. Attendee addresses are other",
                "people's data and never cross the bridge.",
                "",
                "## Writing one event",
                "",
                "Writes target the user's own calendars and are validated before any",
                "provider call:",
                "",
                "| rule | bound |",
                "| --- | --- |",
                "| title / location | at most 200 characters, no control characters |",
                "| range | `begin` before `end`, at most 24 hours long |",
                "| start time | at most 24 hours in the past, at most 366 days ahead |",
                "| all-day | range must be whole UTC days, at least one day long |",
                "| target calendar | access level contributor or better |",
                "",
                "An insert without `calendar_id` goes to the primary writable calendar,",
                "or to the first writable one when no calendar is marked primary. A",
                "calendar the user only reads answers `calendar-read-only`; an event",
                "that no longer exists answers `calendar-not-found`.",
                "",
                "Setting `all_day` to `true` requires the range in the same call, because",
                "the whole-day rule is checked against it. Pass `all_day` = `false`",
                "(`--timed`) to turn an all-day event back into a timed one.",
                "",
                "## Commands",
                "",
                "```sh",
                "# the next seven days",
                "nusadesk-android calendar list",
                "",
                "# create an event from epoch milliseconds",
                "nusadesk-android calendar add --title 'Rapat' \\",
                "  --begin-ms 1760003600000 --end-ms 1760007200000",
                "",
                "# move or rename it later",
                "nusadesk-android calendar update 500 --title 'Rapat baru'",
                "",
                "# remove it",
                "nusadesk-android calendar delete 500",
                "```",
                "",
                "A write reports `written` = `true` and the affected `event_id`.",
                "`calendar add` requires `--title`, `--begin-ms`, and `--end-ms`;",
                "`calendar update` requires the event id and at least one change;",
                "`calendar delete` requires only the event id. The CLI builds the",
                "bounded parameters from these typed flags, so an unknown parameter",
                "cannot be expressed and never reaches the app.",
                "",
                "## Errors",
                "",
                "| error | meaning |",
                "| --- | --- |",
                "| `calendar-permission-required` | no calendar grant yet |",
                "| `calendar-permission-denied` | the user refused or revoked it |",
                "| `calendar-unavailable` | no provider or no writable calendar |",
                "| `calendar-invalid-argument` | a parameter failed a bound above |",
                "| `calendar-read-only` | the target calendar is not writable |",
                "| `calendar-not-found` | the event id does not exist |",
                "| `calendar-failed` | the provider refused the write |",
                "",
                "## Notes",
                "",
                "- All-day events are stored on UTC day boundaries; treat `begin_utc_ms`",
                "  and `end_utc_ms` as dates for them, not as local wall-clock times.",
                "- Rows come from whichever calendars the Android Calendar app shows,",
                "  including read-only ones the user subscribed to; only writable ones",
                "  accept a write.",
                "- The bridge keeps no calendar state: every read and write goes to the",
                "  provider, and the audit line records only the operation and ids,",
                "  never the title or location.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /**
     * Canonical executable Python 3 CLI content. The script ships with
     * executable bits set by the writer; it is deliberately small and
     * bounded: fixed allowlist commands only, no shell execution, no user
     * method passthrough, and the session token is never printed.
     */
    public static String cliContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "#!/usr/bin/env python3",
                "# NusaDesk Android bridge CLI - generated by the NusaDesk Android app.",
                "# App version: " + version,
                "# Fixed session env: " + GUEST_ENV_FILE_PATH,
                "# This tool issues only the fixed allowlisted methods below. It never",
                "# runs a shell, never takes a user-supplied method name, and never",
                "# prints the session token. Calendar writes build their bounded",
                "# params object from typed flags, never from a raw JSON argument.",
                "",
                "import json",
                "import secrets",
                "import socket",
                "import sys",
                "",
                "ENV_FILE = '" + GUEST_ENV_FILE_PATH + "'",
                "SOCKET_TIMEOUT_SECONDS = 15.0",
                "MAX_CONFIG_LINE_BYTES = 1024",
                "MAX_RESPONSE_BYTES = 16384",
                "PROTOCOL_VERSION = 1",
                "ENV_ADDRESS = 'NUSADESK_ANDROID_BRIDGE_ADDRESS'",
                "ENV_PORT = 'NUSADESK_ANDROID_BRIDGE_PORT'",
                "ENV_TOKEN = 'NUSADESK_ANDROID_BRIDGE_TOKEN'",
                "ENV_PROTOCOL = 'NUSADESK_ANDROID_BRIDGE_PROTOCOL'",
                "TOKEN_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-'",
                "USAGE = 'usage: nusadesk-android media start [--camera|--microphone]"
                        + " | media status | media stop | bridge info"
                        + " | calendar list"
                        + " | calendar add --title TITLE --begin-ms EPOCH_MS"
                        + " --end-ms EPOCH_MS [--all-day] [--location LOCATION]"
                        + " | calendar update EVENT_ID [--title TITLE]"
                        + " [--begin-ms EPOCH_MS --end-ms EPOCH_MS]"
                        + " [--all-day|--timed] [--location LOCATION]"
                        + " | calendar delete EVENT_ID'",
                "",
                "# Fixed allowlist only; there is deliberately no generic call",
                "# passthrough and no arbitrary method command.",
                "COMMANDS = {",
                "    'media start': 'media.start',",
                "    'media start --camera': 'media.camera.start',",
                "    'media start --microphone': 'media.microphone.start',",
                "    'media status': 'media.status',",
                "    'media stop': 'media.stop',",
                "    'bridge info': 'bridge.info',",
                "    'calendar list': 'calendar.list',",
                "}",
                "",
                "# Calendar writes take typed flags only: the bounded params object is",
                "# built here, so a raw JSON payload or an unknown key cannot be sent.",
                "CALENDAR_VALUE_FLAGS = {",
                "    '--title': 'title',",
                "    '--location': 'location',",
                "}",
                "CALENDAR_EPOCH_FLAGS = {",
                "    '--begin-ms': 'begin_ms',",
                "    '--end-ms': 'end_ms',",
                "}",
                "MAX_TITLE_CHARS = 200",
                "MAX_EPOCH_CHARS = 19",
                "",
                "",
                "class CliError(Exception):",
                "    pass",
                "",
                "",
                "def parse_args(argv):",
                "    if not argv:",
                "        raise CliError(USAGE)",
                "    if argv[0] == 'calendar':",
                "        return parse_calendar(argv)",
                "    if len(argv) == 2:",
                "        key = argv[0] + ' ' + argv[1]",
                "    elif len(argv) == 3:",
                "        key = argv[0] + ' ' + argv[1] + ' ' + argv[2]",
                "    else:",
                "        raise CliError(USAGE)",
                "    method = COMMANDS.get(key)",
                "    if method is None:",
                "        raise CliError(USAGE)",
                "    return method, None",
                "",
                "",
                "def parse_calendar(argv):",
                "    if len(argv) < 2:",
                "        raise CliError(USAGE)",
                "    command = argv[0] + ' ' + argv[1]",
                "    rest = argv[2:]",
                "    if command == 'calendar list':",
                "        if rest:",
                "            raise CliError(USAGE)",
                "        return 'calendar.list', None",
                "    if command == 'calendar delete':",
                "        if len(rest) != 1:",
                "            raise CliError(USAGE)",
                "        return 'calendar.delete', {'event_id': parse_epoch(rest[0])}",
                "    if command == 'calendar add':",
                "        params = parse_calendar_changes(rest)",
                "        for required in ('title', 'begin_ms', 'end_ms'):",
                "            if required not in params:",
                "                raise CliError(USAGE)",
                "        return 'calendar.insert', params",
                "    if command == 'calendar update':",
                "        if not rest:",
                "            raise CliError(USAGE)",
                "        params = parse_calendar_changes(rest[1:])",
                "        if not params:",
                "            raise CliError(USAGE)",
                "        params['event_id'] = parse_epoch(rest[0])",
                "        return 'calendar.update', params",
                "    raise CliError(USAGE)",
                "",
                "",
                "def parse_calendar_changes(tokens):",
                "    params = {}",
                "    while tokens:",
                "        flag = tokens[0]",
                "        if flag in ('--all-day', '--timed'):",
                "            if 'all_day' in params:",
                "                raise CliError(USAGE)",
                "            params['all_day'] = flag == '--all-day'",
                "            tokens = tokens[1:]",
                "            continue",
                "        if flag in CALENDAR_VALUE_FLAGS or flag in CALENDAR_EPOCH_FLAGS:",
                "            if len(tokens) < 2:",
                "                raise CliError(USAGE)",
                "            if flag in CALENDAR_EPOCH_FLAGS:",
                "                key = CALENDAR_EPOCH_FLAGS[flag]",
                "                value = parse_epoch(tokens[1])",
                "            else:",
                "                key = CALENDAR_VALUE_FLAGS[flag]",
                "                value = parse_title(tokens[1])",
                "            if key in params:",
                "                raise CliError(USAGE)",
                "            params[key] = value",
                "            tokens = tokens[2:]",
                "            continue",
                "        raise CliError(USAGE)",
                "    if ('begin_ms' in params) != ('end_ms' in params):",
                "        raise CliError(USAGE)",
                "    return params",
                "",
                "",
                "def parse_epoch(text):",
                "    if not text.isascii() or not text.isdigit():",
                "        raise CliError(USAGE)",
                "    if len(text) > MAX_EPOCH_CHARS:",
                "        raise CliError(USAGE)",
                "    value = int(text, 10)",
                "    if value < 1:",
                "        raise CliError(USAGE)",
                "    return value",
                "",
                "",
                "def parse_title(text):",
                "    if not text or len(text) > MAX_TITLE_CHARS:",
                "        raise CliError(USAGE)",
                "    if any(ord(ch) < 32 or ord(ch) == 127 for ch in text):",
                "        raise CliError(USAGE)",
                "    return text",
                "",
                "",
                "def load_config(path):",
                "    values = {}",
                "    try:",
                "        with open(path, 'r', encoding='ascii') as handle:",
                "            for raw in handle:",
                "                if len(raw) > MAX_CONFIG_LINE_BYTES:",
                "                    raise CliError('session env line too long')",
                "                line = raw.strip()",
                "                if not line or line.startswith('#'):",
                "                    continue",
                "                if '=' not in line:",
                "                    raise CliError('malformed session env line')",
                "                key, _, value = line.partition('=')",
                "                key = key.strip()",
                "                value = value.strip()",
                "                if key not in (ENV_ADDRESS, ENV_PORT, ENV_TOKEN,",
                "                                ENV_PROTOCOL):",
                "                    raise CliError('unexpected session env key')",
                "                if key in values:",
                "                    raise CliError('duplicate session env key')",
                "                values[key] = value",
                "    except (IOError, UnicodeDecodeError, CliError) as error:",
                "        if isinstance(error, CliError):",
                "            raise",
                "        raise CliError('cannot read session env')",
                "    address = values.get(ENV_ADDRESS)",
                "    port_text = values.get(ENV_PORT)",
                "    token = values.get(ENV_TOKEN)",
                "    protocol = values.get(ENV_PROTOCOL)",
                "    if address != '127.0.0.1':",
                "        raise CliError('bridge address must be loopback only')",
                "    if protocol != str(PROTOCOL_VERSION):",
                "        raise CliError('unsupported bridge protocol version')",
                "    try:",
                "        port = int(port_text, 10)",
                "    except (TypeError, ValueError):",
                "        raise CliError('invalid session env port')",
                "    if port < 1 or port > 65535:",
                "        raise CliError('invalid session env port')",
                "    if token is None or len(token) < 16 or len(token) > 256:",
                "        raise CliError('invalid session env token')",
                "    if any(ch not in TOKEN_ALPHABET for ch in token):",
                "        raise CliError('invalid session env token')",
                "    return address, port, token",
                "",
                "",
                "def build_request(method, token, params):",
                "    request = {",
                "        'v': PROTOCOL_VERSION,",
                "        'id': secrets.token_urlsafe(8),",
                "        'token': token,",
                "        'method': method,",
                "    }",
                "    if params is not None:",
                "        request['params'] = params",
                "    return json.dumps(request, separators=(',', ':'),",
                "                      ensure_ascii=True)",
                "",
                "",
                "def call(address, port, token, method, params):",
                "    payload = build_request(method, token, params)",
                "    with socket.create_connection((address, port),",
                "                                  timeout=SOCKET_TIMEOUT_SECONDS) as sock:",
                "        sock.settimeout(SOCKET_TIMEOUT_SECONDS)",
                "        sock.sendall(payload.encode('ascii') + bytes([10]))",
                "        outgoing = bytearray()",
                "        while True:",
                "            chunk = sock.recv(4096)",
                "            if not chunk:",
                "                break",
                "            outgoing.extend(chunk)",
                "            if 10 in outgoing:",
                "                break",
                "            if len(outgoing) > MAX_RESPONSE_BYTES:",
                "                raise CliError('response too large')",
                "    if not outgoing:",
                "        raise CliError('empty bridge response')",
                "    line = outgoing.split(bytes([10]), 1)[0]",
                "    if len(line) > MAX_RESPONSE_BYTES:",
                "        raise CliError('response too large')",
                "    text = line.decode('utf-8')",
                "    try:",
                "        parsed = json.loads(text)",
                "    except ValueError:",
                "        raise CliError('bridge response is not JSON')",
                "    if not isinstance(parsed, dict):",
                "        raise CliError('bridge response is not a JSON object')",
                "    if parsed.get('v') != PROTOCOL_VERSION:",
                "        raise CliError('unsupported bridge response version')",
                "    return text, parsed",
                "",
                "",
                "def main(argv):",
                "    if len(argv) == 1 and argv[0] in ('-h', '--help'):",
                "        print(USAGE)",
                "        return 0",
                "    try:",
                "        method, params = parse_args(argv)",
                "        address, port, token = load_config(ENV_FILE)",
                "        text, parsed = call(address, port, token, method, params)",
                "    except CliError as error:",
                "        print('nusadesk-android: ' + str(error), file=sys.stderr)",
                "        return 2",
                "    except OSError:",
                "        print('nusadesk-android: bridge socket connection failed',",
                "              file=sys.stderr)",
                "        return 2",
                "    print(text)",
                "    if not parsed.get('ok'):",
                "        return 1",
                "    return 0",
                "",
                "",
                "if __name__ == '__main__':",
                "    sys.exit(main(sys.argv[1:]))",
                "") + "\n";
    }

    private static String generatedFooter(String version) {
        return "> Docs generated by the NusaDesk Android app (version " + version
                + "). Manual edits may be overwritten on the next session start.";
    }

    private static String requireVersion(String appVersion) {
        return requireVersionForWriter(appVersion);
    }

    /**
     * Shared version guard for every generated guest file: a single safe line,
     * no control characters, non-blank.
     */
    static String requireVersionForWriter(String appVersion) {
        if (appVersion == null || appVersion.trim().isEmpty()) {
            throw new IllegalArgumentException("appVersion must be a single safe line");
        }
        for (int i = 0; i < appVersion.length(); i++) {
            char c = appVersion.charAt(i);
            if (c < 0x20 || c == 0x7f) {
                throw new IllegalArgumentException(
                        "appVersion must be a single safe line");
            }
        }
        return appVersion.trim();
    }

    /**
     * Resolve one fixed relative parent, creating missing segments and
     * failing closed the moment any segment is a symlink or not a real
     * directory.
     */
    private static Path prepareDirectory(Path base, String relative, String description)
            throws IOException {
        Path cursor = base;
        for (String segment : relative.split("/")) {
            cursor = cursor.resolve(segment);
            if (Files.exists(cursor, LinkOption.NOFOLLOW_LINKS)) {
                if (Files.isSymbolicLink(cursor)
                        || !Files.isDirectory(cursor, LinkOption.NOFOLLOW_LINKS)) {
                    throw new IOException(description + " is not a real directory: " + cursor);
                }
            } else {
                Files.createDirectory(cursor);
            }
        }
        return cursor;
    }

    /** @return true when {@code target} was (re)written; false when it was already current */
    private static boolean ensureFile(Path target, byte[] expected, String permissions)
            throws IOException {
        if (Files.isRegularFile(target, LinkOption.NOFOLLOW_LINKS)
                && sameBytes(target, expected)) {
            setPermissions(target, permissions);
            return false;
        }
        Path temporary = Files.createTempFile(target.getParent(), TEMP_PREFIX, TEMP_SUFFIX);
        try {
            Files.write(temporary, expected, StandardOpenOption.TRUNCATE_EXISTING);
            setPermissions(temporary, permissions);
            moveAtomically(temporary, target);
            setPermissions(target, permissions);
            return true;
        } catch (IOException | RuntimeException failure) {
            try {
                Files.deleteIfExists(temporary);
            } catch (IOException ignored) {
                // Preserve the original failure.
            }
            throw failure;
        }
    }

    private static boolean sameBytes(Path file, byte[] expected) throws IOException {
        if (Files.size(file) != expected.length) {
            return false;
        }
        byte[] actual = Files.readAllBytes(file);
        if (actual.length != expected.length) {
            return false;
        }
        int difference = 0;
        for (int i = 0; i < expected.length; i++) {
            difference |= actual[i] ^ expected[i];
        }
        return difference == 0;
    }

    private static void moveAtomically(Path source, Path target) throws IOException {
        Set<StandardCopyOption> options = new HashSet<>();
        options.add(StandardCopyOption.ATOMIC_MOVE);
        options.add(StandardCopyOption.REPLACE_EXISTING);
        try {
            Files.move(source, target, options.toArray(new StandardCopyOption[0]));
        } catch (IOException atomicFailed) {
            try {
                Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException fallbackFailed) {
                fallbackFailed.addSuppressed(atomicFailed);
                throw fallbackFailed;
            }
        }
    }

    private static void setPermissions(Path file, String permissions) {
        try {
            Files.setPosixFilePermissions(file,
                    PosixFilePermissions.fromString(permissions));
        } catch (UnsupportedOperationException | IOException | IllegalArgumentException ignored) {
            // The app owns the extracted rootfs; providers without POSIX mode
            // support still leave the regular file writable by the owner.
        }
    }
}