package gh.nusashell.nusadesk.infrastructure.proot;

import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Guest-side Termux CLI compatibility layer.
 *
 * <p>The guest is a Linux environment, and the widely used way to drive
 * Android from a Linux environment is the <em>client</em> half of Termux:API:
 * the MIT-licensed {@code termux-*} shell commands. Those commands talk to
 * the Termux:API Android app, which only accepts callers that share the
 * Termux signing key and UID, so the app half can never serve this product.
 * The client half, however, is just an interface contract — command name,
 * flags, and a JSON result on stdout — and NusaDesk already owns an
 * authenticated capability bridge that can answer the same questions.</p>
 *
 * <p>This writer therefore installs a small set of {@code termux-*} commands
 * into {@code /usr/local/bin} of the guest. Each one is a generated Python 3
 * script that translates the Termux flags into the fixed allowlist methods of
 * the NusaDesk bridge and prints the answer in the Termux JSON shape. Scripts
 * and tools written against Termux:API keep working; nothing here talks to the
 * Termux app, and the bridge contract (fixed methods, bounded params, typed
 * errors) is unchanged.</p>
 *
 * <p>Deliberate limits, recorded in the generated docs: only the methods the
 * bridge actually answers are installed, so {@code termux-sms-send},
 * {@code termux-call-log} and friends are absent rather than fake. Installed
 * commands are bounded like the bridge: fixed row caps and no side effects.
 * Unsupported Termux flags fail with usage instead of being silently ignored.
 * Exit codes follow the Termux contract: {@code 0} on a result, {@code 1} on a
 * typed bridge error, {@code 2} on usage or transport failure.</p>
 */
public final class GuestTermuxCompatWriter {

    /** Guest-relative bin directory, shared with the NusaDesk CLI. */
    public static final String GUEST_BIN_RELATIVE_PATH =
            GuestAwarenessReadmeWriter.GUEST_BIN_RELATIVE_PATH;
    /** Guest-relative docs directory, shared with the NusaDesk docs. */
    public static final String GUEST_DOCS_RELATIVE_PATH =
            GuestAwarenessReadmeWriter.GUEST_DOCS_RELATIVE_PATH;
    /** Guest-relative documentation page for this compatibility layer. */
    public static final String GUEST_DOC_RELATIVE_PATH = "root/docs/termux-compat.md";

    /** Marker prefix of every file this writer owns in the guest bin dir. */
    public static final String MARKER = "NusaDesk Termux-compat";

    /**
     * Installed command names, in the order they are documented. These are the
     * Termux command names the bridge can actually answer.
     */
    public static final String[] COMMANDS = {
            "termux-battery-status",
            "termux-location",
            "termux-sensor",
            "termux-contact-list",
            "termux-sms-list",
            "termux-telephony-deviceinfo",
            "termux-telephony-cellinfo",
    };

    private GuestTermuxCompatWriter() {
    }

    /** Guest-relative path of one installed command. */
    public static String guestRelativePath(String command) {
        return GUEST_BIN_RELATIVE_PATH + "/" + command;
    }

    /**
     * The exact script content of one command. Public so tests and
     * documentation tooling can pin the generated text.
     *
     * @param command one of {@link #COMMANDS}
     * @param appVersion app version stamped into the script header
     */
    public static String scriptContent(String command, String appVersion) {
        String version = GuestAwarenessReadmeWriter.requireVersionForWriter(appVersion);
        if (!knownCommand(command)) {
            throw new IllegalArgumentException("unknown command: " + command);
        }
        return header(command, version) + body(command);
    }

    /** The exact documentation page content for this layer. */
    public static String docContent(String appVersion) {
        String version = GuestAwarenessReadmeWriter.requireVersionForWriter(appVersion);
        return String.join("\n",
                "# Termux command compatibility",
                "",
                "NusaDesk installs a small set of Termux:API command-line clients into",
                "`/usr/local/bin`. They exist because the Termux:API *app* cannot serve",
                "this product: it only accepts callers that share the Termux signing",
                "key and Android UID, and NusaDesk is a different app. The commands",
                "themselves are a plain interface contract, so NusaDesk answers the",
                "same questions from its own authenticated Android capability bridge.",
                "",
                "Scripts written against these Termux commands keep working without",
                "changes. Nothing here contacts the Termux app, and no Termux app is",
                "required or used.",
                "",
                "## Installed commands",
                "",
                "- `termux-battery-status` - battery snapshot",
                "- `termux-location [-p provider] [-r request]` - one foreground fix",
                "  (`-r last` and `-r updates` answer with the same single fix)",
                "- `termux-sensor [-s SENSOR] [-n COUNT]` - accelerometer or gyroscope",
                "  readings; one JSON document per sample, like Termux's event stream",
                "- `termux-contact-list` - bounded contact rows",
                "- `termux-sms-list [-l LIMIT] [-o OFFSET]` - bounded inbox rows",
                "- `termux-telephony-deviceinfo` - telephony device snapshot",
                "- `termux-telephony-cellinfo` - bounded observed cell rows",
                "",
                "## Output shape",
                "",
                "Output is the Termux JSON shape on stdout: object keys as Termux:API",
                "emits them (for example `percentage`, `latitude`, `values`), enum",
                "values in the Termux spelling (for example `CHARGING`, `PLUGGED_USB`),",
                "and, where Termux has one, a `received` timestamp in the Termux",
                "`yyyy-MM-dd HH:mm:ss` format (`termux-sms-list`). Values are computed",
                "from the bounded bridge reading, so some fields are necessarily",
                "best-effort: `termux-location` reports one foreground fix and omits",
                "fields the bridge did not return; `termux-sensor` is a sequence of",
                "one-shot reads rather than a continuous stream; `termux-sms-list`",
                "carries the bridge's bounded message preview as `body`.",
                "",
                "Per-command field sets (the bridge exposes no more than this):",
                "",
                "- `termux-battery-status`: `health`, `percentage`, `plugged`, `status`,",
                "  `temperature` (C), `current` (uA), `voltage` (mV)",
                "- `termux-location`: `latitude`, `longitude`, `accuracy`, `provider`,",
                "  plus `altitude`, `bearing`, `speed` when the fix carries them",
                "- `termux-sensor`: one document per sample, `{SENSOR: {values: [x,y,z]}}`",
                "- `termux-contact-list`: `name`, `number` (one row per number)",
                "- `termux-sms-list`: `type`, `read`, `address`, `number`, `body`,",
                "  `received`",
                "- `termux-telephony-deviceinfo`: `phone_type`, `sim_state`,",
                "  `network_type` (a subset of Termux's device dump)",
                "- `termux-telephony-cellinfo`: `type`, `dbm`, `level` per observed cell",
                "  (Termux's identity fields are not exposed by the bridge)",
                "",
                "Row caps are lower than Termux's defaults: `termux-sms-list` and",
                "`termux-telephony-cellinfo` see at most 50 and 10 rows respectively",
                "from the bounded bridge reading, so `-o` pages only within that",
                "window. `termux-contact-list` expands one bridge row per number, so",
                "it can print up to five entries for each of the bridge's 50 contact",
                "rows. When the bridge itself hit its cap the row commands say so on",
                "stderr; the exit code stays `0` because the rows that *were*",
                "returned are valid.",
                "",
                "`termux-sensor` supports only `-s accelerometer|gyroscope` and",
                "`-n 1..10`; Termux's `-l`, `-a`, `-c`, `-d` and comma-separated",
                "sensor lists are not implemented and fail with usage.",
                "",
                "## Exit codes",
                "",
                "- `0` - a result was printed",
                "- `1` - the bridge returned a typed error (printed to stderr)",
                "- `2` - usage error, an unparseable bridge payload, or the bridge",
                "  was unreachable",
                "",
                "## Not installed",
                "",
                "Only methods this bridge answers are installed. Commands that need",
                "another Termux app, a side effect the bridge does not expose, or an",
                "Android capability outside the current allowlist are deliberately",
                "absent: `termux-sms-send`, `termux-call-log`, `termux-camera-photo`,",
                "`termux-microphone-record`, `termux-clipboard-*`, `termux-notification`,",
                "`termux-toast`, `termux-tts-speak`, `termux-vibrate`, `termux-torch`,",
                "`termux-wifi-*`, `termux-keystore`, `termux-usb`, `termux-share`,",
                "`termux-dialog`, `termux-fingerprint`, `termux-infrared-*`,",
                "`termux-media-player`, `termux-media-scan`, `termux-storage-get`,",
                "`termux-job-scheduler`, `termux-brightness`, `termux-volume`,",
                "`termux-wallpaper`, `termux-audio-info`, `termux-speech-to-text`,",
                "`termux-download`, `termux-nfc`, `termux-tts-engines`, and",
                "`termux-sms-inbox` (upstream already replaced it with `termux-sms-list`).",
                "Camera and microphone are served by the live media session instead:",
                "see [media.md](media.md).",
                "",
                "## Bridge session",
                "",
                "The commands read the same session file as `nusadesk-android`",
                "(`/run/nusadesk/android-bridge.env`) and speak the same loopback",
                "protocol, so they are only usable inside a live NusaDesk session.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    private static boolean knownCommand(String command) {
        return new LinkedHashSet<>(Arrays.asList(COMMANDS)).contains(command);
    }

    private static String generatedFooter(String version) {
        return "> Docs generated by the NusaDesk Android app (version " + version
                + "). Manual edits may be overwritten on the next session start.";
    }

    private static String header(String command, String version) {
        return String.join("\n",
                "#!/usr/bin/env python3",
                "# " + MARKER + " client: " + command,
                "# Generated by the NusaDesk Android app; do not edit.",
                "# App version: " + version,
                "# Speaks only the fixed NusaDesk bridge allowlist. It never contacts",
                "# the Termux app, never runs a shell, and never prints the token.",
                "",
                "import datetime",
                "import json",
                "import secrets",
                "import socket",
                "import sys",
                "",
                "ENV_FILE = '/run/nusadesk/android-bridge.env'",
                "SOCKET_TIMEOUT_SECONDS = 15.0",
                "MAX_CONFIG_LINE_BYTES = 1024",
                "MAX_RESPONSE_BYTES = 16384",
                "PROTOCOL_VERSION = 1",
                "ENV_ADDRESS = 'NUSADESK_ANDROID_BRIDGE_ADDRESS'",
                "ENV_PORT = 'NUSADESK_ANDROID_BRIDGE_PORT'",
                "ENV_TOKEN = 'NUSADESK_ANDROID_BRIDGE_TOKEN'",
                "ENV_PROTOCOL = 'NUSADESK_ANDROID_BRIDGE_PROTOCOL'",
                "TOKEN_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-'",
                "",
                "",
                "class CliError(Exception):",
                "    pass",
                "",
                "",
                "class BridgeError(Exception):",
                "    pass",
                "",
                "",
                "def load_config(path):",
                "    values = {}",
                "    try:",
                "        with open(path, 'r', encoding='ascii') as handle:",
                "            for raw in handle:",
                "                if len(raw) > MAX_CONFIG_LINE_BYTES:",
                "                    raise CliError('session env line too long')",
                "                line = raw.strip()",
                "                if not line or line.startswith('#'):",
                "                    continue",
                "                if '=' not in line:",
                "                    raise CliError('malformed session env line')",
                "                key, _, value = line.partition('=')",
                "                key = key.strip()",
                "                value = value.strip()",
                "                if key not in (ENV_ADDRESS, ENV_PORT, ENV_TOKEN,",
                "                                ENV_PROTOCOL):",
                "                    raise CliError('unexpected session env key')",
                "                if key in values:",
                "                    raise CliError('duplicate session env key')",
                "                values[key] = value",
                "    except (IOError, UnicodeDecodeError, CliError) as error:",
                "        if isinstance(error, CliError):",
                "            raise",
                "        raise CliError('cannot read session env')",
                "    address = values.get(ENV_ADDRESS)",
                "    port_text = values.get(ENV_PORT)",
                "    token = values.get(ENV_TOKEN)",
                "    protocol = values.get(ENV_PROTOCOL)",
                "    if address != '127.0.0.1':",
                "        raise CliError('bridge address must be loopback only')",
                "    if protocol != str(PROTOCOL_VERSION):",
                "        raise CliError('unsupported bridge protocol version')",
                "    try:",
                "        port = int(port_text, 10)",
                "    except (TypeError, ValueError):",
                "        raise CliError('invalid session env port')",
                "    if port < 1 or port > 65535:",
                "        raise CliError('invalid session env port')",
                "    if token is None or len(token) < 16 or len(token) > 256:",
                "        raise CliError('invalid session env token')",
                "    if any(ch not in TOKEN_ALPHABET for ch in token):",
                "        raise CliError('invalid session env token')",
                "    return address, port, token",
                "",
                "",
                "def call(method):",
                "    address, port, token = load_config(ENV_FILE)",
                "    request = {",
                "        'v': PROTOCOL_VERSION,",
                "        'id': secrets.token_urlsafe(8),",
                "        'token': token,",
                "        'method': method,",
                "    }",
                "    payload = json.dumps(request, separators=(',', ':'),",
                "                          ensure_ascii=True)",
                "    with socket.create_connection((address, port),",
                "                                  timeout=SOCKET_TIMEOUT_SECONDS) as sock:",
                "        sock.settimeout(SOCKET_TIMEOUT_SECONDS)",
                "        sock.sendall(payload.encode('ascii') + bytes([10]))",
                "        outgoing = bytearray()",
                "        while True:",
                "            chunk = sock.recv(4096)",
                "            if not chunk:",
                "                break",
                "            outgoing.extend(chunk)",
                "            if 10 in outgoing:",
                "                break",
                "            if len(outgoing) > MAX_RESPONSE_BYTES:",
                "                raise CliError('response too large')",
                "    if not outgoing:",
                "        raise CliError('empty bridge response')",
                "    line = outgoing.split(bytes([10]), 1)[0]",
                "    if len(line) > MAX_RESPONSE_BYTES:",
                "        raise CliError('response too large')",
                "    try:",
                "        parsed = json.loads(line.decode('utf-8'))",
                "    except ValueError:",
                "        raise CliError('bridge response is not JSON')",
                "    if not isinstance(parsed, dict):",
                "        raise CliError('bridge response is not a JSON object')",
                "    if parsed.get('v') != PROTOCOL_VERSION:",
                "        raise CliError('unsupported bridge response version')",
                "    if not parsed.get('ok'):",
                "        raise BridgeError(str(parsed.get('error', 'bridge error')))",
                "    return parsed",
                "",
                "",
                "def emit(value):",
                "    print(json.dumps(value, separators=(',', ':'), ensure_ascii=True))",
                "    return 0",
                "",
                "",
                "def warn_truncated(reading):",
                "    if reading.get('truncated') is True:",
                "        print('" + command + ": bridge row cap reached;'",
                "              ' results are truncated', file=sys.stderr)",
                "",
                "",
                "def run(main):",
                "    try:",
                "        return main(sys.argv[1:])",
                "    except CliError as error:",
                "        print('" + command + ": ' + str(error), file=sys.stderr)",
                "        return 2",
                "    except BridgeError as error:",
                "        print('" + command + ": ' + str(error), file=sys.stderr)",
                "        return 1",
                "    except (ValueError, TypeError, KeyError):",
                "        # A malformed bridge payload is a protocol fault, not a typed",
                "        # capability error: fail with the usage/transport exit code.",
                "        print('" + command + ": malformed bridge response',",
                "              file=sys.stderr)",
                "        return 2",
                "    except OSError:",
                "        print('" + command + ": bridge socket connection failed',",
                "              file=sys.stderr)",
                "        return 2",
                "",
                "");
    }

    private static String body(String command) {
        switch (command) {
            case "termux-battery-status":
                return String.join("\n",
                        "",
                        "PLUGGED = {'none': 'UNPLUGGED', 'ac': 'PLUGGED_AC',",
                        "           'usb': 'PLUGGED_USB', 'wireless': 'PLUGGED_WIRELESS',",
                        "           'dock': 'PLUGGED_DOCK'}",
                        "",
                        "",
                        "def enum_name(value):",
                        "    return str(value).upper().replace('-', '_')",
                        "",
                        "",
                        "def to_termux(reading):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    plugged = str(reading.get('plugged', 'none'))",
                        "    return {",
                        "        'health': enum_name(reading.get('health', 'unknown')),",
                        "        'percentage': int(reading.get('capacity_percent', 0)),",
                        "        'plugged': PLUGGED.get(plugged,",
                        "                               'PLUGGED_' + enum_name(plugged)),",
                        "        'status': enum_name(reading.get('status', 'unknown')),",
                        "        'temperature': round(float(",
                        "            reading.get('temperature_deci_celsius', 0)) / 10.0, 1),",
                        "        'current': int(reading.get('current_microamps', 0)),",
                        "        'voltage': int(reading.get('voltage_microvolts', 0)) // 1000,",
                        "    }",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise CliError('usage: termux-battery-status')",
                        "    return emit(to_termux(call('battery.status')))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-location":
                return String.join("\n",
                        "",
                        "def parse(argv):",
                        "    provider = 'gps'",
                        "    request = 'once'",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag not in ('-p', '-r') or index + 1 >= len(argv):",
                        "            raise CliError('usage: termux-location [-p provider] [-r request]')",
                        "        value = argv[index + 1]",
                        "        if flag == '-p':",
                        "            if value not in ('gps', 'network', 'passive'):",
                        "                raise CliError('unsupported provider: ' + value)",
                        "            provider = value",
                        "        else:",
                        "            if value not in ('once', 'last', 'updates'):",
                        "                raise CliError('unsupported request: ' + value)",
                        "            request = value",
                        "        index += 2",
                        "    return provider, request",
                        "",
                        "",
                        "def to_termux(reading, provider):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    result = {",
                        "        'latitude': reading.get('latitude'),",
                        "        'longitude': reading.get('longitude'),",
                        "        'accuracy': reading.get('accuracy_meters'),",
                        "        'provider': reading.get('provider', provider),",
                        "    }",
                        "    for key, source in (('altitude', 'altitude_meters'),",
                        "                        ('bearing', 'bearing_degrees'),",
                        "                        ('speed', 'speed_meters_per_second')):",
                        "        value = reading.get(source)",
                        "        if value is not None:",
                        "            result[key] = value",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    provider, request = parse(argv)",
                        "    if request == 'updates':",
                        "        print('termux-location: updates stream is not available;'",
                        "              ' returning one fix', file=sys.stderr)",
                        "    return emit(to_termux(call('location.get'), provider))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-sensor":
                return String.join("\n",
                        "",
                        "SENSORS = {'accelerometer': 'sensor.accelerometer',",
                        "           'gyroscope': 'sensor.gyroscope'}",
                        "DEFAULT_NAME = {'accelerometer': 'ACCELEROMETER',",
                        "                'gyroscope': 'GYROSCOPE'}",
                        "MAX_SAMPLES = 10",
                        "",
                        "",
                        "def parse(argv):",
                        "    name = 'accelerometer'",
                        "    count = 1",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag not in ('-s', '-n') or index + 1 >= len(argv):",
                        "            raise CliError('usage: termux-sensor [-s SENSOR] [-n COUNT]')",
                        "        value = argv[index + 1]",
                        "        if flag == '-s':",
                        "            lowered = value.lower()",
                        "            if lowered not in SENSORS:",
                        "                raise CliError('unsupported sensor: ' + value)",
                        "            name = lowered",
                        "        else:",
                        "            if not value.isdigit():",
                        "                raise CliError('count must be a positive number')",
                        "            count = int(value, 10)",
                        "            if count < 1:",
                        "                raise CliError('count must be a positive number')",
                        "            if count > MAX_SAMPLES:",
                        "                raise CliError('count above the bridge cap of '",
                        "                               + str(MAX_SAMPLES))",
                        "        index += 2",
                        "    return name, count",
                        "",
                        "",
                        "def main(argv):",
                        "    name, count = parse(argv)",
                        "    method = SENSORS[name]",
                        "    documents = []",
                        "    for _ in range(count):",
                        "        reading = call(method)",
                        "        if reading.get('available') is not True:",
                        "            raise BridgeError('sensor unavailable')",
                        "        documents.append({DEFAULT_NAME[name]: {'values': [",
                        "            float(reading.get('x', 0.0)),",
                        "            float(reading.get('y', 0.0)),",
                        "            float(reading.get('z', 0.0))]}})",
                        "    # Print only after every sample succeeded, so a mid-sequence",
                        "    # failure never leaves partial JSON on stdout followed by an",
                        "    # error exit.",
                        "    for document in documents:",
                        "        print(json.dumps(document, separators=(',', ':'),",
                        "                         ensure_ascii=True))",
                        "    return 0",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-contact-list":
                return String.join("\n",
                        "",
                        "def to_termux(reading):",
                        "    warn_truncated(reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        name = row.get('name') or ''",
                        "        primary = row.get('number_1')",
                        "        if primary:",
                        "            result.append({'name': name, 'number': primary})",
                        "        for index in range(2, 6):",
                        "            extra = row.get('number_' + str(index))",
                        "            if extra:",
                        "                result.append({'name': name, 'number': extra})",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise CliError('usage: termux-contact-list')",
                        "    return emit(to_termux(call('contacts.list')))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-sms-list":
                return String.join("\n",
                        "",
                        "MAX_ROWS = 50",
                        "",
                        "",
                        "def parse(argv):",
                        "    limit = None",
                        "    offset = None",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag not in ('-l', '-o') or index + 1 >= len(argv):",
                        "            raise CliError('usage: termux-sms-list [-l LIMIT] [-o OFFSET]')",
                        "        value = argv[index + 1]",
                        "        if not value.isdigit():",
                        "            raise CliError('limit and offset must be non-negative numbers')",
                        "        if flag == '-l':",
                        "            limit = int(value, 10)",
                        "        else:",
                        "            offset = int(value, 10)",
                        "        index += 2",
                        "    return limit, offset",
                        "",
                        "",
                        "def to_termux(reading, limit, offset):",
                        "    warn_truncated(reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    if offset is not None:",
                        "        rows = rows[offset:]",
                        "    if limit is not None:",
                        "        rows = rows[:limit]",
                        "    else:",
                        "        rows = rows[:MAX_ROWS]",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        entry = {",
                        "            'type': 'inbox',",
                        "            'read': row.get('read') is True,",
                        "            'address': row.get('address', ''),",
                        "            'number': row.get('address', ''),",
                        "            'body': row.get('snippet', ''),",
                        "        }",
                        "        received_ms = row.get('timestamp_utc_ms')",
                        "        if isinstance(received_ms, int) and received_ms > 0:",
                        "            entry['received'] = datetime.datetime.fromtimestamp(",
                        "                received_ms / 1000).strftime('%Y-%m-%d %H:%M:%S')",
                        "        result.append(entry)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    limit, offset = parse(argv)",
                        "    reading = call('sms.inbox')",
                        "    return emit(to_termux(reading, limit, offset))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-telephony-deviceinfo":
                return String.join("\n",
                        "",
                        "def to_termux(reading):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    result = {}",
                        "    phone_type = reading.get('phone_type')",
                        "    if phone_type:",
                        "        result['phone_type'] = str(phone_type)",
                        "    sim_state = reading.get('sim_state')",
                        "    if sim_state:",
                        "        result['sim_state'] = str(sim_state)",
                        "    network_type = reading.get('network_type')",
                        "    if network_type:",
                        "        result['network_type'] = str(network_type)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise CliError('usage: termux-telephony-deviceinfo')",
                        "    return emit(to_termux(call('telephony.info')))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            case "termux-telephony-cellinfo":
                return String.join("\n",
                        "",
                        "def to_termux(reading):",
                        "    warn_truncated(reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        entry = {'type': str(row.get('technology', '')).lower()}",
                        "        if 'signal_dbm' in row:",
                        "            entry['dbm'] = int(row['signal_dbm'])",
                        "        if 'signal_level' in row:",
                        "            entry['level'] = int(row['signal_level'])",
                        "        result.append(entry)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise CliError('usage: termux-telephony-cellinfo')",
                        "    return emit(to_termux(call('telephony.cellinfo')))",
                        "",
                        "",
                        "if __name__ == '__main__':",
                        "    sys.exit(run(main))",
                        "");
            default:
                throw new IllegalArgumentException("unknown command: " + command);
        }
    }
}
