package gh.nusashell.nusadesk.infrastructure.proot;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.HashSet;
import java.util.Set;

/**
 * Writes the product-owned, app-managed awareness bundle in the guest root.
 *
 * <p>The bundle is written when the guest session starts:
 * <ul>
 *   <li>{@code /root/README.md} — concise product overview with relative
 *       links into {@code docs/};</li>
 *   <li>{@code /root/docs/README.md} and the focused topic docs
 *       ({@code bridge.md}, {@code media.md},
 *       {@code battery-sensors-location.md}, {@code messaging-telephony.md})
 *       documenting the live loopback services, including the live-only
 *       camera + microphone media contract;</li>
 *   <li>{@code /usr/local/bin/nusadesk-android} — an executable Python 3 CLI
 *       that controls {@code media.start} / {@code media.status} /
 *       {@code media.stop} and {@code bridge.info} over the authenticated
 *       loopback JSONL bridge.</li>
 * </ul>
 * Every file is intentional: generated by the Android host rather than
 * shipped as a mutable rootfs asset, carrying the APK version so an app
 * update replaces stale text on the next session start. The targets stay
 * normal writable guest files; this class does not bind them read-only or
 * make them immutable.</p>
 *
 * <p>Only fixed, app-managed paths are ever written and the parents must be
 * real directories: a symlink in {@code root}, {@code root/docs}, or
 * {@code usr/local/bin} fails closed with an {@link IOException} and nothing
 * is written outside the rootfs. A user-supplied destination path is never
 * accepted.</p>
 */
public final class GuestAwarenessReadmeWriter {

    /** Guest-relative path owned by NusaDesk. */
    public static final String GUEST_RELATIVE_PATH = "root/README.md";
    /** Guest-relative docs directory owned by NusaDesk. */
    public static final String GUEST_DOCS_RELATIVE_PATH = "root/docs";
    /** Guest-relative bin directory that receives the CLI. */
    public static final String GUEST_BIN_RELATIVE_PATH = "usr/local/bin";
    /** Guest-relative CLI path, executable on PATH. */
    public static final String GUEST_CLI_RELATIVE_PATH = "usr/local/bin/nusadesk-android";
    /** CLI file name inside the fixed bin parent. */
    public static final String CLI_FILE_NAME = "nusadesk-android";
    /** Guest session configuration pinned by the bridge. */
    public static final String GUEST_ENV_FILE_PATH = "/run/nusadesk/android-bridge.env";

    private static final String TEMP_PREFIX = ".nusadesk-";
    private static final String TEMP_SUFFIX = ".tmp";
    private static final String README_PERMISSIONS = "rw-r--r--";
    private static final String CLI_PERMISSIONS = "rwxr-xr-x";

    /** Outcome of an idempotent ensure operation. */
    public enum Result {
        UNCHANGED,
        UPDATED
    }

    private GuestAwarenessReadmeWriter() {
    }

    /**
     * Ensure the whole awareness bundle (README, docs index and topic docs,
     * and the executable CLI) matches the current app version.
     *
     * @param activeRootfs validated active rootfs directory
     * @param appVersion APK version name, not user input
     * @return whether any file was updated or everything was already current
     * @throws IOException when a fixed path is unsafe or cannot be written
     */
    public static Result ensure(Path activeRootfs, String appVersion) throws IOException {
        if (activeRootfs == null) {
            throw new IllegalArgumentException("activeRootfs must not be null");
        }
        String version = requireVersion(appVersion);
        Path root = prepareDirectory(activeRootfs, "root", "guest /root");
        Path docs = prepareDirectory(root, "docs", "guest /root/docs");
        Path bin = prepareDirectory(activeRootfs, "usr/local/bin", "guest /usr/local/bin");

        boolean updated = false;
        updated |= ensureFile(root.resolve("README.md"),
                content(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("README.md"),
                docsIndexContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("bridge.md"),
                bridgeDocContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("media.md"),
                mediaDocContent(version).getBytes(StandardCharsets.UTF_8), README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("battery-sensors-location.md"),
                batterySensorsLocationDocContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= ensureFile(docs.resolve("messaging-telephony.md"),
                messagingTelephonyDocContent(version).getBytes(StandardCharsets.UTF_8),
                README_PERMISSIONS);
        updated |= ensureFile(bin.resolve(CLI_FILE_NAME),
                cliContent(version).getBytes(StandardCharsets.UTF_8), CLI_PERMISSIONS);
        return updated ? Result.UPDATED : Result.UNCHANGED;
    }

    /** Canonical README text, public for focused tests and documentation tooling. */
    public static String content(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# NusaDesk Linux",
                "",
                "NusaDesk provides:",
                "- Ubuntu Base ARM64 Linux guest through PRoot",
                "- Local guest terminal at 127.0.0.1:22022",
                "- Product-owned systemctl3 service bridge",
                "- Bounded `udocker compose` support",
                "- Best-effort Android battery bridge at `/sys/class/power_supply/battery`",
                "- Optional Android workspace at `~/nusadesk`",
                "- Android-owned lifecycle, DNS doctor, and session-temporary `/tmp`",
                "",
                "## Documentation",
                "",
                "Guest-facing documentation is generated and owned by the app:",
                "",
                "- [Guest documentation index](docs/README.md)",
                "- [Android capability bridge](docs/bridge.md)",
                "- [Live media (camera + microphone)](docs/media.md)",
                "- [Battery, sensors, and location](docs/battery-sensors-location.md)",
                "- [Messaging and telephony](docs/messaging-telephony.md)",
                "",
                "> This file is managed by the NusaDesk Android app. It is writable in",
                "> the guest and may be regenerated after an app update.",
                "> App version: " + version,
                "",
                "This is a PRoot guest, not a VM or full Docker environment.",
                "",
                "") + "\n";
    }

    /** Canonical docs index text. */
    public static String docsIndexContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# NusaDesk Guest Documentation",
                "",
                "This directory is generated and owned by the NusaDesk Android app.",
                "Manual edits may be overwritten on the next session start.",
                "",
                "## Topics",
                "",
                "- [Android capability bridge](bridge.md)",
                "- [Live media (camera + microphone)](media.md)",
                "- [Battery, sensors, and location](battery-sensors-location.md)",
                "- [Messaging and telephony](messaging-telephony.md)",
                "",
                "## Command-line tool",
                "",
                "`nusadesk-android` is installed at `/usr/local/bin/nusadesk-android`:",
                "",
                "- `nusadesk-android media start|status|stop` - live media session",
                "- `nusadesk-android bridge info` - bridge discovery",
                "",
                "See [media.md](media.md) for the live stream contract and",
                "[bridge.md](bridge.md) for the transport and protocol.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical bridge transport and protocol doc. */
    public static String bridgeDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Android capability bridge",
                "",
                "NusaDesk exposes a small, authenticated capability bridge to the",
                "guest for the active PRoot session. It is loopback-only, never bound",
                "to the LAN, and dispatches only fixed method names; it is not a shell",
                "and no method takes request parameters.",
                "",
                "## Session configuration",
                "",
                "The address, port, protocol version, and session token are owned by",
                "the app and pinned in `/run/nusadesk/android-bridge.env`:",
                "",
                "- `NUSADESK_ANDROID_BRIDGE_ADDRESS=127.0.0.1`",
                "- `NUSADESK_ANDROID_BRIDGE_PORT=<ephemeral port>`",
                "- `NUSADESK_ANDROID_BRIDGE_TOKEN=<session token>`",
                "- `NUSADESK_ANDROID_BRIDGE_PROTOCOL=1`",
                "",
                "The token authenticates every request because loopback is only a",
                "reachability boundary, not an identity boundary. The token is never",
                "printed by `nusadesk-android`.",
                "",
                "## Protocol",
                "",
                "One connection carries exactly one newline-delimited JSON request and",
                "receives one JSON response on the same connection. The envelope is a",
                "flat object with no params:",
                "",
                "- `v` - fixed protocol version (`1`)",
                "- `id` - bounded, unique per invocation",
                "- `token` - the session token",
                "- `method` - one fixed allowlist method",
                "",
                "Responses are one flat JSON line: success carries `ok` = `true` plus",
                "method fields; failure carries `ok` = `false` plus a typed `error`.",
                "Frames are bounded (16 KiB), and the bridge applies a socket timeout",
                "and a bounded concurrency cap per session.",
                "",
                "## Methods",
                "",
                "- `bridge.info` - transport and capability list",
                "- `battery.status` - Android battery snapshot",
                "- `sensor.accelerometer`, `sensor.gyroscope` - one-shot reads",
                "- `location.get` - one foreground one-shot fix",
                "- `location.stream.start`, `location.stream.poll`,",
                "  `location.stream.stop` - one foreground pull stream",
                "- `contacts.list`, `calllog.list`, `sms.inbox`, `telephony.info`,",
                "  `telephony.cellinfo` - read-only, bounded row reads",
                "- `media.start`, `media.status`, `media.stop` - live media session",
                "",
                "## Client",
                "",
                "`nusadesk-android` wraps the envelope with a fixed allowlist:",
                "",
                "- `nusadesk-android bridge info` - discovery",
                "- `nusadesk-android media start|status|stop` - live media control",
                "",
                "There is no `nusadesk-android call <method>`. The CLI never forwards",
                "a user-supplied method name; the allowlist above is all it can issue.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical live media contract doc. */
    public static String mediaDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Live media (camera + microphone)",
                "",
                "Live media is the guest camera + microphone session. Android captures",
                "with Camera2 and AudioRecord, encodes H.264 video and AAC-LC audio",
                "with hardware encoders, and serves one loopback-only RTSP-over-TCP",
                "stream. The session is live-only: NusaDesk never writes a capture",
                "file, never persists recorded media, and exposes no artifact path.",
                "Save a file yourself from the stream if you need one.",
                "",
                "## Lifetime",
                "",
                "The stream lives only while both of these hold:",
                "",
                "- the guest bridge session for this app is live, and",
                "- the user-visible camera + microphone foreground media service runs.",
                "",
                "`media stop` stops the service; closing the bridge session also",
                "tears the stream down. Nothing is stored for resuming later.",
                "",
                "## Commands",
                "",
                "- `nusadesk-android media start` - start a new session; on success",
                "  the JSON response reports `state` = `running` and the `rtsp_url`",
                "- `nusadesk-android media status` - always ok; reports the explicit",
                "  `state` (`stopped`, `starting`, `running`, `failed`)",
                "- `nusadesk-android media stop` - idempotent; always reports",
                "  `state` = `stopped`",
                "",
                "## States",
                "",
                "| state | meaning |",
                "| --- | --- |",
                "| `stopped` | no live session |",
                "| `starting` | start accepted, pipeline coming up |",
                "| `running` | RTSP listening on loopback, encoders producing |",
                "| `failed` | session failed with a typed `error` |",
                "",
                "## Running response",
                "",
                "In the running state the response carries flat fields:",
                "",
                "- `state` = `running`",
                "- `rtsp_url` = `rtsp://127.0.0.1:<port>/`",
                "- `video_codec` = `h264`",
                "- `audio_codec` = `aac`",
                "- `video_width` / `video_height` = encoder metadata",
                "  (target at most 1280 x 720)",
                "- `video_fps` = 30",
                "- `client_limit` = 2",
                "",
                "The stream binds only to `127.0.0.1` and serves RTSP over TCP with",
                "a bounded client cap (`client_limit`). It is never exposed on the",
                "LAN.",
                "",
                "## Consuming the stream",
                "",
                "Use the `rtsp_url` from `media start` or from a running",
                "`media status`:",
                "",
                "```sh",
                "ffplay -rtsp_transport tcp 'rtsp://127.0.0.1:<port>/'",
                "ffmpeg -rtsp_transport tcp -i 'rtsp://127.0.0.1:<port>/' -c copy out.mp4",
                "```",
                "",
                "OpenCV (C++ or Python) can open the same URL with the TCP transport.",
                "Saving is manual; NusaDesk does not persist the stream.",
                "",
                "## Permissions and foreground",
                "",
                "The bridge never opens a camera or microphone permission prompt.",
                "A missing, denied, or partial grant is a typed `media-*` error, never",
                "a prompt. Capture is user-visible foreground work; starting it from",
                "the background returns the foreground error below.",
                "",
                "## Typed errors",
                "",
                "| error | meaning |",
                "| --- | --- |",
                "| `media-permission-required` | camera/mic grant missing, no denial on record |",
                "| `media-permission-denied` | camera/mic grant was denied |",
                "| `media-foreground-required` | app not eligible to start the camera/mic foreground service |",
                "| `media-unavailable` | platform cannot serve the stream |",
                "| `media-busy` | a start is already in flight or the camera is in use |",
                "| `media-encoder-unavailable` | a hardware encoder or codec metadata is not ready |",
                "| `media-start-failed` | start did not complete within its bound |",
                "",
                "## Retired artifact commands",
                "",
                "`camera.snapshot` and `mic.record` are retired. They are not exposed",
                "by this bridge, their artifact paths no longer exist, and no guest",
                "capture file is produced anywhere. The live-only session above is",
                "the camera + microphone surface.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical battery, sensors, and location doc. */
    public static String batterySensorsLocationDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Battery, sensors, and location",
                "",
                "## Battery",
                "",
                "- `battery.status` - one Android BatteryManager snapshot",
                "- `/sys/class/power_supply/battery` - a best-effort app-owned",
                "  projection refreshed every two seconds while the session is live.",
                "  It is not real kernel sysfs; treat it as an app snapshot and let",
                "  the app own it.",
                "",
                "## Sensors",
                "",
                "- `sensor.accelerometer` - one-shot accelerometer reading",
                "- `sensor.gyroscope` - one-shot gyroscope reading",
                "",
                "Unavailable and timeout states are typed errors.",
                "",
                "## Location",
                "",
                "- `location.get` - one foreground one-shot fix",
                "- `location.stream.start` - start one foreground pull stream at a",
                "  fixed 5 second interval",
                "- `location.stream.poll` - read the next fix with a bounded wait",
                "- `location.stream.stop` - idempotent stop",
                "",
                "Location is foreground-only and pull-based and lives only while the",
                "bridge session is live. The bridge never opens a background location",
                "and never surfaces an automatic permission prompt.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /** Canonical messaging and telephony doc. */
    public static String messagingTelephonyDocContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "# Messaging and telephony",
                "",
                "Read-only, bounded guest surfaces:",
                "",
                "- `contacts.list` - contacts snapshot",
                "- `calllog.list` - call log snapshot",
                "- `sms.inbox` - SMS inbox snapshot",
                "- `telephony.info` - device telephony information",
                "- `telephony.cellinfo` - serving cell information",
                "",
                "All reads use fixed defaults and return bounded rows. The response",
                "reports `count`, and rows dropped by the byte bound set",
                "`truncated` = `true`. Permission, denial, unavailability, and",
                "no-telephony states are typed errors.",
                "",
                "Side-effecting operations are deliberately not offered:",
                "`sms.send` and `phone.call` are never dispatched and answer with a",
                "typed unsupported result.",
                "",
                generatedFooter(version),
                "",
                "") + "\n";
    }

    /**
     * Canonical executable Python 3 CLI content. The script ships with
     * executable bits set by the writer; it is deliberately small and
     * bounded: fixed allowlist commands only, no shell execution, no user
     * method passthrough, and the session token is never printed.
     */
    public static String cliContent(String appVersion) {
        String version = requireVersion(appVersion);
        return String.join("\n",
                "#!/usr/bin/env python3",
                "# NusaDesk Android bridge CLI - generated by the NusaDesk Android app.",
                "# App version: " + version,
                "# Fixed session env: " + GUEST_ENV_FILE_PATH,
                "# This tool issues only the fixed allowlisted methods below. It never",
                "# runs a shell, never takes a user-supplied method name, and never",
                "# prints the session token.",
                "",
                "import json",
                "import secrets",
                "import socket",
                "import sys",
                "",
                "ENV_FILE = '" + GUEST_ENV_FILE_PATH + "'",
                "SOCKET_TIMEOUT_SECONDS = 15.0",
                "MAX_CONFIG_LINE_BYTES = 1024",
                "MAX_RESPONSE_BYTES = 16384",
                "PROTOCOL_VERSION = 1",
                "ENV_ADDRESS = 'NUSADESK_ANDROID_BRIDGE_ADDRESS'",
                "ENV_PORT = 'NUSADESK_ANDROID_BRIDGE_PORT'",
                "ENV_TOKEN = 'NUSADESK_ANDROID_BRIDGE_TOKEN'",
                "ENV_PROTOCOL = 'NUSADESK_ANDROID_BRIDGE_PROTOCOL'",
                "TOKEN_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-'",
                "USAGE = 'usage: nusadesk-android media start|status|stop | bridge info'",
                "",
                "# Fixed allowlist only; there is deliberately no generic call",
                "# passthrough and no arbitrary method command.",
                "COMMANDS = {",
                "    'media start': 'media.start',",
                "    'media status': 'media.status',",
                "    'media stop': 'media.stop',",
                "    'bridge info': 'bridge.info',",
                "}",
                "",
                "",
                "class CliError(Exception):",
                "    pass",
                "",
                "",
                "def parse_args(argv):",
                "    if len(argv) != 2:",
                "        raise CliError(USAGE)",
                "    method = COMMANDS.get(argv[0] + ' ' + argv[1])",
                "    if method is None:",
                "        raise CliError(USAGE)",
                "    return method",
                "",
                "",
                "def load_config(path):",
                "    values = {}",
                "    try:",
                "        with open(path, 'r', encoding='ascii') as handle:",
                "            for raw in handle:",
                "                if len(raw) > MAX_CONFIG_LINE_BYTES:",
                "                    raise CliError('session env line too long')",
                "                line = raw.strip()",
                "                if not line or line.startswith('#'):",
                "                    continue",
                "                if '=' not in line:",
                "                    raise CliError('malformed session env line')",
                "                key, _, value = line.partition('=')",
                "                key = key.strip()",
                "                value = value.strip()",
                "                if key not in (ENV_ADDRESS, ENV_PORT, ENV_TOKEN,",
                "                                ENV_PROTOCOL):",
                "                    raise CliError('unexpected session env key')",
                "                if key in values:",
                "                    raise CliError('duplicate session env key')",
                "                values[key] = value",
                "    except (IOError, UnicodeDecodeError, CliError) as error:",
                "        if isinstance(error, CliError):",
                "            raise",
                "        raise CliError('cannot read session env')",
                "    address = values.get(ENV_ADDRESS)",
                "    port_text = values.get(ENV_PORT)",
                "    token = values.get(ENV_TOKEN)",
                "    protocol = values.get(ENV_PROTOCOL)",
                "    if address != '127.0.0.1':",
                "        raise CliError('bridge address must be loopback only')",
                "    if protocol != str(PROTOCOL_VERSION):",
                "        raise CliError('unsupported bridge protocol version')",
                "    try:",
                "        port = int(port_text, 10)",
                "    except (TypeError, ValueError):",
                "        raise CliError('invalid session env port')",
                "    if port < 1 or port > 65535:",
                "        raise CliError('invalid session env port')",
                "    if token is None or len(token) < 16 or len(token) > 256:",
                "        raise CliError('invalid session env token')",
                "    if any(ch not in TOKEN_ALPHABET for ch in token):",
                "        raise CliError('invalid session env token')",
                "    return address, port, token",
                "",
                "",
                "def build_request(method, token):",
                "    request = {",
                "        'v': PROTOCOL_VERSION,",
                "        'id': secrets.token_urlsafe(8),",
                "        'token': token,",
                "        'method': method,",
                "    }",
                "    return json.dumps(request, separators=(',', ':'),",
                "                      ensure_ascii=True)",
                "",
                "",
                "def call(address, port, token, method):",
                "    payload = build_request(method, token)",
                "    with socket.create_connection((address, port),",
                "                                  timeout=SOCKET_TIMEOUT_SECONDS) as sock:",
                "        sock.settimeout(SOCKET_TIMEOUT_SECONDS)",
                "        sock.sendall(payload.encode('ascii') + bytes([10]))",
                "        outgoing = bytearray()",
                "        while True:",
                "            chunk = sock.recv(4096)",
                "            if not chunk:",
                "                break",
                "            outgoing.extend(chunk)",
                "            if 10 in outgoing:",
                "                break",
                "            if len(outgoing) > MAX_RESPONSE_BYTES:",
                "                raise CliError('response too large')",
                "    if not outgoing:",
                "        raise CliError('empty bridge response')",
                "    line = outgoing.split(bytes([10]), 1)[0]",
                "    if len(line) > MAX_RESPONSE_BYTES:",
                "        raise CliError('response too large')",
                "    text = line.decode('utf-8')",
                "    try:",
                "        parsed = json.loads(text)",
                "    except ValueError:",
                "        raise CliError('bridge response is not JSON')",
                "    if not isinstance(parsed, dict):",
                "        raise CliError('bridge response is not a JSON object')",
                "    if parsed.get('v') != PROTOCOL_VERSION:",
                "        raise CliError('unsupported bridge response version')",
                "    return text, parsed",
                "",
                "",
                "def main(argv):",
                "    if len(argv) == 1 and argv[0] in ('-h', '--help'):",
                "        print(USAGE)",
                "        return 0",
                "    try:",
                "        method = parse_args(argv)",
                "        address, port, token = load_config(ENV_FILE)",
                "        text, parsed = call(address, port, token, method)",
                "    except CliError as error:",
                "        print('nusadesk-android: ' + str(error), file=sys.stderr)",
                "        return 2",
                "    except OSError:",
                "        print('nusadesk-android: bridge socket connection failed',",
                "              file=sys.stderr)",
                "        return 2",
                "    print(text)",
                "    if not parsed.get('ok'):",
                "        return 1",
                "    return 0",
                "",
                "",
                "if __name__ == '__main__':",
                "    sys.exit(main(sys.argv[1:]))",
                "") + "\n";
    }

    private static String generatedFooter(String version) {
        return "> Docs generated by the NusaDesk Android app (version " + version
                + "). Manual edits may be overwritten on the next session start.";
    }

    private static String requireVersion(String appVersion) {
        if (appVersion == null || appVersion.trim().isEmpty()
                || appVersion.indexOf('\n') >= 0 || appVersion.indexOf('\r') >= 0
                || appVersion.indexOf('\0') >= 0) {
            throw new IllegalArgumentException("appVersion must be a single safe line");
        }
        return appVersion.trim();
    }

    /**
     * Resolve one fixed relative parent, creating missing segments and
     * failing closed the moment any segment is a symlink or not a real
     * directory.
     */
    private static Path prepareDirectory(Path base, String relative, String description)
            throws IOException {
        Path cursor = base;
        for (String segment : relative.split("/")) {
            cursor = cursor.resolve(segment);
            if (Files.exists(cursor, LinkOption.NOFOLLOW_LINKS)) {
                if (Files.isSymbolicLink(cursor)
                        || !Files.isDirectory(cursor, LinkOption.NOFOLLOW_LINKS)) {
                    throw new IOException(description + " is not a real directory: " + cursor);
                }
            } else {
                Files.createDirectory(cursor);
            }
        }
        return cursor;
    }

    /** @return true when {@code target} was (re)written; false when it was already current */
    private static boolean ensureFile(Path target, byte[] expected, String permissions)
            throws IOException {
        if (Files.isRegularFile(target, LinkOption.NOFOLLOW_LINKS)
                && sameBytes(target, expected)) {
            setPermissions(target, permissions);
            return false;
        }
        Path temporary = Files.createTempFile(target.getParent(), TEMP_PREFIX, TEMP_SUFFIX);
        try {
            Files.write(temporary, expected, StandardOpenOption.TRUNCATE_EXISTING);
            setPermissions(temporary, permissions);
            moveAtomically(temporary, target);
            setPermissions(target, permissions);
            return true;
        } catch (IOException | RuntimeException failure) {
            try {
                Files.deleteIfExists(temporary);
            } catch (IOException ignored) {
                // Preserve the original failure.
            }
            throw failure;
        }
    }

    private static boolean sameBytes(Path file, byte[] expected) throws IOException {
        if (Files.size(file) != expected.length) {
            return false;
        }
        byte[] actual = Files.readAllBytes(file);
        if (actual.length != expected.length) {
            return false;
        }
        int difference = 0;
        for (int i = 0; i < expected.length; i++) {
            difference |= actual[i] ^ expected[i];
        }
        return difference == 0;
    }

    private static void moveAtomically(Path source, Path target) throws IOException {
        Set<StandardCopyOption> options = new HashSet<>();
        options.add(StandardCopyOption.ATOMIC_MOVE);
        options.add(StandardCopyOption.REPLACE_EXISTING);
        try {
            Files.move(source, target, options.toArray(new StandardCopyOption[0]));
        } catch (IOException atomicFailed) {
            try {
                Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException fallbackFailed) {
                fallbackFailed.addSuppressed(atomicFailed);
                throw fallbackFailed;
            }
        }
    }

    private static void setPermissions(Path file, String permissions) {
        try {
            Files.setPosixFilePermissions(file,
                    PosixFilePermissions.fromString(permissions));
        } catch (UnsupportedOperationException | IOException | IllegalArgumentException ignored) {
            // The app owns the extracted rootfs; providers without POSIX mode
            // support still leave the regular file writable by the owner.
        }
    }
}