package gh.nusashell.nusadesk.infrastructure.proot;

/**
 * Guest-side native Android tool dispatcher (ADR-0045).
 *
 * <p>The host binds the device's Android tool trees into the guest at their
 * identical paths ({@code /system/bin}, {@code /system/lib64}), so the
 * device's own binaries — mksh at {@code /system/bin/sh}, the
 * {@code toolbox} and {@code toybox} multicall binaries, and on a rooted
 * device {@code /system/bin/su} — run natively under the app's own uid.
 * This writer installs {@code /usr/local/bin/android-cli}, the single
 * dispatcher over that tree:</p>
 *
 * <ul>
 *   <li>{@code android-cli sh [args…]}, {@code getprop [name]},
 *       {@code toolbox <applet> [args…]} and
 *       {@code toybox <applet> [args…]} exec the matching
 *       {@code <root>/bin/} binary with the caller's argument list;</li>
 *   <li>{@code android-cli exec <absolute-path> [args…]} runs any binary
 *       under the bound trees — no verb allowlist: the platform's own
 *       uid/permission checks are the boundary, and a denial is passed
 *       through verbatim followed by one {@code android-cli: hint:} line;</li>
 *   <li>{@code android-cli su [args…]} runs the device's own
 *       {@code /system/bin/su} when present — the documented door to the
 *       root tier, one Magisk prompt per grant — and fails typed (exit 5)
 *       with a not-rooted hint when it is absent;</li>
 *   <li>{@code doctor} probes the tree (each core tool gets a one-line
 *       exec probe, device su is reported {@code present|absent}) and
 *       prints the resulting tier plus the boundary note;
 *       {@code status} prints the tier as one machine line.</li>
 * </ul>
 *
 * <p>There is deliberately no adb in this version: power comes from the
 * binaries themselves, not from a loopback daemon or a tcpip step. The
 * script never builds a shell string out of user arguments — child argv is
 * always a list — prints one
 * {@code android-cli: tier=… source=native device=…} informational line to
 * stderr (suppressed by {@code -q} or {@code ANDROID_CLI_QUIET=1}) so stdout
 * stays pipeable, propagates the child's own exit code, and answers a
 * missing tool with a typed exit 5 naming the path it probed.
 * {@code ANDROID_CLI_SYSTEM_ROOT} relocates the {@code /system} tree, which
 * exists so hermetic tests can point at a temp tree of fake binaries. Like
 * every generated guest file it is rewritten by
 * {@link GuestAwarenessReadmeWriter#ensure} on session start, so an app
 * update replaces a stale copy.</p>
 */
public final class GuestAndroidCliWriter {

    /** Guest-relative CLI path, executable on PATH. */
    public static final String GUEST_CLI_RELATIVE_PATH = "usr/local/bin/android-cli";
    /** CLI file name inside the fixed bin parent. */
    public static final String CLI_FILE_NAME = "android-cli";

    private GuestAndroidCliWriter() {
    }

    /**
     * The exact executable Python 3 script installed at
     * {@link #GUEST_CLI_RELATIVE_PATH}. Public so tests and documentation
     * tooling can pin the generated text.
     *
     * @param appVersion app version stamped into the script header
     */
    public static String scriptContent(String appVersion) {
        String version = GuestAwarenessReadmeWriter.requireVersionForWriter(appVersion);
        return String.join("\n",
                "#!/usr/bin/env python3",
                "# NusaDesk native Android tool dispatcher - generated by the",
                "# NusaDesk Android app. App version: " + version,
                "# Runs the device's own binaries natively inside the guest: the",
                "# host binds the Android tool trees at their identical paths, so",
                "# <root>/bin/sh, <root>/bin/toolbox and <root>/bin/toybox are the",
                "# phone's own tools run under the app's uid. There is no adb and",
                "# no tcpip step: the platform's own uid checks are the boundary",
                "# and a denial is passed through verbatim. Child argv is always",
                "# a list - never a shell string.",
                "",
                "import os",
                "import subprocess",
                "import sys",
                "",
                "SYSTEM_ROOT = os.environ.get('ANDROID_CLI_SYSTEM_ROOT') or '/system'",
                "ENV_FILE = '" + GuestAwarenessReadmeWriter.GUEST_ENV_FILE_PATH + "'",
                "PROBE_TIMEOUT_SECONDS = 10.0",
                "CORE_TOOLS = ('sh', 'toolbox', 'toybox')",
                "USAGE = ('usage: android-cli [-q] doctor'",
                "         + ' | status'",
                "         + ' | sh [args...]'",
                "         + ' | getprop [name]'",
                "         + ' | toolbox <applet> [args...]'",
                "         + ' | toybox <applet> [args...]'",
                "         + ' | su [args...]'",
                "         + ' | exec <absolute-path> [args...]')",
                "",
                "",
                "def quiet_env():",
                "    return os.environ.get('ANDROID_CLI_QUIET') == '1'",
                "",
                "",
                "ANDROID_BIN_PATHS = ['/system/bin', '/system/xbin', '/product/bin',",
                "                     '/apex/com.android.runtime/bin']",
                "ANDROID_LIB_PATHS = ['/apex/com.android.runtime/lib64/bionic',",
                "                     '/apex/com.android.art/lib64',",
                "                     '/apex/com.android.i18n/lib64',",
                "                     '/system/lib64']",
                "",
                "",
                "def child_env():",
                "    # Android's own search paths for the children only, so script-based",
                "    # tools find cmd/app_process and ABI libraries live where the",
                "    # linker expects them (the app cannot read /linkerconfig, so the",
                "    # linker has no namespace map of its own here). The session PATH",
                "    # is never touched, and the platform's checks remain the boundary.",
                "    env = dict(os.environ)",
                "    env['PATH'] = ':'.join(ANDROID_BIN_PATHS",
                "                           + ([env['PATH']] if env.get('PATH') else []))",
                "    env['LD_LIBRARY_PATH'] = ':'.join(",
                "        ANDROID_LIB_PATHS",
                "        + ([env['LD_LIBRARY_PATH']] if env.get('LD_LIBRARY_PATH') else []))",
                "    return env",
                "",
                "",
                "def info(tier, quiet):",
                "    if not quiet:",
                "        print('android-cli: tier=' + tier + ' source=native device='",
                "              + SYSTEM_ROOT, file=sys.stderr)",
                "",
                "",
                "def tool_path(name):",
                "    return os.path.join(SYSTEM_ROOT, 'bin', name)",
                "",
                "",
                "def present(path):",
                "    # Follows links on purpose: getprop -> toolbox counts when the",
                "    # toolbox binary it points at is there.",
                "    return os.path.isfile(path)",
                "",
                "",
                "def tier_now():",
                "    for name in CORE_TOOLS:",
                "        if present(tool_path(name)):",
                "            return 'app'",
                "    return 'none'",
                "",
                "",
                "def hint():",
                "    print('android-cli: hint: the platform denied this to the app uid;'",
                "          + ' this device grants more only to a higher tier - run'",
                "          + ' android-cli doctor', file=sys.stderr)",
                "",
                "",
                "def missing(path):",
                "    print('android-cli: ' + path + ': no such tool under'",
                "          + ' ANDROID_CLI_SYSTEM_ROOT (' + SYSTEM_ROOT + ')',",
                "          file=sys.stderr)",
                "    return 5",
                "",
                "",
                "def run_child(path, args):",
                "    try:",
                "        completed = subprocess.run([path] + list(args), env=child_env())",
                "    except FileNotFoundError:",
                "        return missing(path)",
                "    except OSError as error:",
                "        print('android-cli: ' + path + ': ' + str(error),",
                "              file=sys.stderr)",
                "        return 1",
                "    if completed.returncode != 0:",
                "        hint()",
                "    return completed.returncode",
                "",
                "",
                "def cmd_tool(name, args):",
                "    path = tool_path(name)",
                "    if not present(path):",
                "        return missing(path)",
                "    return run_child(path, args)",
                "",
                "",
                "def cmd_su(args):",
                "    path = tool_path('su')",
                "    if not present(path):",
                "        print('android-cli: ' + path + ': device su absent - the'",
                "              + ' device is not rooted, or su is not under the'",
                "              + ' bound trees; android-cli doctor shows what exists',",
                "              file=sys.stderr)",
                "        return 5",
                "    return run_child(path, args)",
                "",
                "",
                "def cmd_exec(args):",
                "    target = args[0]",
                "    if not target.startswith('/'):",
                "        print('android-cli: exec needs an absolute path under'",
                "              + ' ANDROID_CLI_SYSTEM_ROOT (' + SYSTEM_ROOT + ')',",
                "              file=sys.stderr)",
                "        return 2",
                "    normalized = os.path.normpath(target)",
                "    root = os.path.normpath(SYSTEM_ROOT)",
                "    prefix = root if root.endswith(os.sep) else root + os.sep",
                "    if normalized != root and not normalized.startswith(prefix):",
                "        print('android-cli: ' + normalized + ' is not under'",
                "              + ' ANDROID_CLI_SYSTEM_ROOT (' + root + ')',",
                "              file=sys.stderr)",
                "        return 2",
                "    if not present(normalized):",
                "        return missing(normalized)",
                "    return run_child(normalized, args[1:])",
                "",
                "",
                "def probe(argv):",
                "    try:",
                "        completed = subprocess.run(",
                "            argv, env=child_env(), stdout=subprocess.PIPE,",
                "            stderr=subprocess.STDOUT,",
                "            timeout=PROBE_TIMEOUT_SECONDS)",
                "    except (OSError, subprocess.SubprocessError):",
                "        return False, ''",
                "    output = completed.stdout or b''",
                "    return True, output.decode('utf-8', 'replace')",
                "",
                "",
                "def cmd_doctor():",
                "    print('android-cli doctor - native Android tools')",
                "    print('system root: ' + SYSTEM_ROOT",
                "          + ' (ANDROID_CLI_SYSTEM_ROOT)')",
                "    if not os.path.isdir(SYSTEM_ROOT):",
                "        print('system tree: missing - the host bound no Android'",
                "              + ' tool tree')",
                "    tier = 'none'",
                "    for name in CORE_TOOLS:",
                "        path = tool_path(name)",
                "        if not present(path):",
                "            print(name + ': missing (' + path + ')')",
                "            continue",
                "        if name == 'sh':",
                "            ran, output = probe([path, '-c', 'echo android-cli-probe'])",
                "            ok = ran and 'android-cli-probe' in output",
                "        else:",
                "            ran, _output = probe([path])",
                "            ok = ran",
                "        print(name + ': '",
                "              + ('present, exec ok' if ok else 'present, exec failed')",
                "              + ' (' + path + ')')",
                "        if ok:",
                "            tier = 'app'",
                "    for name in ('getprop', 'su'):",
                "        path = tool_path(name)",
                "        label = 'device su' if name == 'su' else name",
                "        print(label + ': ' + ('present' if present(path) else 'absent')",
                "              + ' (' + path + ')')",
                "    print('bridge session env: '",
                "          + ('present' if os.path.isfile(ENV_FILE) else 'absent')",
                "          + ' (informational only)')",
                "    print('tier: ' + tier + ' source=native')",
                "    print(\"note: privileged verbs (screencap, input, pm, am,\"",
                "          + \" dumpsys) are denied to an app uid by the platform's\"",
                "          + \" own checks - they fail verbatim and no flag changes\"",
                "          + \" that. A shell tier is a separate, documented enablement\"",
                "          + \" (the device's own adbd over loopback), not part of v1.\"",
                "          + \" On a rooted device android-cli su is the user's own door\"",
                "          + \" to a root shell: one Magisk prompt per grant.\")",
                "    return 0 if tier == 'app' else 5",
                "",
                "",
                "def cmd_status():",
                "    print('tier=' + tier_now() + ' source=native')",
                "    return 0",
                "",
                "",
                "def usage_error():",
                "    print('android-cli: ' + USAGE, file=sys.stderr)",
                "    return 2",
                "",
                "",
                "def main(argv):",
                "    args = list(argv)",
                "    quiet = quiet_env()",
                "    while args and args[0] in ('-q', '--quiet'):",
                "        args = args[1:]",
                "        quiet = True",
                "    if args and args[0] in ('-h', '--help'):",
                "        print(USAGE)",
                "        return 0",
                "    if not args:",
                "        return usage_error()",
                "    verb, rest = args[0], args[1:]",
                "    if verb == 'doctor':",
                "        if rest:",
                "            return usage_error()",
                "        info(tier_now(), quiet)",
                "        return cmd_doctor()",
                "    if verb == 'status':",
                "        if rest:",
                "            return usage_error()",
                "        info(tier_now(), quiet)",
                "        return cmd_status()",
                "    if verb == 'sh':",
                "        info(tier_now(), quiet)",
                "        return cmd_tool('sh', rest)",
                "    if verb == 'getprop':",
                "        if len(rest) > 1:",
                "            return usage_error()",
                "        info(tier_now(), quiet)",
                "        return cmd_tool('getprop', rest)",
                "    if verb in ('toolbox', 'toybox'):",
                "        if not rest:",
                "            return usage_error()",
                "        info(tier_now(), quiet)",
                "        return cmd_tool(verb, rest)",
                "    if verb == 'su':",
                "        info(tier_now(), quiet)",
                "        return cmd_su(rest)",
                "    if verb == 'exec':",
                "        if not rest:",
                "            return usage_error()",
                "        info(tier_now(), quiet)",
                "        return cmd_exec(rest)",
                "    return usage_error()",
                "",
                "",
                "if __name__ == '__main__':",
                "    sys.exit(main(sys.argv[1:]))",
                "") + "\n";
    }
}
