package gh.nusashell.nusadesk.infrastructure.ssh;

import android.util.Log;

import gh.nusashell.nusadesk.infrastructure.session.KeystoreBridgeCredential;

/**
 * The only production configuration for the in-app SSH client.
 *
 * <p>The app is not a general SSH client: the terminal attaches to the guest
 * Linux this app started, on the fixed loopback endpoint in
 * {@link LocalSshEndpoint}. This factory is that boundary. It exposes no
 * parameter for a host or a port, so no production caller can dial an external
 * target even by mistake; the generic {@link SshSessionConfig} constructor and
 * {@link SshClientBridge} remain for internal/test use only (ADR-0013).</p>
 *
 * <p>Identity is app-managed end to end:</p>
 * <ul>
 *   <li><b>Credential</b> — the per-install token in the Android Keystore vault
 *       ({@link KeystoreBridgeCredential#CREDENTIAL_ID}), the same secret the
 *       guest workload installs as the guest account's password. It is never
 *       user-entered and never leaves the vault except as a zeroed buffer.</li>
 *   <li><b>Host key</b> — the guest host key is generated by this app into its
 *       private storage and pinned under {@link LocalSshEndpoint#HOST_KEY_SCOPE}
 *       before readiness is published. {@link #pinnedHostKeyOnly()} refuses any
 *       key that is not the pinned one, so a foreign listener that somehow held
 *       the fixed port could not be attached to either.</li>
 * </ul>
 *
 * <p>Terminal size is the only variable: the caller supplies the initial PTY
 * dimensions, which the page reports after it fits.</p>
 */
public final class LocalSshSessionFactory {

    private static final String TAG = "LocalSshSessionFactory";

    /** Guest account the app-managed credential authenticates as. */
    public static final String USERNAME = "root";

    private static final int CONNECT_TIMEOUT_MILLIS = 15_000;
    private static final int AUTH_TIMEOUT_MILLIS = 15_000;
    private static final int CHANNEL_OPEN_TIMEOUT_MILLIS = 10_000;
    private static final int KEEPALIVE_INTERVAL_SECONDS = 30;

    private static final FirstHostKeyTrustCallback PINNED_ONLY = (host, fingerprint) -> {
        Log.w(TAG, "refusing an unpinned host key on the local endpoint " + host
                + "; the guest host key must be pinned by the runtime host before "
                + "the endpoint is published");
        return false;
    };

    private LocalSshSessionFactory() {
    }

    /**
     * Build the client configuration for the fixed local endpoint.
     *
     * @param initialCols initial PTY columns, validated by {@link SshSessionConfig}
     * @param initialRows initial PTY rows, validated by {@link SshSessionConfig}
     */
    public static SshSessionConfig create(int initialCols, int initialRows) {
        return new SshSessionConfig(
                LocalSshEndpoint.HOST,
                LocalSshEndpoint.PORT,
                USERNAME,
                KeystoreBridgeCredential.CREDENTIAL_ID,
                CONNECT_TIMEOUT_MILLIS,
                AUTH_TIMEOUT_MILLIS,
                CHANNEL_OPEN_TIMEOUT_MILLIS,
                KEEPALIVE_INTERVAL_SECONDS,
                SshSessionConfig.DEFAULT_TERMINAL_TYPE,
                initialCols,
                initialRows);
    }

    /**
     * Trust policy for the local endpoint: accept only the host key this app
     * pinned when it started the guest daemon.
     *
     * <p>A first-contact decision is meaningful for a user-chosen remote host;
     * for an endpoint this app created it would mean trusting whatever happens
     * to answer, which is exactly the foreign-listener attachment the fixed-port
     * contract forbids. Returning {@code false} leaves the connection refused
     * and stores nothing.</p>
     */
    public static FirstHostKeyTrustCallback pinnedHostKeyOnly() {
        return PINNED_ONLY;
    }
}
