package gh.nusashell.nusadesk.infrastructure.webapp;

import android.webkit.WebView;

import gh.nusashell.nusadesk.domain.webapp.WebAppDefinition;
import gh.nusashell.nusadesk.infrastructure.runtimehost.ExternalLinkHandler;
import gh.nusashell.nusadesk.infrastructure.runtimehost.LoopbackNavigationPolicy;
import gh.nusashell.nusadesk.infrastructure.runtimehost.LoopbackWebViewClient;
import gh.nusashell.nusadesk.infrastructure.runtimehost.LoopbackWebViewConfig;
import gh.nusashell.nusadesk.infrastructure.runtimehost.WebViewFailureListener;

/**
 * The locked-down WebView boundary for one user-defined local web app.
 *
 * <p>A launcher tile may load exactly one origin, generated from the app's
 * validated port: {@code http://127.0.0.1:<port>/}. Everything else about the
 * boundary follows from that:</p>
 *
 * <ul>
 *   <li>a different loopback port is a different origin and is blocked, not sent
 *       to the system browser, so one registered app can never reach another
 *       app's server or an unowned local listener;</li>
 *   <li>external HTTP(S) links and a small documented set of intent schemes leave
 *       the WebView for the system browser;</li>
 *   <li>{@code file}, {@code content}, {@code javascript}, {@code data},
 *       {@code blob} and non-blank {@code about:} URLs are blocked;</li>
 *   <li>no JavaScript interface is registered, and file / universal
 *       file-from-URL access stays disabled.</li>
 * </ul>
 *
 * <p>This class owns no navigation logic of its own: it binds the generated
 * web-app origin to the project's single implementation of the loopback WebView
 * boundary, so there is one place where that security decision is made and one
 * place to fix it. Constructing a boundary performs no I/O and starts no
 * process.</p>
 *
 * <p>Required attach order, owned by the caller: observe readiness through
 * {@link WebAppReadinessObserver}, then {@link #applySettings(WebView)}, then load
 * {@link #getLoadUrl()}. Loading first would render a browser error page
 * instead of an honest "not running yet" state.</p>
 */
public final class WebAppWebViewBoundary {
    private final WebAppDefinition definition;
    private final LoopbackNavigationPolicy navigationPolicy;
    private final LoopbackWebViewConfig webViewConfig = new LoopbackWebViewConfig();

    /**
     * @param definition the registered web app this boundary guards
     * @throws IllegalArgumentException when {@code definition} is null
     */
    public WebAppWebViewBoundary(WebAppDefinition definition) {
        if (definition == null) {
            throw new IllegalArgumentException("definition must not be null");
        }
        this.definition = definition;
        this.navigationPolicy = new LoopbackNavigationPolicy(definition.getEndpointUrl());
    }

    /** The app this boundary guards. */
    public WebAppDefinition getDefinition() {
        return definition;
    }

    /**
     * The only URL the caller may load: {@code http://127.0.0.1:<port>/}, exactly
     * as generated by {@link WebAppDefinition#getEndpointUrl()}.
     *
     * <p>Named for what the caller does with it. The underlying origin (without
     * the trailing path slash) is owned by the navigation policy this boundary
     * delegates to.</p>
     */
    public String getLoadUrl() {
        return definition.getEndpointUrl();
    }

    /**
     * Classifies a URL against this app's origin.
     *
     * @return {@code OWNED} to load in the WebView, {@code EXTERNAL} to hand to
     *         the system browser, {@code BLOCKED} to refuse; never null
     */
    public LoopbackNavigationPolicy.Decision classify(String url) {
        return navigationPolicy.classify(url);
    }

    /**
     * Applies the locked-down WebView settings: JavaScript on because the app's UI
     * needs it, DOM storage on, file and universal file-from-URL access off, and
     * no JavaScript interface.
     */
    public void applySettings(WebView webView) {
        webViewConfig.apply(webView);
    }

    /**
     * Builds the {@link LoopbackWebViewClient} that enforces {@link #classify(String)}
     * for this app. External URLs go to {@code externalHandler}; blocked
     * navigations and load/render failures go to {@code failureListener}.
     */
    public LoopbackWebViewClient newWebViewClient(
            ExternalLinkHandler externalHandler, WebViewFailureListener failureListener) {
        return new LoopbackWebViewClient(navigationPolicy, externalHandler, failureListener);
    }
}
