package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The W2e communications command set: {@code termux-sms-send},
 * {@code termux-telephony-call}, {@code termux-keystore},
 * {@code termux-job-scheduler}, and {@code termux-call-log}, re-homed onto
 * the shared {@code termux_compat} runtime like the core catalog.
 *
 * <p>Bodies only parse flags and translate payloads — {@code sms.send},
 * {@code phone.call}, {@code keystore.*}, {@code jobscheduler.*}, and the
 * existing parameter-free {@code calllog.list} do the real work inside
 * {@code CommsModule}. Per-recipient SMS results, keystore JSON shape, job
 * description text, and call-log fields mirror the upstream Termux scripts;
 * deliberate limits (guest-session-scoped job execution, bounded stdin,
 * absent SIM ids in call-log rows) are stated in {@code docLines}.</p>
 */
public final class TermuxCommsCommands {

    private TermuxCommsCommands() {
    }

    /** The comms commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                smsSend(),
                telephonyCall(),
                keystore(),
                jobScheduler(),
                callLog()));
    }

    private static TermuxCommand smsSend() {
        return new TermuxCommand(
                "termux-sms-send",
                String.join("\n",
                        "import sys",
                        "",
                        "USAGE = ('usage: termux-sms-send -n number[,number2,...]'",
                        "         ' [-s slot] [text]')",
                        "MAX_TEXT_CHARS = 8192",
                        "",
                        "",
                        "def parse(argv):",
                        "    recipients = None",
                        "    slot = None",
                        "    text_parts = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        arg = argv[index]",
                        "        if arg == '-h':",
                        "            print(USAGE)",
                        "            raise SystemExit(0)",
                        "        if arg in ('-n', '-s'):",
                        "            if index + 1 >= len(argv):",
                        "                raise tc.CliError(USAGE)",
                        "            value = argv[index + 1]",
                        "            if arg == '-n':",
                        "                recipients = value",
                        "            else:",
                        "                if not value.isdigit():",
                        "                    raise tc.CliError('slot must be a number')",
                        "                slot = int(value, 10)",
                        "            index += 2",
                        "            continue",
                        "        if arg.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        text_parts.append(arg)",
                        "        index += 1",
                        "    if recipients is None or not recipients.strip():",
                        "        raise tc.CliError('no recipient number given')",
                        "    text = (' '.join(text_parts) if text_parts",
                        "            else sys.stdin.read())",
                        "    if len(text) > MAX_TEXT_CHARS:",
                        "        raise tc.CliError('text too long (max '",
                        "                          + str(MAX_TEXT_CHARS) + ' chars)')",
                        "    return recipients, slot, text",
                        "",
                        "",
                        "def csv(value):",
                        "    return [part for part in str(value or '').split(',')",
                        "            if part]",
                        "",
                        "",
                        "def main(argv):",
                        "    recipients, slot, text = parse(argv)",
                        "    params = {'recipients': recipients, 'text': text}",
                        "    if slot is not None:",
                        "        params['slot'] = slot",
                        "    result = tc.bridge_call('sms.send', params)",
                        "    failed = csv(result.get('failed'))",
                        "    unconfirmed = csv(result.get('unconfirmed'))",
                        "    problems = []",
                        "    if failed:",
                        "        problems.append('failed: ' + ','.join(failed))",
                        "    if unconfirmed:",
                        "        problems.append('unconfirmed: '",
                        "                        + ','.join(unconfirmed))",
                        "    if problems:",
                        "        tc.warn('termux-sms-send',",
                        "                'not delivered to ' + '; '.join(problems))",
                        "        return 1",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-sms-send -n number[,number2,...] [-s slot]`",
                        "  `[text]` - real SMS via `SmsManager`; text comes from",
                        "  the arguments or stdin, matching upstream. Prints",
                        "  nothing when every recipient's parts report RESULT_OK;",
                        "  otherwise stderr lists the `failed`/`unconfirmed`",
                        "  recipients and the command exits 1 (upstream is",
                        "  fire-and-forget; here results are real). `-s slot`",
                        "  picks a SIM slot and needs READ_PHONE_STATE."));
    }

    private static TermuxCommand telephonyCall() {
        return new TermuxCommand(
                "termux-telephony-call",
                String.join("\n",
                        "USAGE = 'usage: termux-telephony-call <number>'",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv == ['-h']:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1 or argv[0].startswith('-'):",
                        "        raise tc.CliError(USAGE)",
                        "    tc.bridge_call('phone.call', {'number': argv[0]})",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-telephony-call <number>` - real call via",
                        "  `ACTION_CALL`; needs CALL_PHONE granted and the app",
                        "  able to come to foreground (a background launch is",
                        "  silently dropped by Android, so the bridge answers",
                        "  `foreground-required` instead)."));
    }

    private static TermuxCommand keystore() {
        return new TermuxCommand(
                "termux-keystore",
                String.join("\n",
                        "import base64",
                        "import json",
                        "import os",
                        "import sys",
                        "import tempfile",
                        "",
                        "USAGE = (",
                        "    'usage: termux-keystore command\\n'",
                        "    '  list [-d]\\n'",
                        "    '  delete <alias>\\n'",
                        "    '  generate <alias> [-a alg] [-s size] [-c curve]'",
                        "    ' [-u validity]\\n'",
                        "    '  sign <alias> <algorithm>   (data on stdin, raw'",
                        "    ' signature on stdout)\\n'",
                        "    '  verify <alias> <algorithm> <signature-file>'",
                        "    '   (data on stdin)')",
                        "MAX_INPUT_BYTES = 256 * 1024",
                        "MAX_INLINE_BYTES = 6144",
                        "",
                        "",
                        "def read_stdin():",
                        "    data = sys.stdin.buffer.read(MAX_INPUT_BYTES + 1)",
                        "    if len(data) > MAX_INPUT_BYTES:",
                        "        raise tc.CliError('input too large (max '",
                        "                          + str(MAX_INPUT_BYTES) + ' bytes)')",
                        "    return data",
                        "",
                        "",
                        "def stage(data):",
                        "    # A guest-visible /tmp file is a real path inside the",
                        "    # rootfs, so the bridge can resolve it; bind-mount",
                        "    # paths are not resolvable, so stdin/signature bytes",
                        "    # always land here first.",
                        "    handle = tempfile.NamedTemporaryFile(",
                        "        prefix='nusadesk-keystore-', dir='/tmp',",
                        "        delete=False)",
                        "    try:",
                        "        handle.write(data)",
                        "    finally:",
                        "        handle.close()",
                        "    return handle.name",
                        "",
                        "",
                        "def data_param(raw):",
                        "    if len(raw) <= MAX_INLINE_BYTES:",
                        "        return ({'data':",
                        "                base64.b64encode(raw).decode('ascii')}, [])",
                        "    path = stage(raw)",
                        "    return ({'path': path}, [path])",
                        "",
                        "",
                        "def parse_generate(args):",
                        "    algorithm = 'RSA'",
                        "    size = -1",
                        "    curve = None",
                        "    validity = 0",
                        "    index = 0",
                        "    while index < len(args):",
                        "        flag = args[index]",
                        "        if flag not in ('-a', '-s', '-c', '-u') \\",
                        "                or index + 1 >= len(args):",
                        "            raise tc.CliError(USAGE)",
                        "        value = args[index + 1]",
                        "        if flag == '-a':",
                        "            algorithm = value",
                        "        elif flag == '-s':",
                        "            if not value.isdigit():",
                        "                raise tc.CliError('invalid key size ' + value)",
                        "            size = int(value, 10)",
                        "        elif flag == '-c':",
                        "            curve = value",
                        "        else:",
                        "            if not value.isdigit():",
                        "                raise tc.CliError(",
                        "                    'invalid validity ' + value)",
                        "            validity = int(value, 10)",
                        "        index += 2",
                        "    if algorithm == 'RSA':",
                        "        if size == -1:",
                        "            size = 2048",
                        "        if size not in (2048, 3072, 4096):",
                        "            raise tc.CliError(",
                        "                'invalid RSA key size ' + str(size))",
                        "    elif algorithm == 'EC':",
                        "        curve = (curve or {256: 'secp256r1',",
                        "                           384: 'secp384r1',",
                        "                           521: 'secp521r1'}.get(size))",
                        "        if curve is None:",
                        "            raise tc.CliError(",
                        "                'invalid EC key size ' + str(size))",
                        "    else:",
                        "        raise tc.CliError(",
                        "            'invalid algorithm ' + algorithm)",
                        "    return algorithm, size, curve or 'secp256r1', validity",
                        "",
                        "",
                        "def main(argv):",
                        "    if not argv:",
                        "        raise tc.CliError(USAGE)",
                        "    action, args = argv[0], argv[1:]",
                        "    staged = []",
                        "    try:",
                        "        if action == 'list':",
                        "            detailed = args == ['-d']",
                        "            if args and not detailed:",
                        "                raise tc.CliError(USAGE)",
                        "            result = tc.bridge_call(",
                        "                'keystore.list', {'detailed': detailed})",
                        "            return tc.emit(",
                        "                json.loads(result.get('keys_json', '[]')))",
                        "        if action == 'delete':",
                        "            if len(args) != 1:",
                        "                raise tc.CliError(USAGE)",
                        "            tc.bridge_call('keystore.delete',",
                        "                           {'alias': args[0]})",
                        "            return 0",
                        "        if action == 'generate':",
                        "            if not args:",
                        "                raise tc.CliError(",
                        "                    'generate needs an alias')",
                        "            alias = args[0]",
                        "            algorithm, size, curve, validity = \\",
                        "                parse_generate(args[1:])",
                        "            params = {'alias': alias, 'algorithm': algorithm,",
                        "                      'validity_seconds': validity,",
                        "                      'purposes': 'sign,verify',",
                        "                      'digests':",
                        "                      'none,sha1,sha256,sha384,sha512'}",
                        "            if algorithm == 'RSA':",
                        "                params['size'] = size",
                        "            else:",
                        "                params['curve'] = curve",
                        "            tc.bridge_call('keystore.generate', params)",
                        "            return 0",
                        "        if action == 'sign':",
                        "            if len(args) != 2:",
                        "                raise tc.CliError(USAGE)",
                        "            params, staged = data_param(read_stdin())",
                        "            params['alias'] = args[0]",
                        "            params['algorithm'] = args[1]",
                        "            result = tc.bridge_call('keystore.sign', params)",
                        "            signature = base64.b64decode(",
                        "                result.get('signature', ''))",
                        "            sys.stdout.buffer.write(signature)",
                        "            return 0",
                        "        if action == 'verify':",
                        "            if len(args) != 3:",
                        "                raise tc.CliError(USAGE)",
                        "            with open(args[2], 'rb') as handle:",
                        "                signature = handle.read(MAX_INPUT_BYTES + 1)",
                        "            if len(signature) > MAX_INPUT_BYTES:",
                        "                raise tc.CliError('signature too large')",
                        "            signature_path = stage(signature)",
                        "            staged.append(signature_path)",
                        "            params, data_staged = data_param(read_stdin())",
                        "            staged.extend(data_staged)",
                        "            params['alias'] = args[0]",
                        "            params['algorithm'] = args[1]",
                        "            params['signature_path'] = signature_path",
                        "            result = tc.bridge_call('keystore.verify', params)",
                        "            print('true' if result.get('verified')",
                        "                  else 'false')",
                        "            return 0",
                        "        raise tc.CliError(USAGE)",
                        "    finally:",
                        "        for path in staged:",
                        "            try:",
                        "                os.unlink(path)",
                        "            except OSError:",
                        "                pass",
                        ""),
                Arrays.asList(
                        "- `termux-keystore list [-d]` - aliases inside",
                        "  AndroidKeyStore as the upstream JSON array",
                        "  (`alias`, `algorithm`, `size`,",
                        "  `inside_secure_hardware`, `user_authentication`);",
                        "  `-d` adds RSA `modulus`/`exponent` or EC `x`/`y`.",
                        "- `termux-keystore delete <alias>` - remove a key",
                        "  (no-op when absent, like upstream).",
                        "- `termux-keystore generate <alias> [-a RSA|EC]`",
                        "  `[-s size] [-c curve] [-u validity]` - generate a",
                        "  sign+verify key; RSA sizes 2048/3072/4096, EC sizes",
                        "  256/384/521 (or `-c` an explicit curve). `-u` seconds",
                        "  requires device unlock before use.",
                        "- `termux-keystore sign <alias> <algorithm>` - stdin",
                        "  data in, raw signature bytes out (upstream shape);",
                        "  stdin and signature files are bounded at 256 KiB.",
                        "- `termux-keystore verify <alias> <algorithm>`",
                        "  `<signature-file>` - stdin data in, prints `true` or",
                        "  `false`. Private keys never leave AndroidKeyStore; a",
                        "  user-locked key answers `keystore-auth-required`."));
    }

    private static TermuxCommand jobScheduler() {
        return new TermuxCommand(
                "termux-job-scheduler",
                String.join("\n",
                        "import json",
                        "",
                        "USAGE = (",
                        "    'usage: termux-job-scheduler [options]\\n'",
                        "    '  -p/--pending            list pending jobs\\n'",
                        "    '  --cancel-all           cancel all jobs\\n'",
                        "    '  --cancel --job-id N    cancel one job\\n'",
                        "    '  -s/--script PATH       script to schedule\\n'",
                        "    '  --job-id N --period-ms MS --network NAME\\n'",
                        "    '  --battery-not-low BOOL --storage-not-low BOOL\\n'",
                        "    '  --charging BOOL --persisted BOOL\\n'",
                        "    '  --trigger-content-uri URI'",
                        "    ' --trigger-content-flag N')",
                        "BOOLS = ('--battery-not-low', '--storage-not-low',",
                        "         '--charging', '--persisted')",
                        "INTS = ('--job-id', '--period-ms',",
                        "        '--trigger-content-flag')",
                        "ALIASES = {'-s': 'script'}",
                        "STRINGS = ('-s', '--script', '--network',",
                        "           '--trigger-content-uri')",
                        "",
                        "",
                        "def parse_bool(value):",
                        "    if value in ('true', '1'):",
                        "        return True",
                        "    if value in ('false', '0'):",
                        "        return False",
                        "    raise tc.CliError('expected true/false: ' + value)",
                        "",
                        "",
                        "def parse_int(value):",
                        "    if not value.isdigit():",
                        "        raise tc.CliError('expected a number: ' + value)",
                        "    return int(value, 10)",
                        "",
                        "",
                        "def format_job(job):",
                        "    desc = []",
                        "    if job.get('periodic'):",
                        "        desc.append('(periodic: %dms)'",
                        "                    % int(job.get('interval_ms', 0)))",
                        "    if job.get('charging'):",
                        "        desc.append('(while charging)')",
                        "    if job.get('idle'):",
                        "        desc.append('(while idle)')",
                        "    if job.get('persisted'):",
                        "        desc.append('(persisted)')",
                        "    if job.get('battery_not_low'):",
                        "        desc.append('(battery not low)')",
                        "    if job.get('storage_not_low'):",
                        "        desc.append('(storage not low)')",
                        "    desc.append('(network: %s)'",
                        "                % job.get('network', 'any'))",
                        "    return 'Job %d: %s    %s' % (",
                        "        int(job.get('id', 0)), job.get('script', ''),",
                        "        ' '.join(desc))",
                        "",
                        "",
                        "def warn_recent(reading):",
                        "    for job in json.loads(reading.get('jobs_json', '[]')):",
                        "        if job.get('last_result') == 'session-down':",
                        "            tc.warn('termux-job-scheduler',",
                        "                    'job %d last trigger missed: guest'",
                        "                    ' session was not running'",
                        "                    % int(job.get('id', 0)))",
                        "    for item in json.loads(",
                        "            reading.get('recent_json', '[]')):",
                        "        tc.warn('termux-job-scheduler',",
                        "                'job %d %s' % (int(item.get('id', 0)),",
                        "                               item.get('result', '?')))",
                        "",
                        "",
                        "def print_jobs(reading, label):",
                        "    jobs = json.loads(reading.get('jobs_json', '[]'))",
                        "    if not jobs:",
                        "        print('No jobs found')",
                        "        return",
                        "    print('\\n'.join(label + ' ' + format_job(job)",
                        "                     for job in jobs))",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv == ['-h'] or argv == ['--help']:",
                        "        print(USAGE)",
                        "        return 0",
                        "    params = {}",
                        "    pending = False",
                        "    cancel = False",
                        "    cancel_all = False",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-p', '--pending'):",
                        "            pending = True",
                        "            index += 1",
                        "            continue",
                        "        if flag == '--cancel':",
                        "            cancel = True",
                        "            index += 1",
                        "            continue",
                        "        if flag == '--cancel-all':",
                        "            cancel_all = True",
                        "            index += 1",
                        "            continue",
                        "        if flag in BOOLS + INTS + STRINGS:",
                        "            if index + 1 >= len(argv):",
                        "                raise tc.CliError(USAGE)",
                        "            value = argv[index + 1]",
                        "            key = ALIASES.get(",
                        "                flag, flag.lstrip('-').replace('-', '_'))",
                        "            if flag in BOOLS:",
                        "                params[key] = parse_bool(value)",
                        "            elif flag in INTS:",
                        "                params[key] = parse_int(value)",
                        "            else:",
                        "                params[key] = value",
                        "            index += 2",
                        "            continue",
                        "        raise tc.CliError(USAGE)",
                        "    if pending:",
                        "        reading = tc.call('jobscheduler.list')",
                        "        print_jobs(reading, 'Pending')",
                        "        warn_recent(reading)",
                        "        return 0",
                        "    if cancel_all:",
                        "        print_jobs(",
                        "            tc.bridge_call('jobscheduler.cancel',",
                        "                           {'all': True}), 'Cancelling')",
                        "        return 0",
                        "    if cancel:",
                        "        if 'job_id' not in params:",
                        "            raise tc.CliError(",
                        "                '--cancel needs --job-id N')",
                        "        result = tc.bridge_call('jobscheduler.cancel',",
                        "                                {'job_id': params['job_id']})",
                        "        if result.get('found'):",
                        "            print_jobs(result, 'Cancelling')",
                        "        else:",
                        "            print('No job %d found' % params['job_id'])",
                        "        return 0",
                        "    if 'script' not in params:",
                        "        raise tc.CliError('no script path given')",
                        "    result = tc.bridge_call('jobscheduler.schedule',",
                        "                            params)",
                        "    job_id = int(result.get('job_id', 0))",
                        "    desc = format_job({",
                        "        'id': job_id, 'script': params['script'],",
                        "        'periodic': params.get('period_ms', 0) > 0,",
                        "        'interval_ms': params.get('period_ms', 0),",
                        "        'charging': params.get('charging', False),",
                        "        'idle': False,",
                        "        'persisted': params.get('persisted', False),",
                        "        'battery_not_low':",
                        "            params.get('battery_not_low', True),",
                        "        'storage_not_low':",
                        "            params.get('storage_not_low', False),",
                        "        'network': params.get('network', 'any')})",
                        "    print('Scheduling %s - response %d'",
                        "          % (desc, int(result.get('result_code', 0))))",
                        "    for job in json.loads(result.get('jobs_json', '[]')):",
                        "        if int(job.get('id', -1)) == job_id:",
                        "            print('Pending ' + format_job(job))",
                        "            break",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-job-scheduler -s PATH [options]` - real",
                        "  `JobScheduler` entry (`--job-id`, `--period-ms`,",
                        "  `--network`, `--battery-not-low`,",
                        "  `--storage-not-low`, `--charging`, `--persisted`,",
                        "  `--trigger-content-uri`, `--trigger-content-flag`);",
                        "  `-p/--pending`, `--cancel --job-id N`,",
                        "  `--cancel-all` mirror upstream output.",
                        "  LIMITATION: a job only runs while the NusaDesk",
                        "  guest session is running — a trigger on a stopped",
                        "  session is recorded as `session-down` and reported",
                        "  on stderr; there is no background execution and no",
                        "  fake timer. Scripts run inside the guest through",
                        "  the session's own SSH channel."));
    }

    private static TermuxCommand callLog() {
        return new TermuxCommand(
                "termux-call-log",
                String.join("\n",
                        "import datetime",
                        "import json",
                        "",
                        "USAGE = ('usage: termux-call-log [-l limit]'",
                        "         ' [-o offset]')",
                        "DEFAULT_LIMIT = 10",
                        "DEFAULT_OFFSET = 0",
                        "",
                        "",
                        "def parse(argv):",
                        "    limit = DEFAULT_LIMIT",
                        "    offset = DEFAULT_OFFSET",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-h':",
                        "            print(USAGE)",
                        "            raise SystemExit(0)",
                        "        if flag not in ('-l', '-o') \\",
                        "                or index + 1 >= len(argv):",
                        "            raise tc.CliError(USAGE)",
                        "        value = argv[index + 1]",
                        "        if not value.isdigit():",
                        "            raise tc.CliError(",
                        "                'the -' + flag[1] + ' value '",
                        "                + repr(value) + ' is not a positive'",
                        "                ' number')",
                        "        if flag == '-l':",
                        "            limit = int(value, 10)",
                        "        else:",
                        "            offset = int(value, 10)",
                        "        index += 2",
                        "    return limit, offset",
                        "",
                        "",
                        "def duration_text(total_seconds):",
                        "    total = int(total_seconds)",
                        "    hours = total // 3600",
                        "    mins = (total % 3600) // 60",
                        "    secs = total % 60",
                        "    text = '%02d:%02d' % (mins, secs)",
                        "    return ('%02d:' % hours + text) if hours else text",
                        "",
                        "",
                        "def to_termux(row):",
                        "    timestamp = row.get('timestamp_utc_ms', 0)",
                        "    date = datetime.datetime.fromtimestamp(",
                        "        timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')",
                        "    call_type = str(row.get('type', 'unknown')).upper()",
                        "    if call_type == 'UNKNOWN':",
                        "        call_type = 'UNKNOWN_TYPE'",
                        "    return {",
                        "        'name': row.get('name') or 'UNKNOWN_CALLER',",
                        "        'phone_number': row.get('number', ''),",
                        "        'type': call_type,",
                        "        'date': date,",
                        "        'duration': duration_text(",
                        "            row.get('duration_seconds', 0)),",
                        "        'sim_id': None,",
                        "    }",
                        "",
                        "",
                        "def main(argv):",
                        "    limit, offset = parse(argv)",
                        "    # calllog.list is parameter-free: it returns a",
                        "    # bounded newest-first window, so limit/offset are",
                        "    # slices over that window here in the guest.",
                        "    reading = tc.call('calllog.list')",
                        "    tc.warn_truncated('termux-call-log', reading)",
                        "    if reading.get('available') is not True:",
                        "        raise tc.BridgeError('call log unavailable')",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    window = rows[offset:offset + limit]",
                        "    return tc.emit([to_termux(row) for row in window",
                        "                    if isinstance(row, dict)])",
                        ""),
                Arrays.asList(
                        "- `termux-call-log [-l limit] [-o offset]` - call",
                        "  history in upstream shape: `name` (`UNKNOWN_CALLER`",
                        "  when uncached), `phone_number`, `type`, `date`",
                        "  (`yyyy-MM-dd HH:mm:ss`), `duration` (`MM:SS`/`HH:MM:SS`),",
                        "  `sim_id`. The bridge row window is bounded and",
                        "  newest-first; `-l`/`-o` slice it guest-side",
                        "  (defaults 10/0) and truncation warns on stderr.",
                        "  `sim_id` is always null: the bridge deliberately",
                        "  does not expose phone-account identifiers."));
    }
}
