package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Collections;
import java.util.List;

/**
 * The sensor domain's Termux-compat commands: the full-flag {@code
 * termux-sensor} over {@code sensor.list}, {@code sensor.read}, and the
 * {@code sensor.stream.*} pull stream.
 *
 * <p>Upstream key differences the doc lines record: sensor names are the
 * bridge's canonical lowercase type names (not the device-reported label),
 * {@code -n} is capped at 10 samples per bounded read, the continuous mode is
 * a pull stream whose documents carry every requested sensor's latest values,
 * and {@code -c} stops that stream instead of freeing a service.</p>
 */
public final class TermuxSensorCommands {

    private TermuxSensorCommands() {
    }

    /** The sensor commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.singletonList(sensor());
    }

    private static TermuxCommand sensor() {
        return new TermuxCommand(
                "termux-sensor",
                String.join("\n",
                        "import json",
                        "",
                        "USAGE = ('usage: termux-sensor [-h] [-a] [-c] [-l]'",
                        "         ' [-s sensors] [-d delay_ms] [-n count]')",
                        "DEFAULT_DELAY_MS = 1000",
                        "MAX_DELAY_MS = 5000",
                        "MAX_READ_SAMPLES = 10",
                        "POLL_TIMEOUT_MS = 2000",
                        "",
                        "",
                        "def parse(argv):",
                        "    flags = set()",
                        "    sensors = ''",
                        "    delay_ms = DEFAULT_DELAY_MS",
                        "    delay_given = False",
                        "    limit = None",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-h', '--help'):",
                        "            flags.add('h')",
                        "            index += 1",
                        "            continue",
                        "        if flag in ('-a', '-c', '-l'):",
                        "            flags.add(flag[1])",
                        "            index += 1",
                        "            continue",
                        "        if flag not in ('-s', '-d', '-n') or index + 1 >= len(argv):",
                        "            raise tc.CliError(USAGE)",
                        "        value = argv[index + 1]",
                        "        if flag == '-s':",
                        "            sensors = value",
                        "        elif flag == '-d':",
                        "            if not value.isdigit():",
                        "                raise tc.CliError('delay must be a number')",
                        "            delay_ms = int(value, 10)",
                        "            delay_given = True",
                        "            if delay_ms > MAX_DELAY_MS:",
                        "                raise tc.CliError('delay above the bridge cap of '",
                        "                                  + str(MAX_DELAY_MS) + ' ms')",
                        "        else:",
                        "            if not value.isdigit() or int(value, 10) < 1:",
                        "                raise tc.CliError('limit must be a positive number')",
                        "            limit = int(value, 10)",
                        "        index += 2",
                        "    if 'c' in flags:",
                        "        if len(flags) > 1 or sensors or delay_given or limit is not None:",
                        "            raise tc.CliError('no other options allowed with -c')",
                        "    elif 'l' in flags:",
                        "        if len(flags) > 1 or sensors or delay_given or limit is not None:",
                        "            raise tc.CliError('no other options allowed with -l')",
                        "    elif delay_given and 'a' not in flags and not sensors:",
                        "        raise tc.CliError('use -s or -a when using -d')",
                        "    elif 'a' in flags and sensors:",
                        "        raise tc.CliError('listed sensors are ignored with -a')",
                        "    elif 'a' not in flags and not sensors and 'h' not in flags:",
                        "        raise tc.CliError('no sensors selected (use -s, -a, -l, or -c)')",
                        "    return flags, sensors, delay_ms, limit",
                        "",
                        "",
                        "def stream(params):",
                        "    started = tc.bridge_call('sensor.stream.start', params)",
                        "    tc.warn_truncated('termux-sensor', started)",
                        "    try:",
                        "        while True:",
                        "            event = tc.bridge_call('sensor.stream.poll',",
                        "                                   {'timeout_ms': POLL_TIMEOUT_MS})",
                        "            if event.get('stream_stopped'):",
                        "                break",
                        "            sample = event.get('sample_json')",
                        "            if sample is not None:",
                        "                tc.print_json(json.loads(sample))",
                        "    except KeyboardInterrupt:",
                        "        pass",
                        "    finally:",
                        "        try:",
                        "            tc.bridge_call('sensor.stream.stop')",
                        "        except Exception:",
                        "            pass",
                        "    return 0",
                        "",
                        "",
                        "def main(argv):",
                        "    if not argv:",
                        "        raise tc.CliError('no arguments supplied')",
                        "    flags, sensors, delay_ms, limit = parse(argv)",
                        "    if 'h' in flags:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if 'l' in flags:",
                        "        reading = tc.bridge_call('sensor.list')",
                        "        tc.warn_truncated('termux-sensor', reading)",
                        "        rows = json.loads(reading.get('sensors_json', '[]'))",
                        "        names = [row.get('name') for row in rows",
                        "                 if isinstance(row, dict) and row.get('name')]",
                        "        return tc.emit({'sensors': names})",
                        "    if 'c' in flags:",
                        "        result = tc.bridge_call('sensor.stream.stop')",
                        "        if result.get('was_running'):",
                        "            print('Sensor cleanup successful!')",
                        "        else:",
                        "            print('Sensor cleanup unnecessary')",
                        "        return 0",
                        "    params = {'delay_ms': delay_ms}",
                        "    if 'a' in flags:",
                        "        params['all'] = True",
                        "    else:",
                        "        params['sensor'] = sensors",
                        "    if limit is not None:",
                        "        if limit > MAX_READ_SAMPLES:",
                        "            raise tc.CliError('limit above the bridge cap of '",
                        "                              + str(MAX_READ_SAMPLES))",
                        "        params['count'] = limit",
                        "        timeout = 25.0 + (limit * delay_ms) / 1000.0",
                        "        reading = tc.bridge_call('sensor.read', params, timeout=timeout)",
                        "        tc.warn_truncated('termux-sensor', reading)",
                        "        for document in json.loads(reading.get('samples_json', '[]')):",
                        "            tc.print_json(document)",
                        "        return 0",
                        "    return stream(params)",
                        ""),
                java.util.Arrays.asList(
                        "- `termux-sensor [-h] [-a] [-c] [-l] [-s sensors] [-d ms] [-n n]`",
                        "  - full-flag sensor client. `-l` prints `{\"sensors\":[...]}` of",
                        "  canonical lowercase type names (`accelerometer`, `gyroscope`,",
                        "  `magnetic_field`, `light`, `proximity`, `pressure`,",
                        "  `step_counter`, ...), not upstream's device labels; `-s` takes",
                        "  a comma list of names, numeric types, or substrings (shortest",
                        "  match wins, like upstream). `-n 1..10` emits one",
                        "  `{SENSOR:{values:[..]}}` document per sample via a bounded",
                        "  read; without `-n` it streams via `sensor.stream.*` until",
                        "  interrupted, and each document carries the latest values of",
                        "  every requested sensor (samples between polls coalesce).",
                        "  `-d` is bounded to 0..5000 ms and `-c` stops the stream."));
    }
}
