package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Text and notification Termux-compat commands (bridge v2, W2a):
 * {@code termux-clipboard-get}, {@code termux-clipboard-set},
 * {@code termux-toast}, {@code termux-notification},
 * {@code termux-notification-channel}, {@code termux-notification-list},
 * {@code termux-notification-remove}.
 *
 * <p>Flags and output mirror the upstream {@code termux-api-package}
 * scripts: clipboard get prints raw text (no JSON), channel create/delete
 * prints upstream's confirmation line, and notification list prints the
 * upstream JSON array shape. Flags the bridge cannot honour — toast colors
 * and gravity, notification actions/buttons/media/LED/icon/type — fail
 * with usage instead of being silently ignored. Long or control-carrying
 * text (newlines) cannot cross the framed params, so it is staged as a
 * file in guest {@code /tmp} per contract §8.1 and sent as
 * {@code text_path}/{@code content_path}; {@code --image-path} is staged
 * the same way and every staging file is removed in a {@code finally}.</p>
 */
public final class TermuxTextCommands {

    private TermuxTextCommands() {
    }

    /** The text/notification commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                clipboardGet(),
                clipboardSet(),
                toast(),
                notification(),
                notificationChannel(),
                notificationList(),
                notificationRemove()));
    }

    private static TermuxCommand clipboardGet() {
        return new TermuxCommand(
                "termux-clipboard-get",
                String.join("\n",
                        "def main(argv):",
                        "    if argv == ['-h']:",
                        "        print('Usage: termux-clipboard-get')",
                        "        print('Get the system clipboard text.')",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-clipboard-get')",
                        "    reading = tc.call('clipboard.get')",
                        "    tc.warn_truncated('termux-clipboard-get', reading)",
                        "    # Upstream prints the raw clip text, not JSON.",
                        "    sys.stdout.write(reading['text'])",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-clipboard-get` - print the system clipboard",
                        "  text (raw text, not JSON). Requires the app in the",
                        "  foreground on Android 10+; otherwise the command exits",
                        "  `1` with `clipboard-permission-required`"));
    }

    private static TermuxCommand clipboardSet() {
        return new TermuxCommand(
                "termux-clipboard-set",
                String.join("\n",
                        "import os",
                        "import tempfile",
                        "",
                        "MAX_INLINE_CHARS = 8192",
                        "",
                        "",
                        "def has_control_chars(text):",
                        "    return any(ord(char) < 32 or 127 <= ord(char) < 160",
                        "               for char in text)",
                        "",
                        "",
                        "def stage_text(text):",
                        "    fd, staging = tempfile.mkstemp(prefix='nusadesk-text-',",
                        "                                   dir='/tmp')",
                        "    with os.fdopen(fd, 'w', encoding='utf-8') as handle:",
                        "        handle.write(text)",
                        "    return staging",
                        "",
                        "",
                        "def main(argv):",
                        "    args = list(argv)",
                        "    while args and args[0].startswith('-') and args[0] != '-':",
                        "        option = args.pop(0)",
                        "        if option == '--':",
                        "            break",
                        "        if option == '-h':",
                        "            print('Usage: termux-clipboard-set [text]')",
                        "            print('Set the system clipboard text. The text is either')",
                        "            print('supplied as arguments or read from stdin.')",
                        "            return 0",
                        "        raise tc.CliError('illegal option ' + option)",
                        "    text = ' '.join(args) if args else sys.stdin.read()",
                        "    staging = None",
                        "    params = {}",
                        "    try:",
                        "        if len(text) > MAX_INLINE_CHARS or has_control_chars(text):",
                        "            staging = stage_text(text)",
                        "            params['text_path'] = staging",
                        "        else:",
                        "            params['text'] = text",
                        "        tc.bridge_call('clipboard.set', params)",
                        "    finally:",
                        "        if staging is not None:",
                        "            try:",
                        "                os.unlink(staging)",
                        "            except OSError:",
                        "                pass",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-clipboard-set [text]` - set the system",
                        "  clipboard; text comes from arguments or stdin like",
                        "  upstream. Prints nothing on success"));
    }

    private static TermuxCommand toast() {
        return new TermuxCommand(
                "termux-toast",
                String.join("\n",
                        "import os",
                        "import select",
                        "import tempfile",
                        "",
                        "MAX_INLINE_CHARS = 8192",
                        "",
                        "",
                        "def has_control_chars(text):",
                        "    return any(ord(char) < 32 or 127 <= ord(char) < 160",
                        "               for char in text)",
                        "",
                        "",
                        "def stage_text(text):",
                        "    fd, staging = tempfile.mkstemp(prefix='nusadesk-text-',",
                        "                                   dir='/tmp')",
                        "    with os.fdopen(fd, 'w', encoding='utf-8') as handle:",
                        "        handle.write(text)",
                        "    return staging",
                        "",
                        "",
                        "def read_stdin(timeout):",
                        "    try:",
                        "        ready, _, _ = select.select([sys.stdin], [], [], timeout)",
                        "        if not ready:",
                        "            return ''",
                        "        return os.read(sys.stdin.fileno(), 65536).decode(",
                        "            'utf-8', 'replace')",
                        "    except OSError:",
                        "        return ''",
                        "",
                        "",
                        "def main(argv):",
                        "    args = list(argv)",
                        "    short = False",
                        "    index = 0",
                        "    while index < len(args):",
                        "        flag = args[index]",
                        "        if flag == '--':",
                        "            index += 1",
                        "            break",
                        "        if flag == '-h':",
                        "            print('Usage: termux-toast [-s] [text]')",
                        "            print('Show text in a Toast (a transient popup).')",
                        "            print('The text is either supplied as arguments or read')",
                        "            print('from stdin if no arguments are given.')",
                        "            return 0",
                        "        if flag == '-s':",
                        "            short = True",
                        "            index += 1",
                        "            continue",
                        "        if flag in ('-b', '-c', '-g'):",
                        "            raise tc.CliError('unsupported flag ' + flag + ': toast'",
                        "                              ' color and gravity are not supported')",
                        "        if flag.startswith('-') and flag != '-':",
                        "            raise tc.CliError('illegal option ' + flag)",
                        "        break",
                        "    rest = args[index:]",
                        "    text = ' '.join(rest) if rest else read_stdin(3.0)",
                        "    text = text.rstrip('\\n')",
                        "    staging = None",
                        "    params = {'short': short}",
                        "    try:",
                        "        if len(text) > MAX_INLINE_CHARS or has_control_chars(text):",
                        "            staging = stage_text(text)",
                        "            params['text_path'] = staging",
                        "        else:",
                        "            params['text'] = text",
                        "        tc.bridge_call('toast', params)",
                        "    finally:",
                        "        if staging is not None:",
                        "            try:",
                        "                os.unlink(staging)",
                        "            except OSError:",
                        "                pass",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-toast [-s] [text]` - show a Toast; text comes",
                        "  from arguments or stdin (3 s wait) like upstream.",
                        "  `-s` short duration. Upstream's `-b`/`-c`/`-g` color and",
                        "  gravity flags are not supported and fail with usage"));
    }

    private static TermuxCommand notification() {
        return new TermuxCommand(
                "termux-notification",
                String.join("\n",
                        "import os",
                        "import select",
                        "import shutil",
                        "import tempfile",
                        "",
                        "PRIORITIES = ('min', 'low', 'default', 'high', 'max')",
                        "MAX_INLINE_CHARS = 8192",
                        "",
                        "# Flags upstream accepts that this bridge cannot honour:",
                        "# actions and buttons execute inside the Termux app, and",
                        "# icon/LED/type need resources or styles NusaDesk does not",
                        "# carry. They fail with usage rather than being ignored.",
                        "UNSUPPORTED = ('--action', '--alert-once',",
                        "               '--button1', '--button1-action',",
                        "               '--button2', '--button2-action',",
                        "               '--button3', '--button3-action',",
                        "               '--icon', '--led-color', '--led-on', '--led-off',",
                        "               '--media-next', '--media-pause', '--media-play',",
                        "               '--media-previous', '--on-delete', '--type')",
                        "VALUE_OPTIONS = {'--content': 'content', '--title': 'title',",
                        "                 '--id': 'id', '--channel': 'channel',",
                        "                 '--group': 'group', '--priority': 'priority',",
                        "                 '--vibrate': 'vibrate_pattern',",
                        "                 '--image-path': 'image_path'}",
                        "FLAG_OPTIONS = ('--ongoing', '--sound')",
                        "SHORT_OPTIONS = {'-c': '--content', '-t': '--title', '-i': '--id'}",
                        "",
                        "",
                        "def has_control_chars(text):",
                        "    return any(ord(char) < 32 or 127 <= ord(char) < 160",
                        "               for char in text)",
                        "",
                        "",
                        "def stage_text(text):",
                        "    fd, staging = tempfile.mkstemp(prefix='nusadesk-text-',",
                        "                                   dir='/tmp')",
                        "    with os.fdopen(fd, 'w', encoding='utf-8') as handle:",
                        "        handle.write(text)",
                        "    return staging",
                        "",
                        "",
                        "def read_stdin(timeout):",
                        "    try:",
                        "        ready, _, _ = select.select([sys.stdin], [], [], timeout)",
                        "        if not ready:",
                        "            return ''",
                        "        return os.read(sys.stdin.fileno(), 65536).decode(",
                        "            'utf-8', 'replace')",
                        "    except OSError:",
                        "        return ''",
                        "",
                        "",
                        "def parse(argv):",
                        "    values = {}",
                        "    flags = set()",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        arg = argv[index]",
                        "        if arg in ('-h', '--help'):",
                        "            return 'help', None, None",
                        "        if arg == '--help-actions':",
                        "            return 'actions', None, None",
                        "        if arg == '--':",
                        "            index += 1",
                        "            break",
                        "        if arg.startswith('--'):",
                        "            name, separator, inline = arg.partition('=')",
                        "            if name in UNSUPPORTED:",
                        "                raise tc.CliError('unsupported flag: ' + name)",
                        "            if name in FLAG_OPTIONS:",
                        "                if separator:",
                        "                    raise tc.CliError(name + ' takes no value')",
                        "                flags.add(name[2:])",
                        "                index += 1",
                        "                continue",
                        "            if name not in VALUE_OPTIONS:",
                        "                raise tc.CliError('illegal option ' + name)",
                        "            if separator:",
                        "                value = inline",
                        "            else:",
                        "                index += 1",
                        "                if index >= len(argv):",
                        "                    raise tc.CliError(name + ' needs a value')",
                        "                value = argv[index]",
                        "            values[VALUE_OPTIONS[name]] = value",
                        "            index += 1",
                        "            continue",
                        "        if arg.startswith('-') and arg != '-':",
                        "            option = arg[:2]",
                        "            if option not in SHORT_OPTIONS:",
                        "                raise tc.CliError('illegal option ' + arg)",
                        "            if len(arg) > 2:",
                        "                value = arg[2:]",
                        "            else:",
                        "                index += 1",
                        "                if index >= len(argv):",
                        "                    raise tc.CliError(option + ' needs a value')",
                        "                value = argv[index]",
                        "            values[VALUE_OPTIONS[SHORT_OPTIONS[option]]] = value",
                        "            index += 1",
                        "            continue",
                        "        raise tc.CliError('too many arguments')",
                        "    if index < len(argv):",
                        "        raise tc.CliError('too many arguments')",
                        "    return None, values, flags",
                        "",
                        "",
                        "def main(argv):",
                        "    action, values, flags = parse(argv)",
                        "    if action == 'help':",
                        "        print('Usage: termux-notification [options]')",
                        "        print('Display a system notification. Content text is')",
                        "        print('specified using -c/--content or read from stdin.')",
                        "        return 0",
                        "    if action == 'actions':",
                        "        print('Notification actions and buttons execute inside the')",
                        "        print('Termux app; they are not supported by NusaDesk.')",
                        "        return 0",
                        "    if 'ongoing' in flags and 'id' not in values:",
                        "        raise tc.CliError('ongoing notifications without an ID are'",
                        "                          ' not removable; set an id with --id')",
                        "    params = {}",
                        "    for key in ('id', 'title', 'channel', 'group'):",
                        "        if key in values:",
                        "            params[key] = values[key]",
                        "    if 'priority' in values:",
                        "        if values['priority'] not in PRIORITIES:",
                        "            raise tc.CliError('unsupported priority: '",
                        "                              + values['priority'])",
                        "        params['priority'] = values['priority']",
                        "    if 'ongoing' in flags:",
                        "        params['ongoing'] = True",
                        "    if 'sound' in flags:",
                        "        params['sound'] = True",
                        "    if 'vibrate_pattern' in values:",
                        "        parts = values['vibrate_pattern'].split(',')",
                        "        if not all(part.isdigit() for part in parts):",
                        "            raise tc.CliError('bad vibrate pattern: '",
                        "                              + values['vibrate_pattern'])",
                        "        params['vibrate'] = True",
                        "    if 'content' in values:",
                        "        content = values['content'].rstrip('\\n')",
                        "    else:",
                        "        content = read_stdin(3.0).rstrip('\\n')",
                        "    staging = []",
                        "    try:",
                        "        if content:",
                        "            if len(content) > MAX_INLINE_CHARS \\",
                        "                    or has_control_chars(content):",
                        "                staged = stage_text(content)",
                        "                params['content_path'] = staged",
                        "                staging.append(staged)",
                        "            else:",
                        "                params['content'] = content",
                        "        if 'image_path' in values:",
                        "            image = values['image_path']",
                        "            if not os.path.isfile(image):",
                        "                raise tc.CliError('image not found: ' + image)",
                        "            fd, staged_image = tempfile.mkstemp(",
                        "                prefix='nusadesk-notification-image-', dir='/tmp')",
                        "            os.close(fd)",
                        "            shutil.copyfile(image, staged_image)",
                        "            staging.append(staged_image)",
                        "            params['image_path'] = staged_image",
                        "        tc.bridge_call('notification.post', params)",
                        "    finally:",
                        "        for path in staging:",
                        "            try:",
                        "                os.unlink(path)",
                        "            except OSError:",
                        "                pass",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-notification [options]` - post a notification;",
                        "  `-c/--content` (or stdin), `-t/--title`, `-i/--id`,",
                        "  `--channel`, `--group`, `--priority min|low|default|high|max`,",
                        "  `--ongoing`, `--sound`, `--vibrate pattern` (pattern accepted,",
                        "  a default vibration is used), `--image-path` (staged).",
                        "  Upstream's action/button/media/LED/icon/`--type` flags are not",
                        "  supported and fail with usage"));
    }

    private static TermuxCommand notificationChannel() {
        return new TermuxCommand(
                "termux-notification-channel",
                String.join("\n",
                        "def main(argv):",
                        "    args = list(argv)",
                        "    if args == ['-h']:",
                        "        print('Usage: termux-notification-channel -d channel-id')",
                        "        print('       termux-notification-channel channel-id name')",
                        "        print('Create or delete a notification channel.')",
                        "        return 0",
                        "    if args and args[0] == '-d':",
                        "        if len(args) != 2:",
                        "            raise tc.CliError('usage: termux-notification-channel'",
                        "                              ' -d channel-id')",
                        "        tc.bridge_call('notification.channel',",
                        "                       {'id': args[1], 'delete': True})",
                        "        print('Deleted channel with id \"' + args[1] + '\".')",
                        "        return 0",
                        "    if len(args) != 2:",
                        "        raise tc.CliError('usage: termux-notification-channel'",
                        "                          ' channel-id channel-name')",
                        "    tc.bridge_call('notification.channel',",
                        "                   {'id': args[0], 'name': args[1]})",
                        "    print('Created channel with id \"' + args[0]",
                        "          + '\" and name \"' + args[1] + '\".')",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-notification-channel [-d] id [name]` - create",
                        "  (`id name`) or delete (`-d id`) a notification channel;",
                        "  prints upstream's confirmation line"));
    }

    private static TermuxCommand notificationList() {
        return new TermuxCommand(
                "termux-notification-list",
                String.join("\n",
                        "import datetime",
                        "import json",
                        "",
                        "",
                        "def to_termux(reading):",
                        "    tc.warn_truncated('termux-notification-list', reading)",
                        "    rows = json.loads(reading.get('notifications_json', '[]'))",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        entry = {",
                        "            'id': int(row.get('id', 0)),",
                        "            'tag': str(row.get('tag', '')),",
                        "            'packageName': str(row.get('package', '')),",
                        "            'title': str(row.get('title', '')),",
                        "            'content': str(row.get('content', '')),",
                        "        }",
                        "        posted_ms = row.get('posted_ms')",
                        "        if isinstance(posted_ms, int) and posted_ms > 0:",
                        "            entry['when'] = datetime.datetime.fromtimestamp(",
                        "                posted_ms / 1000).strftime('%Y-%m-%d %H:%M:%S')",
                        "        result.append(entry)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv == ['-h']:",
                        "        print('Usage: termux-notification-list')",
                        "        print('Show the list of currently shown notifications.')",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-notification-list')",
                        "    return tc.emit(to_termux(tc.call('notification.list')))",
                        ""),
                Arrays.asList(
                        "- `termux-notification-list` - currently shown",
                        "  notifications as a JSON array; fields `id`, `tag`,",
                        "  `packageName`, `title`, `content`, `when` (upstream's",
                        "  `key`, `group`, `lines` are not populated). Requires",
                        "  notification access in Settings; bounded to 50 rows"));
    }

    private static TermuxCommand notificationRemove() {
        return new TermuxCommand(
                "termux-notification-remove",
                String.join("\n",
                        "def main(argv):",
                        "    if argv == ['-h']:",
                        "        print('Usage: termux-notification-remove notification-id')",
                        "        print('Remove a notification previously shown with')",
                        "        print('termux-notification --id.')",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError('usage: termux-notification-remove'",
                        "                          ' notification-id')",
                        "    tc.bridge_call('notification.remove', {'id': argv[0]})",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-notification-remove id` - cancel a notification",
                        "  posted with `termux-notification --id id`"));
    }
}
