package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The storage/share domain Termux-compat commands (wave 2, W2d): the nine
 * {@code termux-saf-*} clients plus {@code termux-storage-get},
 * {@code termux-share}, {@code termux-media-scan}, {@code termux-wallpaper},
 * and {@code termux-download}.
 *
 * <p>Each body is a thin flag-to-method mapping onto {@code StorageModule}'s
 * bridge methods through the shared {@code termux_compat} runtime. File
 * payloads follow the staging rule: the guest writes or reads a file inside
 * the rootfs ({@code /tmp}) and passes that guest path; only the guest moves
 * results to the user's destination, because a workspace bind mount is
 * visible only to the guest.</p>
 */
public final class TermuxStorageCommands {

    private TermuxStorageCommands() {
    }

    /** The storage domain commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                safManagedir(),
                safDirs(),
                safLs(),
                safStat(),
                safCreate(),
                safMkdir(),
                safRead(),
                safWrite(),
                safRm(),
                storageGet(),
                share(),
                mediaScan(),
                wallpaper(),
                download()));
    }

    private static TermuxCommand safManagedir() {
        return new TermuxCommand(
                "termux-saf-managedir",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-managedir'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError(USAGE)",
                        "    # The picker waits for the user; give it a generous",
                        "    # socket timeout (the host-side bound is 120 s).",
                        "    reading = tc.bridge_call('saf.manage', timeout=150.0)",
                        "    print(reading.get('uri', ''))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-managedir` - opens the system folder",
                        "  picker and persists a SAF grant for the chosen tree;",
                        "  prints the tree URI to use with the other",
                        "  `termux-saf-*` commands (empty line on cancel)"));
    }

    private static TermuxCommand safDirs() {
        return new TermuxCommand(
                "termux-saf-dirs",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-dirs'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('saf.trees')",
                        "    tc.warn_truncated('termux-saf-dirs', reading)",
                        "    print(reading.get('entries_json', '[]'))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-dirs` - JSON array of the granted trees,",
                        "  one `{name, type, uri, last_modified}` object per",
                        "  entry, like `termux-saf-ls`"));
    }

    private static TermuxCommand safLs() {
        return new TermuxCommand(
                "termux-saf-ls",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-ls folder-uri'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('saf.list', {'uri': argv[0]})",
                        "    tc.warn_truncated('termux-saf-ls', reading)",
                        "    print(reading.get('entries_json', '[]'))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-ls FOLDER-URI` - JSON array of child",
                        "  entries `{name, type, uri, last_modified, length?}`;",
                        "  `length` is present for files, absent for folders.",
                        "  Large listings are bounded and reported as truncated",
                        "  on stderr"));
    }

    private static TermuxCommand safStat() {
        return new TermuxCommand(
                "termux-saf-stat",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-stat uri'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('saf.stat', {'uri': argv[0]})",
                        "    entry = reading.get('entry_json')",
                        "    if entry:",
                        "        print(entry)",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-stat URI` - one JSON entry object like",
                        "  `termux-saf-ls` emits; a document that no longer",
                        "  resolves prints nothing, like upstream"));
    }

    private static TermuxCommand safCreate() {
        return new TermuxCommand(
                "termux-saf-create",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-create [-t mime-type] folder-uri name'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    mime = ''",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-t' and index + 1 < len(argv):",
                        "            mime = argv[index + 1]",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    if len(args) != 2:",
                        "        raise tc.CliError(USAGE)",
                        "    params = {'uri': args[0], 'name': args[1]}",
                        "    if mime:",
                        "        params['mime'] = mime",
                        "    print(tc.bridge_call('saf.create', params).get('uri', ''))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-create [-t MIME] FOLDER-URI NAME` -",
                        "  creates a document in a granted folder and prints",
                        "  its URI; default mime `application/octet-stream`"));
    }

    private static TermuxCommand safMkdir() {
        return new TermuxCommand(
                "termux-saf-mkdir",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-mkdir parent-uri name'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 2:",
                        "        raise tc.CliError(USAGE)",
                        "    params = {'uri': argv[0], 'name': argv[1],",
                        "              'mime': 'vnd.android.document/directory'}",
                        "    print(tc.bridge_call('saf.create', params).get('uri', ''))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-saf-mkdir PARENT-URI NAME` - creates a",
                        "  directory in a granted tree and prints its URI"));
    }

    private static TermuxCommand safRead() {
        return new TermuxCommand(
                "termux-saf-read",
                String.join("\n",
                        "import base64",
                        "",
                        "USAGE = 'usage: termux-saf-read uri'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    offset = 0",
                        "    while True:",
                        "        reading = tc.bridge_call('saf.read',",
                        "                                 {'uri': argv[0], 'offset': offset})",
                        "        chunk = base64.b64decode(reading.get('data', ''))",
                        "        sys.stdout.buffer.write(chunk)",
                        "        sys.stdout.buffer.flush()",
                        "        if reading.get('truncated') is not True or not chunk:",
                        "            return 0",
                        "        offset += len(chunk)",
                        ""),
                Arrays.asList(
                        "- `termux-saf-read URI` - writes the document bytes",
                        "  to stdout, paged through the bridge in bounded",
                        "  chunks until the whole file is emitted"));
    }

    private static TermuxCommand safWrite() {
        return new TermuxCommand(
                "termux-saf-write",
                String.join("\n",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "",
                        "USAGE = 'usage: termux-saf-write uri'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    fd, staging = tempfile.mkstemp(prefix='nusadesk-saf-',",
                        "                                 dir='/tmp')",
                        "    try:",
                        "        with os.fdopen(fd, 'wb') as out:",
                        "            shutil.copyfileobj(sys.stdin.buffer, out)",
                        "        tc.bridge_call('saf.write',",
                        "                       {'uri': argv[0], 'path': staging})",
                        "        return 0",
                        "    finally:",
                        "        try:",
                        "            os.unlink(staging)",
                        "        except OSError:",
                        "            pass",
                        ""),
                Arrays.asList(
                        "- `termux-saf-write URI` - truncates the document and",
                        "  writes stdin into it; creates nothing (use",
                        "  `termux-saf-create` first)"));
    }

    private static TermuxCommand safRm() {
        return new TermuxCommand(
                "termux-saf-rm",
                String.join("\n",
                        "USAGE = 'usage: termux-saf-rm uri'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('saf.remove', {'uri': argv[0]})",
                        "    return 0 if reading.get('deleted') is True else 1",
                        ""),
                Arrays.asList(
                        "- `termux-saf-rm URI` - deletes a document; exit 0",
                        "  deleted, 1 not deleted or a bridge error"));
    }

    private static TermuxCommand storageGet() {
        return new TermuxCommand(
                "termux-storage-get",
                String.join("\n",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "",
                        "USAGE = 'usage: termux-storage-get output-file'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if len(argv) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    destination = os.path.abspath(argv[0])",
                        "    fd, staging = tempfile.mkstemp(prefix='nusadesk-get-',",
                        "                                 dir='/tmp')",
                        "    os.close(fd)",
                        "    try:",
                        "        reading = tc.bridge_call('storage.get',",
                        "                                 {'path': staging}, timeout=150.0)",
                        "        if reading.get('copied') is True:",
                        "            try:",
                        "                shutil.move(staging, destination)",
                        "            except OSError:",
                        "                raise tc.CliError(",
                        "                    'cannot write output file: ' + destination)",
                        "        return 0",
                        "    finally:",
                        "        try:",
                        "            os.unlink(staging)",
                        "        except OSError:",
                        "            pass",
                        ""),
                Arrays.asList(
                        "- `termux-storage-get OUTPUT-FILE` - opens the system",
                        "  file picker and writes the picked document to",
                        "  OUTPUT-FILE; a dismissed picker exits 0 with no",
                        "  file, like upstream"));
    }

    private static TermuxCommand share() {
        return new TermuxCommand(
                "termux-share",
                String.join("\n",
                        "import mimetypes",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "",
                        "USAGE = ('usage: termux-share [-a action] [-c content-type] '",
                        "         '[-d] [-t title] [file]')",
                        "ACTIONS = ('edit', 'send', 'view')",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    params = {}",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-d':",
                        "            params['default_receiver'] = True",
                        "            index += 1",
                        "        elif flag in ('-a', '-c', '-t') and index + 1 < len(argv):",
                        "            value = argv[index + 1]",
                        "            if flag == '-a':",
                        "                if value not in ACTIONS:",
                        "                    raise tc.CliError('unsupported action: ' + value)",
                        "                params['action'] = value",
                        "            elif flag == '-c':",
                        "                params['content_type'] = value",
                        "            else:",
                        "                params['title'] = value",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    if len(args) > 1:",
                        "        raise tc.CliError(USAGE)",
                        "    staging = None",
                        "    try:",
                        "        if args:",
                        "            source = os.path.realpath(args[0])",
                        "            if not os.path.isfile(source):",
                        "                tc.fail('termux-share', source + ' is not a file', 1)",
                        "            fd, staging = tempfile.mkstemp(",
                        "                prefix='nusadesk-share-', dir='/tmp')",
                        "            with os.fdopen(fd, 'wb') as out:",
                        "                with open(source, 'rb') as inp:",
                        "                    shutil.copyfileobj(inp, out)",
                        "            params['path'] = staging",
                        "            if 'content_type' not in params:",
                        "                # Upstream guesses the type from the extension; an",
                        "                # octet-stream share made the receiver fail to",
                        "                # open a .txt file on the S10e (2026-09-22).",
                        "                guessed = mimetypes.guess_type(source)[0]",
                        "                if guessed:",
                        "                    params['content_type'] = guessed",
                        "        else:",
                        "            text = sys.stdin.read()",
                        "            if not text:",
                        "                print('Error: Nothing to share')",
                        "                return 0",
                        "            if len(text) > 8192:",
                        "                raise tc.CliError('shared text exceeds 8192 characters')",
                        "            params['text'] = text",
                        "        tc.bridge_call('share.send', params, timeout=150.0)",
                        "        return 0",
                        "    finally:",
                        "        if staging is not None:",
                        "            try:",
                        "                os.unlink(staging)",
                        "            except OSError:",
                        "                pass",
                        ""),
                Arrays.asList(
                        "- `termux-share [-a edit|send|view] [-c MIME] [-d]`",
                        "  `[-t TITLE] [FILE]` - shares a file or stdin text",
                        "  through the system sheet. A file is staged into the",
                        "  public `Downloads` collection so the receiver gets a",
                        "  readable `content://` URI (the app declares no file",
                        "  provider), so a copy stays visible there"));
    }

    private static TermuxCommand mediaScan() {
        return new TermuxCommand(
                "termux-media-scan",
                String.join("\n",
                        "import os",
                        "",
                        "USAGE = 'usage: termux-media-scan [-r] [-v] file [file...]'",
                        "MAX_PATHS = 64",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    recursive = False",
                        "    verbose = False",
                        "    args = []",
                        "    for flag in argv:",
                        "        if flag == '-r':",
                        "            recursive = True",
                        "        elif flag == '-v':",
                        "            verbose = True",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "    if not args:",
                        "        raise tc.CliError(USAGE)",
                        "    paths = []",
                        "    for arg in args:",
                        "        path = (os.path.realpath(arg) if os.path.exists(arg)",
                        "                else os.path.abspath(arg))",
                        "        if recursive and os.path.isdir(path):",
                        "            for root, _dirs, files in os.walk(path):",
                        "                for name in files:",
                        "                    paths.append(os.path.join(root, name))",
                        "        else:",
                        "            paths.append(path)",
                        "    if len(paths) > MAX_PATHS:",
                        "        raise tc.CliError('too many paths; the bridge accepts'",
                        "                          ' at most ' + str(MAX_PATHS))",
                        "    reading = tc.bridge_call('media.scan', {",
                        "        'paths': '\\n'.join(paths),",
                        "        'recursive': recursive,",
                        "        'verbose': verbose})",
                        "    if verbose:",
                        "        for path in paths:",
                        "            print(path)",
                        "    print('Finished scanning %d file(s)'",
                        "          % int(reading.get('scanned', 0)))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-media-scan [-r] [-v] FILE...` - registers",
                        "  files with the media provider. Only files under the",
                        "  workspace (`~/nusadesk`) are indexable — the media",
                        "  provider cannot read app-private rootfs files, and",
                        "  the summary prints the provider-confirmed count, so",
                        "  `Finished scanning 0 file(s)` is an honest answer,",
                        "  not a crash"));
    }

    private static TermuxCommand wallpaper() {
        return new TermuxCommand(
                "termux-wallpaper",
                String.join("\n",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "",
                        "USAGE = 'usage: termux-wallpaper -f file | -u url [-l]'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    path = None",
                        "    url = None",
                        "    lockscreen = False",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-l':",
                        "            lockscreen = True",
                        "            index += 1",
                        "        elif flag in ('-f', '-u') and index + 1 < len(argv):",
                        "            if flag == '-f':",
                        "                path = argv[index + 1]",
                        "            else:",
                        "                url = argv[index + 1]",
                        "            index += 2",
                        "        else:",
                        "            raise tc.CliError(USAGE)",
                        "    if (path is None) == (url is None):",
                        "        raise tc.CliError('specify either -f or -u, but not both')",
                        "    params = {'lockscreen': lockscreen}",
                        "    staging = None",
                        "    try:",
                        "        if path is not None:",
                        "            source = os.path.realpath(path)",
                        "            if not os.path.isfile(source):",
                        "                tc.fail('termux-wallpaper',",
                        "                        source + ' is not a file', 1)",
                        "            fd, staging = tempfile.mkstemp(",
                        "                prefix='nusadesk-wallpaper-', dir='/tmp')",
                        "            with os.fdopen(fd, 'wb') as out:",
                        "                with open(source, 'rb') as inp:",
                        "                    shutil.copyfileobj(inp, out)",
                        "            params['path'] = staging",
                        "        else:",
                        "            params['url'] = url",
                        "        tc.bridge_call('wallpaper.set', params)",
                        "        print('Wallpaper set successfully!')",
                        "        return 0",
                        "    finally:",
                        "        if staging is not None:",
                        "            try:",
                        "                os.unlink(staging)",
                        "            except OSError:",
                        "                pass",
                        ""),
                Arrays.asList(
                        "- `termux-wallpaper -f FILE | -u URL [-l]` - sets the",
                        "  home-screen wallpaper, or the lock screen with `-l`",
                        "  (upstream semantics: one target, not both). `-u`",
                        "  takes an http/https image resource; the download is",
                        "  bounded and must report an `image/*` content type"));
    }

    private static TermuxCommand download() {
        return new TermuxCommand(
                "termux-download",
                String.join("\n",
                        "import os",
                        "",
                        "USAGE = ('usage: termux-download [-d description] '",
                        "         '[-t title] [-p path] url-to-download')",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    params = {}",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-d', '-t', '-p') and index + 1 < len(argv):",
                        "            value = argv[index + 1]",
                        "            if flag == '-d':",
                        "                params['description'] = value",
                        "            elif flag == '-t':",
                        "                params['title'] = value",
                        "            else:",
                        "                params['name'] = os.path.basename(value)",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    if len(args) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    params['url'] = args[0]",
                        "    tc.bridge_call('download.request', params)",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-download [-d DESC] [-t TITLE] [-p PATH] URL`",
                        "  - enqueues an http/https URL with the system",
                        "  download manager into the public `Download`",
                        "  directory (`-p` supplies only the destination file",
                        "  name, not a full path); silent on success, like",
                        "  upstream"));
    }
}
