package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The USB Termux-compat command (wave 2, W2g): {@code termux-usb}.
 *
 * <p>A compatibility wrapper over the existing USB pass-through slice
 * (ADR-0041): {@code -l} renders {@code usb.list} in the upstream shape (a
 * JSON array of usbfs device paths); {@code -r}/{@code -e} open the device
 * through {@code nusadesk-usb}'s {@code open_device} — the same
 * {@code usb.open} + SCM_RIGHTS fd delivery, never a second transport. The
 * callback contract is upstream's: the command string is word-split like
 * {@code termux-callback}'s unquoted expansion, the descriptor arrives as
 * the last argv entry, or as {@code TERMUX_USB_FD} under {@code -E}, and the
 * callback runs directly (no shell). Unlike upstream, the
 * {@code vendorId productId} pair is honoured (upstream sends the extras but
 * its app side only ever looked the device path up); bare {@code
 * termux-usb <device>} without {@code -r} stays a passive check, reporting
 * "granted" only when descriptor strings are readable — it never pops the
 * consent dialog.</p>
 */
public final class TermuxUsbCommand {

    private TermuxUsbCommand() {
    }

    /** The USB domain commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                usb()));
    }

    private static TermuxCommand usb() {
        return new TermuxCommand(
                "termux-usb",
                String.join("\n",
                        "import importlib.machinery",
                        "import importlib.util",
                        "import json",
                        "import os",
                        "import shlex",
                        "import subprocess",
                        "",
                        "USAGE = ('Usage: termux-usb [-l | [-r] [-E] [-e command]'",
                        "         + ' [device | vendorId productId]]'",
                        "         + '\\nList or access USB devices. Devices cannot be'",
                        "         + ' accessed directly,\\n                 only using'",
                        "         + ' termux-usb.'",
                        "         + '\\n  -l           list available devices'",
                        "         + '\\n  -r           show permission request dialog'",
                        "         + ' if necessary'",
                        "         + '\\n  -e command   execute the specified command with'",
                        "         + ' a file descriptor\\n                 referring to'",
                        "         + ' the device as an argument (unless -E'",
                        "         + '\\n                 argument is given)'",
                        "         + '\\n  -E           transfer file descriptor as'",
                        "         + ' TERMUX_USB_FD env var\\n                 instead'",
                        "         + ' of as command line argument')",
                        "",
                        "HELPER_PATH = '/usr/local/bin/nusadesk-usb'",
                        "",
                        "# The pass-through's own messages, mapped onto the texts",
                        "# upstream's termux-usb printed for the same outcomes.",
                        "OPEN_MESSAGES = {",
                        "    'usb-device-not-found': 'No such device.',",
                        "    'usb-permission-denied': 'Permission denied.',",
                        "    'usb-permission-timeout': 'Permission request timeout.',",
                        "    'usb-socket-failed': 'Open device failed.',",
                        "    'usb-open-failed': 'Open device failed.',",
                        "}",
                        "",
                        "",
                        "def load_helper():",
                        "    # Reuse the installed nusadesk-usb CLI as a module: its",
                        "    # open_device() owns the usb.open call and the SCM_RIGHTS",
                        "    # fd receive, so this command never reimplements delivery.",
                        "    try:",
                        "        loader = importlib.machinery.SourceFileLoader(",
                        "            'nusadesk_usb', HELPER_PATH)",
                        "        spec = importlib.util.spec_from_loader(",
                        "            'nusadesk_usb', loader)",
                        "        module = importlib.util.module_from_spec(spec)",
                        "        loader.exec_module(module)",
                        "        return module",
                        "    except (OSError, ImportError, SyntaxError) as error:",
                        "        raise tc.CliError('termux-usb: cannot load '",
                        "                          + HELPER_PATH + ': ' + str(error))",
                        "",
                        "",
                        "def list_devices():",
                        "    reading = tc.bridge_call('usb.list')",
                        "    rows = reading.get('devices')",
                        "    if not isinstance(rows, str):",
                        "        raise tc.CliError('malformed bridge response')",
                        "    devices = json.loads(rows)",
                        "    if not isinstance(devices, list):",
                        "        raise tc.CliError('malformed bridge response')",
                        "    return devices",
                        "",
                        "",
                        "def resolve(args, devices):",
                        "    # Upstream takes one usbfs path or a vendorId/productId",
                        "    # pair; the pair is honoured here even though upstream's",
                        "    # app side only ever matched the path.",
                        "    if len(args) == 1:",
                        "        for device in devices:",
                        "            if device.get('name') == args[0]:",
                        "                return (device.get('vendorId'),",
                        "                        device.get('productId'), device)",
                        "        print('No such device.')",
                        "        return None",
                        "    pair = []",
                        "    for part in args:",
                        "        text = part[2:] if part.lower().startswith('0x') else part",
                        "        try:",
                        "            value = int(text, 16)",
                        "        except ValueError:",
                        "            raise tc.CliError('termux-usb: bad id: ' + str(part))",
                        "        if value < 0 or value > 0xffff:",
                        "            raise tc.CliError('termux-usb: bad id: ' + str(part))",
                        "        pair.append(value)",
                        "    for device in devices:",
                        "        if (device.get('vendorId') == pair[0]",
                        "                and device.get('productId') == pair[1]):",
                        "            return pair[0], pair[1], device",
                        "    print('No such device.')",
                        "    return None",
                        "",
                        "",
                        "def open_fd(helper, vendor_id, product_id):",
                        "    try:",
                        "        return helper.open_device(vendor_id, product_id)",
                        "    except Exception as error:",
                        "        text = str(error)",
                        "        code = text.split(':', 1)[0].strip()",
                        "        message = OPEN_MESSAGES.get(code)",
                        "        if message is None:",
                        "            tc.warn('termux-usb', text)",
                        "            message = 'Open device failed.'",
                        "        print(message)",
                        "        return None",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    list_mode = False",
                        "    request = False",
                        "    export_fd = False",
                        "    command = None",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-l':",
                        "            list_mode = True",
                        "            index += 1",
                        "        elif flag == '-r':",
                        "            request = True",
                        "            index += 1",
                        "        elif flag == '-E':",
                        "            export_fd = True",
                        "            index += 1",
                        "        elif flag == '-e':",
                        "            if index + 1 >= len(argv):",
                        "                raise tc.CliError(USAGE)",
                        "            command = argv[index + 1]",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            print('termux-usb: illegal option ' + flag)",
                        "            return 1",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    if list_mode:",
                        "        if args or command is not None:",
                        "            print('termux-usb: too many arguments')",
                        "            return 1",
                        "        devices = list_devices()",
                        "        print(json.dumps([device.get('name')",
                        "                          for device in devices]))",
                        "        return 0",
                        "    if not args:",
                        "        print('termux-usb: missing -l or device path')",
                        "        return 1",
                        "    if len(args) > 2:",
                        "        print('termux-usb: too many arguments')",
                        "        return 1",
                        "    devices = list_devices()",
                        "    resolved = resolve(args, devices)",
                        "    if resolved is None:",
                        "        return 1",
                        "    vendor_id, product_id, entry = resolved",
                        "    if vendor_id is None or product_id is None:",
                        "        print('No such device.')",
                        "        return 1",
                        "    helper = load_helper()",
                        "    if command is None:",
                        "        # Upstream's 'permission' action: bare termux-usb is a",
                        "        # passive check (descriptor strings read only under a",
                        "        # grant), -r exercises the real consent flow.",
                        "        if not request:",
                        "            if (entry is not None",
                        "                    and (entry.get('manufacturer') is not None",
                        "                         or entry.get('product') is not None)):",
                        "                print('Permission granted.')",
                        "                return 0",
                        "            print('Permission denied.')",
                        "            return 1",
                        "        fd = open_fd(helper, vendor_id, product_id)",
                        "        if fd is None:",
                        "            return 1",
                        "        os.close(fd)",
                        "        print('Permission granted.')",
                        "        return 0",
                        "    fd = open_fd(helper, vendor_id, product_id)",
                        "    if fd is None:",
                        "        return 1",
                        "    try:",
                        "        words = shlex.split(command)",
                        "        if not words:",
                        "            raise tc.CliError('termux-usb: empty -e command')",
                        "        if export_fd:",
                        "            env = dict(os.environ)",
                        "            env['TERMUX_USB_FD'] = str(fd)",
                        "            completed = subprocess.run(words, env=env,",
                        "                                       pass_fds=(fd,))",
                        "        else:",
                        "            completed = subprocess.run(words + [str(fd)],",
                        "                                       pass_fds=(fd,))",
                        "    finally:",
                        "        os.close(fd)",
                        "    code = completed.returncode",
                        "    if code < 0:",
                        "        return 128 + (-code)",
                        "    return code",
                        ""),
                Arrays.asList(
                        "- `termux-usb -l` - JSON array of attached usbfs",
                        "  device paths, upstream's shape (the devices come",
                        "  from `usb.list`).",
                        "- `termux-usb [-r] DEVICE | VID PID` - permission",
                        "  path: bare is a passive check (never shows the",
                        "  dialog), `-r` runs the consent flow; ids are hex",
                        "  as lsusb prints them.",
                        "- `termux-usb -e CMD [-E] DEVICE | VID PID` - opens",
                        "  the device through `nusadesk-usb`'s SCM_RIGHTS",
                        "  delivery and runs CMD word-split (upstream's",
                        "  unquoted `$TERMUX_CALLBACK` expansion): the fd is",
                        "  the last argv entry, or `TERMUX_USB_FD` under -E.",
                        "  The callback's own exit status is returned.",
                        "- Outcome texts mirror upstream (`No such device.`,",
                        "  `Permission denied.`, `Permission request timeout.`,",
                        "  `Open device failed.`); the typed `usb-*` codes",
                        "  stay on stderr."));
    }
}
