package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The speech/dialog domain Termux-compat commands (wave 2, W2b):
 * {@code termux-tts-engines}, {@code termux-tts-speak},
 * {@code termux-speech-to-text}, and {@code termux-dialog}.
 *
 * <p>Each body is a thin flag-to-method mapping onto {@code SpeechModule}
 * and {@code DialogModule} through the shared {@code termux_compat}
 * runtime. {@code termux-tts-speak} stages over-long text into the guest
 * {@code /tmp} (inside the rootfs, where {@code tts.speak}'s
 * {@code text_path} can reach it) like the storage commands do. The dialog
 * command speaks the brief's flat flag set ({@code -t -i -p -w -l -n -m
 * -s -c -f}); {@code -w} or a positional argument picks the upstream
 * widget, {@code -l}/{@code -f} supply the values list, and the upstream
 * {@code {"code","text",...}} JSON shape is reassembled from the flat
 * bridge fields.</p>
 */
public final class TermuxSpeechCommands {

    private TermuxSpeechCommands() {
    }

    /** The speech domain commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                ttsEngines(),
                ttsSpeak(),
                speechToText(),
                dialog()));
    }

    private static TermuxCommand ttsEngines() {
        return new TermuxCommand(
                "termux-tts-engines",
                String.join("\n",
                        "USAGE = 'usage: termux-tts-engines'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('tts.engines', timeout=30.0)",
                        "    print(reading.get('engines_json', '[]'))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-tts-engines` - JSON array of the",
                        "  installed TTS engines, one `{name, label,",
                        "  default}` object per entry like upstream"));
    }

    private static TermuxCommand ttsSpeak() {
        return new TermuxCommand(
                "termux-tts-speak",
                String.join("\n",
                        "import os",
                        "import tempfile",
                        "",
                        "USAGE = ('usage: termux-tts-speak [-e engine] [-l language]'",
                        "         ' [-n region] [-v variant] [-p pitch] [-r rate]'",
                        "         ' [-s stream] [text-to-speak]')",
                        "STREAMS = {'ALARM': 'alarm', 'MUSIC': 'music',",
                        "           'NOTIFICATION': 'notification', 'RING': 'ring',",
                        "           'SYSTEM': 'system', 'VOICE_CALL': 'call'}",
                        "INLINE_MAX = 8192",
                        "STAGED_MAX = 32768",
                        "",
                        "",
                        "def voice_factor(flag, value):",
                        "    try:",
                        "        number = float(value)",
                        "    except ValueError:",
                        "        raise tc.CliError(flag + ' expects a decimal, got: ' + value)",
                        "    if number < 0.1 or number > 3.0:",
                        "        raise tc.CliError(flag + ' must be between 0.1 and 3.0')",
                        "    return value",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    params = {}",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-e', '-l', '-n', '-v', '-p', '-r', '-s'):",
                        "            if index + 1 >= len(argv):",
                        "                raise tc.CliError(USAGE)",
                        "            value = argv[index + 1]",
                        "            if flag == '-e':",
                        "                params['engine'] = value",
                        "            elif flag == '-l':",
                        "                params['language'] = value",
                        "            elif flag == '-n':",
                        "                params['region'] = value",
                        "            elif flag == '-v':",
                        "                params['variant'] = value",
                        "            elif flag == '-p':",
                        "                params['pitch'] = voice_factor('-p', value)",
                        "            elif flag == '-r':",
                        "                params['rate'] = voice_factor('-r', value)",
                        "            else:",
                        "                stream = STREAMS.get(value)",
                        "                if stream is None:",
                        "                    raise tc.CliError('unsupported stream: ' + value)",
                        "                params['stream'] = stream",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    text = ' '.join(args) if args else sys.stdin.read()",
                        "    staging = None",
                        "    try:",
                        "        if len(text) > STAGED_MAX:",
                        "            raise tc.CliError(",
                        "                'text exceeds ' + str(STAGED_MAX) + ' characters')",
                        "        if len(text) > INLINE_MAX:",
                        "            # Long text rides a staged file inside the",
                        "            # rootfs instead of the bounded params frame.",
                        "            fd, staging = tempfile.mkstemp(",
                        "                prefix='nusadesk-tts-', dir='/tmp')",
                        "            with os.fdopen(fd, 'w', encoding='utf-8') as out:",
                        "                out.write(text)",
                        "            params['text_path'] = staging",
                        "        else:",
                        "            params['text'] = text",
                        "        tc.bridge_call('tts.speak', params, timeout=320.0)",
                        "        return 0",
                        "    finally:",
                        "        if staging is not None:",
                        "            try:",
                        "                os.unlink(staging)",
                        "            except OSError:",
                        "                pass",
                        ""),
                Arrays.asList(
                        "- `termux-tts-speak [-e ENGINE] [-l LANG] [-n REGION]`",
                        "  `[-v VARIANT] [-p PITCH] [-r RATE] [-s STREAM]`",
                        "  `[TEXT]` - speaks the argument (or stdin) through",
                        "  the system TTS engine and exits after the last",
                        "  utterance finishes. `STREAM` is one of `ALARM`,",
                        "  `MUSIC` (default), `NOTIFICATION`, `RING`,",
                        "  `SYSTEM`, `VOICE_CALL`; `PITCH`/`RATE` are decimals",
                        "  in 0.1-3.0 (1.0 normal). Text over 8192 chars is",
                        "  staged via `/tmp` (32768 chars max); speech beyond",
                        "  the 300 s engine bound answers `tts-timeout`"));
    }

    private static TermuxCommand speechToText() {
        return new TermuxCommand(
                "termux-speech-to-text",
                String.join("\n",
                        "import json",
                        "",
                        "USAGE = 'usage: termux-speech-to-text [-p]'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    progress = '-p' in argv",
                        "    argv = [arg for arg in argv if arg != '-p']",
                        "    if argv:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('speech.recognize', {},",
                        "                             timeout=150.0)",
                        "    if progress:",
                        "        for match in json.loads(",
                        "                reading.get('matches_json', '[]')):",
                        "            print(match)",
                        "    else:",
                        "        print(reading.get('text', ''))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-speech-to-text [-p]` - listens once while",
                        "  the app is foreground and prints the best final",
                        "  hypothesis (empty line when nothing matched, like",
                        "  upstream). The bridge returns a single response,",
                        "  so partial results cannot stream: `-p` prints the",
                        "  final alternatives, one per line, instead of the",
                        "  partial stream upstream shows. Needs the",
                        "  `RECORD_AUDIO` grant (`permission.request`);",
                        "  cancel/timeout surface as `speech-*` errors"));
    }

    private static TermuxCommand dialog() {
        return new TermuxCommand(
                "termux-dialog",
                String.join("\n",
                        "import json",
                        "",
                        "USAGE = ('usage: termux-dialog [widget] [-t title] [-i hint]'",
                        "         ' [-p] [-m] [-n] [-w widget] [-l values] [-s] [-c]'",
                        "         ' [-f values-file]')",
                        "WIDGETS = ('checkbox', 'confirm', 'counter', 'date', 'radio',",
                        "           'sheet', 'speech', 'spinner', 'text', 'time')",
                        "LIST_WIDGETS = ('checkbox', 'radio', 'sheet', 'spinner')",
                        "TITLE_ONLY = ('counter', 'date', 'time')",
                        "",
                        "",
                        "def read_values_file(path):",
                        "    try:",
                        "        with open(path, 'r', encoding='utf-8') as handle:",
                        "            lines = handle.read().splitlines()",
                        "    except (IOError, UnicodeDecodeError):",
                        "        tc.fail('termux-dialog',",
                        "                'cannot read values file: ' + path, 2)",
                        "    # Escape commas like the upstream comma list expects.",
                        "    return ','.join(line.replace(',', '\\\\,')",
                        "                    for line in lines)",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        print('widgets: ' + ', '.join(WIDGETS))",
                        "        return 0",
                        "    opts = {}",
                        "    positional = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-t', '-i', '-w', '-l', '-f'):",
                        "            if index + 1 >= len(argv):",
                        "                raise tc.CliError(USAGE)",
                        "            opts[flag] = argv[index + 1]",
                        "            index += 2",
                        "        elif flag in ('-p', '-m', '-n', '-s', '-c'):",
                        "            opts[flag] = True",
                        "            index += 1",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            positional.append(flag)",
                        "            index += 1",
                        "    if len(positional) > 1:",
                        "        raise tc.CliError('too many arguments')",
                        "    if '-l' in opts and '-f' in opts:",
                        "        raise tc.CliError('-l and -f are mutually exclusive')",
                        "    widget = positional[0] if positional else opts.get('-w')",
                        "    if '-w' in opts and positional:",
                        "        raise tc.CliError('widget given twice')",
                        "    if opts.get('-c'):",
                        "        if widget not in (None, 'confirm'):",
                        "            raise tc.CliError('-c conflicts with widget ' + widget)",
                        "        widget = 'confirm'",
                        "    if opts.get('-s'):",
                        "        if widget not in (None, 'sheet'):",
                        "            raise tc.CliError('-s conflicts with widget ' + widget)",
                        "        widget = 'sheet'",
                        "    if widget is None:",
                        "        widget = 'text'",
                        "    if widget not in WIDGETS:",
                        "        raise tc.CliError('unsupported widget: ' + widget)",
                        "    values = opts.get('-l')",
                        "    if '-f' in opts:",
                        "        values = read_values_file(opts['-f'])",
                        "    if widget in LIST_WIDGETS:",
                        "        if not values:",
                        "            raise tc.CliError(",
                        "                \"widget '\" + widget + \"' needs -l or -f values\")",
                        "        for bad in ('-i', '-m', '-p', '-n'):",
                        "            if bad in opts:",
                        "                raise tc.CliError(",
                        "                    'invalid option ' + bad + ' for ' + widget)",
                        "    elif widget == 'text':",
                        "        if values is not None:",
                        "            raise tc.CliError('text takes no values list')",
                        "        if opts.get('-m') and opts.get('-n'):",
                        "            raise tc.CliError('-m and -n are mutually exclusive')",
                        "    elif widget in ('confirm', 'speech'):",
                        "        if values is not None:",
                        "            raise tc.CliError(",
                        "                \"'\" + widget + \"' takes no values list\")",
                        "        for bad in ('-m', '-p', '-n'):",
                        "            if bad in opts:",
                        "                raise tc.CliError(",
                        "                    'invalid option ' + bad + ' for ' + widget)",
                        "    else:",
                        "        if values is not None:",
                        "            raise tc.CliError(",
                        "                \"'\" + widget + \"' takes no values list\")",
                        "        for bad in ('-i', '-m', '-p', '-n'):",
                        "            if bad in opts:",
                        "                raise tc.CliError(",
                        "                    'invalid option ' + bad + ' for ' + widget)",
                        "    params = {'widget': widget}",
                        "    if '-t' in opts:",
                        "        params['title'] = opts['-t']",
                        "    if '-i' in opts:",
                        "        params['hint'] = opts['-i']",
                        "    if values is not None:",
                        "        params['values'] = values",
                        "    if opts.get('-p'):",
                        "        params['password'] = True",
                        "    if opts.get('-m'):",
                        "        params['multiline'] = True",
                        "    if opts.get('-n'):",
                        "        params['numeric'] = True",
                        "    reading = tc.bridge_call('dialog.show', params,",
                        "                             timeout=150.0)",
                        "    result = {'code': int(reading.get('code', -2)),",
                        "              'text': reading.get('text', '')}",
                        "    if 'index' in reading:",
                        "        result['index'] = reading['index']",
                        "    if reading.get('values_json'):",
                        "        result['values'] = json.loads(",
                        "            reading['values_json'])",
                        "    if reading.get('error'):",
                        "        result['error'] = reading['error']",
                        "    tc.print_json(result)",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-dialog [WIDGET] [-t TITLE] [-i HINT] [-p]`",
                        "  `[-m] [-n] [-w WIDGET] [-l V1,V2] [-s] [-c]`",
                        "  `[-f FILE]` - shows the upstream input widget on the",
                        "  phone and prints `{\"code\":..,\"text\":..}` JSON:",
                        "  `-1` OK, `-2` cancel/back/dismiss (exit 0 either",
                        "  way); `sheet`/`speech` picks answer `code` 0 like",
                        "  upstream; `index`/`values`/`error` appear when the",
                        "  widget produces them. `-w`/positional pick a widget",
                        "  (`text` default, `confirm`, `checkbox`, `counter`,",
                        "  `date`, `radio`, `sheet`, `speech`, `spinner`,",
                        "  `time`); `-s` = sheet, `-c` = confirm, `-l` or `-f`",
                        "  supply list values, `-p` password, `-m` multiline,",
                        "  `-n` numeric. `sheet` is a plain list dialog (no",
                        "  material bottom sheet in this app)"));
    }
}
