package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The original Termux-compat command set (ADR-0036): the seven commands the
 * bridge already answers. Bodies are the same translations the writer used to
 * inline, re-homed onto the shared {@code termux_compat} runtime
 * ({@code tc.call}, {@code tc.emit}, {@code tc.warn},
 * {@code tc.warn_truncated}, {@code tc.print_json}, {@code tc.CliError},
 * {@code tc.BridgeError}).
 */
public final class TermuxCoreCommands {

    private TermuxCoreCommands() {
    }

    /** The core commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                batteryStatus(),
                location(),
                contactList(),
                smsList(),
                telephonyDeviceinfo(),
                telephonyCellinfo()));
    }

    private static TermuxCommand batteryStatus() {
        return new TermuxCommand(
                "termux-battery-status",
                String.join("\n",
                        "PLUGGED = {'none': 'UNPLUGGED', 'ac': 'PLUGGED_AC',",
                        "           'usb': 'PLUGGED_USB', 'wireless': 'PLUGGED_WIRELESS',",
                        "           'dock': 'PLUGGED_DOCK'}",
                        "",
                        "",
                        "def enum_name(value):",
                        "    return str(value).upper().replace('-', '_')",
                        "",
                        "",
                        "def to_termux(reading):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    plugged = str(reading.get('plugged', 'none'))",
                        "    return {",
                        "        'health': enum_name(reading.get('health', 'unknown')),",
                        "        'percentage': int(reading.get('capacity_percent', 0)),",
                        "        'plugged': PLUGGED.get(plugged,",
                        "                               'PLUGGED_' + enum_name(plugged)),",
                        "        'status': enum_name(reading.get('status', 'unknown')),",
                        "        'temperature': round(float(",
                        "            reading.get('temperature_deci_celsius', 0)) / 10.0, 1),",
                        "        'current': int(reading.get('current_microamps', 0)),",
                        "        'voltage': int(reading.get('voltage_microvolts', 0)) // 1000,",
                        "    }",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-battery-status')",
                        "    return tc.emit(to_termux(tc.call('battery.status')))",
                        ""),
                Arrays.asList(
                        "- `termux-battery-status` - battery snapshot; fields",
                        "  `health`, `percentage`, `plugged`, `status`,",
                        "  `temperature` (C), `current` (uA), `voltage` (mV)"));
    }

    private static TermuxCommand location() {
        return new TermuxCommand(
                "termux-location",
                String.join("\n",
                        "def parse(argv):",
                        "    provider = None",
                        "    request = 'once'",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag not in ('-p', '-r') or index + 1 >= len(argv):",
                        "            raise tc.CliError('usage: termux-location [-p provider] [-r request]')",
                        "        value = argv[index + 1]",
                        "        if flag == '-p':",
                        "            if value not in ('gps', 'network', 'passive'):",
                        "                raise tc.CliError('unsupported provider: ' + value)",
                        "            provider = value",
                        "        else:",
                        "            if value not in ('once', 'last', 'updates'):",
                        "                raise tc.CliError('unsupported request: ' + value)",
                        "            request = value",
                        "        index += 2",
                        "    return provider, request",
                        "",
                        "",
                        "def to_termux(reading, provider):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    result = {",
                        "        'latitude': reading.get('latitude'),",
                        "        'longitude': reading.get('longitude'),",
                        "        'accuracy': reading.get('accuracy_meters'),",
                        "        'provider': reading.get('provider') or provider or 'gps',",
                        "    }",
                        "    for key, source in (('altitude', 'altitude_meters'),",
                        "                        ('bearing', 'bearing_degrees'),",
                        "                        ('speed', 'speed_meters_per_second')):",
                        "        value = reading.get(source)",
                        "        if value is not None:",
                        "            result[key] = value",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    provider, request = parse(argv)",
                        "    if request == 'updates':",
                        "        tc.warn('termux-location', 'updates stream is not available;'",
                        "              ' returning one fix')",
                        "        request = 'once'",
                        "    params = {'request': request}",
                        "    if provider is not None:",
                        "        params['provider'] = provider",
                        "    # The 35 s socket timeout sits just above the app's 30 s",
                        "    # one-shot window so the socket never gives up first.",
                        "    reading = tc.bridge_call('location.get', params,",
                        "                             timeout=35.0)",
                        "    if reading.get('stale') is True:",
                        "        age_ms = reading.get('age_ms')",
                        "        suffix = (' (' + str(age_ms) + ' ms old)'",
                        "                  if age_ms is not None else '')",
                        "        tc.warn('termux-location', 'last known fix' + suffix)",
                        "    return tc.emit(to_termux(reading, provider))",
                        ""),
                Arrays.asList(
                        "- `termux-location [-p provider] [-r request]` - one",
                        "  foreground fix; `-p gps|network|passive` forces the",
                        "  provider, `-r last` answers the freshest last-known fix",
                        "  without waiting (`-r updates` still answers one fix).",
                        "  Fields `latitude`, `longitude`, `accuracy`, `provider`,",
                        "  plus `altitude`, `bearing`, `speed` when the fix",
                        "  carries them; a stale last-known answer warns",
                        "  `last known fix (<age> ms old)` on stderr"));
    }

    private static TermuxCommand contactList() {
        return new TermuxCommand(
                "termux-contact-list",
                String.join("\n",
                        "import json",
                        "",
                        "",
                        "def to_termux(reading):",
                        "    tc.warn_truncated('termux-contact-list', reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        name = row.get('name') or ''",
                        "        primary = row.get('number_1')",
                        "        if primary:",
                        "            result.append({'name': name, 'number': primary})",
                        "        for index in range(2, 6):",
                        "            extra = row.get('number_' + str(index))",
                        "            if extra:",
                        "                result.append({'name': name, 'number': extra})",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-contact-list')",
                        "    return tc.emit(to_termux(tc.call('contacts.list')))",
                        ""),
                Arrays.asList(
                        "- `termux-contact-list` - bounded contact rows; fields",
                        "  `name`, `number` (one row per number)"));
    }

    private static TermuxCommand smsList() {
        return new TermuxCommand(
                "termux-sms-list",
                String.join("\n",
                        "import datetime",
                        "import json",
                        "",
                        "",
                        "MAX_ROWS = 50",
                        "",
                        "",
                        "def parse(argv):",
                        "    limit = None",
                        "    offset = None",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag not in ('-l', '-o') or index + 1 >= len(argv):",
                        "            raise tc.CliError('usage: termux-sms-list [-l LIMIT] [-o OFFSET]')",
                        "        value = argv[index + 1]",
                        "        if not value.isdigit():",
                        "            raise tc.CliError('limit and offset must be non-negative numbers')",
                        "        if flag == '-l':",
                        "            limit = int(value, 10)",
                        "        else:",
                        "            offset = int(value, 10)",
                        "        index += 2",
                        "    return limit, offset",
                        "",
                        "",
                        "def to_termux(reading, limit, offset):",
                        "    tc.warn_truncated('termux-sms-list', reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    if offset is not None:",
                        "        rows = rows[offset:]",
                        "    if limit is not None:",
                        "        rows = rows[:limit]",
                        "    else:",
                        "        rows = rows[:MAX_ROWS]",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        entry = {",
                        "            'type': 'inbox',",
                        "            'read': row.get('read') is True,",
                        "            'address': row.get('address', ''),",
                        "            'number': row.get('address', ''),",
                        "            'body': row.get('snippet', ''),",
                        "        }",
                        "        received_ms = row.get('timestamp_utc_ms')",
                        "        if isinstance(received_ms, int) and received_ms > 0:",
                        "            entry['received'] = datetime.datetime.fromtimestamp(",
                        "                received_ms / 1000).strftime('%Y-%m-%d %H:%M:%S')",
                        "        result.append(entry)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    limit, offset = parse(argv)",
                        "    reading = tc.call('sms.inbox')",
                        "    return tc.emit(to_termux(reading, limit, offset))",
                        ""),
                Arrays.asList(
                        "- `termux-sms-list [-l LIMIT] [-o OFFSET]` - bounded inbox",
                        "  rows; fields `type`, `read`, `address`, `number`,",
                        "  `body`, `received`"));
    }

    private static TermuxCommand telephonyDeviceinfo() {
        return new TermuxCommand(
                "termux-telephony-deviceinfo",
                String.join("\n",
                        "def to_termux(reading):",
                        "    if reading.get('available') is not True:",
                        "        return {}",
                        "    result = {}",
                        "    phone_type = reading.get('phone_type')",
                        "    if phone_type:",
                        "        result['phone_type'] = str(phone_type)",
                        "    sim_state = reading.get('sim_state')",
                        "    if sim_state:",
                        "        result['sim_state'] = str(sim_state)",
                        "    network_type = reading.get('network_type')",
                        "    if network_type:",
                        "        result['network_type'] = str(network_type)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-telephony-deviceinfo')",
                        "    return tc.emit(to_termux(tc.call('telephony.info')))",
                        ""),
                Arrays.asList(
                        "- `termux-telephony-deviceinfo` - telephony device",
                        "  snapshot; fields `phone_type`, `sim_state`,",
                        "  `network_type` (a subset of Termux's device dump)"));
    }

    private static TermuxCommand telephonyCellinfo() {
        return new TermuxCommand(
                "termux-telephony-cellinfo",
                String.join("\n",
                        "import json",
                        "",
                        "",
                        "def to_termux(reading):",
                        "    tc.warn_truncated('termux-telephony-cellinfo', reading)",
                        "    rows = json.loads(reading.get('rows', '[]'))",
                        "    result = []",
                        "    for row in rows:",
                        "        if not isinstance(row, dict):",
                        "            continue",
                        "        entry = {'type': str(row.get('technology', '')).lower()}",
                        "        if 'signal_dbm' in row:",
                        "            entry['dbm'] = int(row['signal_dbm'])",
                        "        if 'signal_level' in row:",
                        "            entry['level'] = int(row['signal_level'])",
                        "        result.append(entry)",
                        "    return result",
                        "",
                        "",
                        "def main(argv):",
                        "    if argv:",
                        "        raise tc.CliError('usage: termux-telephony-cellinfo')",
                        "    return tc.emit(to_termux(tc.call('telephony.cellinfo')))",
                        ""),
                Arrays.asList(
                        "- `termux-telephony-cellinfo` - bounded observed cell rows;",
                        "  fields `type`, `dbm`, `level` per observed cell (Termux's",
                        "  identity fields are not exposed by the bridge)"));
    }
}
