package gh.nusashell.nusadesk.infrastructure.proot.termux;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The capture domain Termux-compat commands (wave 2, W2c):
 * {@code termux-camera-info}, {@code termux-camera-photo}, and
 * {@code termux-microphone-record}.
 *
 * <p>Each body is a thin flag-to-method mapping onto {@code CaptureModule}'s
 * bridge methods through the shared {@code termux_compat} runtime. File
 * payloads follow the staging rule: the guest creates an empty file inside
 * the rootfs ({@code /tmp}) and passes that guest path; the host fills it;
 * the guest moves the result to the user's destination, because a workspace
 * bind mount is visible only to the guest.</p>
 *
 * <p>{@code termux-microphone-record} keeps its destination↔staging mapping
 * in a small state file under {@code /tmp}, so a later {@code -q} (a fresh
 * command process, after the recording outlived the starter) knows where to
 * move the finalized file.</p>
 */
public final class TermuxCaptureCommands {

    private TermuxCaptureCommands() {
    }

    /** The capture domain commands in documentation order. */
    public static List<TermuxCommand> commands() {
        return Collections.unmodifiableList(Arrays.asList(
                cameraInfo(),
                cameraPhoto(),
                microphoneRecord()));
    }

    private static TermuxCommand cameraInfo() {
        return new TermuxCommand(
                "termux-camera-info",
                String.join("\n",
                        "USAGE = 'usage: termux-camera-info'",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    if argv:",
                        "        raise tc.CliError(USAGE)",
                        "    reading = tc.bridge_call('camera.info')",
                        "    tc.warn_truncated('termux-camera-info', reading)",
                        "    print(reading.get('camera_json', '[]'))",
                        "    return 0",
                        ""),
                Arrays.asList(
                        "- `termux-camera-info` - JSON array of Camera2",
                        "  devices, one `{id, facing, jpeg_output_sizes}`",
                        "  object each (`facing` is `front`/`back` or the",
                        "  raw platform constant). Needs no camera grant."));
    }

    private static TermuxCommand cameraPhoto() {
        return new TermuxCommand(
                "termux-camera-photo",
                String.join("\n",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "",
                        "USAGE = 'usage: termux-camera-photo [-c camera-id] output-file'",
                        "",
                        "",
                        "def parse(argv):",
                        "    camera_id = '0'",
                        "    args = []",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag == '-c' and index + 1 < len(argv):",
                        "            camera_id = argv[index + 1]",
                        "            index += 2",
                        "        elif flag.startswith('-'):",
                        "            raise tc.CliError(USAGE)",
                        "        else:",
                        "            args.append(flag)",
                        "            index += 1",
                        "    if len(args) != 1:",
                        "        raise tc.CliError(USAGE)",
                        "    return camera_id, args[0]",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    camera_id, output = parse(argv)",
                        "    destination = os.path.abspath(output)",
                        "    parent = os.path.dirname(destination) or '.'",
                        "    if not os.path.isdir(parent):",
                        "        raise tc.CliError('no such directory: ' + parent)",
                        "    fd, staging = tempfile.mkstemp(",
                        "        prefix='nusadesk-photo-', dir='/tmp')",
                        "    os.close(fd)",
                        "    try:",
                        "        # The capture is foreground-bound on the host;",
                        "        # give it more room than the default 15 s.",
                        "        tc.bridge_call('camera.photo',",
                        "                       {'camera_id': camera_id, 'path': staging},",
                        "                       timeout=45.0)",
                        "        try:",
                        "            shutil.move(staging, destination)",
                        "        except OSError:",
                        "            raise tc.CliError(",
                        "                'cannot write output file: ' + destination)",
                        "        return 0",
                        "    finally:",
                        "        try:",
                        "            os.unlink(staging)",
                        "        except OSError:",
                        "            pass",
                        ""),
                Arrays.asList(
                        "- `termux-camera-photo [-c CAMERA-ID] OUTPUT-FILE` -",
                        "  captures one JPEG at the camera's largest JPEG size",
                        "  (no preview) and writes it to OUTPUT-FILE; needs the",
                        "  CAMERA grant and runs through the foreground host,",
                        "  so the app must be able to surface a window."));
    }

    private static TermuxCommand microphoneRecord() {
        return new TermuxCommand(
                "termux-microphone-record",
                String.join("\n",
                        "import json",
                        "import os",
                        "import shutil",
                        "import tempfile",
                        "import time",
                        "",
                        "USAGE = ('usage: termux-microphone-record [-h] [-d] '",
                        "         '[-f file] [-l limit] [-e encoder] [-b bitrate]'",
                        "         ' [-r rate] [-c channels] [-i] [-q]')",
                        "ENCODERS = ('aac', 'amr_wb', 'amr_nb', 'opus')",
                        "EXTENSIONS = {'aac': '.m4a', 'amr_wb': '.3gp',",
                        "              'amr_nb': '.3gp', 'opus': '.ogg'}",
                        "STATE_FILE = '/tmp/nusadesk-mic-record.json'",
                        "MAX_LIMIT = 900",
                        "",
                        "",
                        "def parse(argv):",
                        "    record = {}",
                        "    index = 0",
                        "    while index < len(argv):",
                        "        flag = argv[index]",
                        "        if flag in ('-i', '-q'):",
                        "            if len(argv) != 1:",
                        "                raise tc.CliError(",
                        "                    'no other options allowed with ' + flag)",
                        "            return flag[1], None",
                        "        if flag == '-d':",
                        "            index += 1",
                        "            continue",
                        "        if flag in ('-f', '-l', '-e', '-b', '-r', '-c') \\",
                        "                and index + 1 < len(argv):",
                        "            value = argv[index + 1]",
                        "            index += 2",
                        "            if flag == '-f':",
                        "                record['file'] = value",
                        "            elif flag == '-l':",
                        "                if not value.isdigit():",
                        "                    raise tc.CliError('limit must be a number')",
                        "                limit = int(value)",
                        "                if limit > MAX_LIMIT:",
                        "                    raise tc.CliError(",
                        "                        'limit exceeds the 900 s cap')",
                        "                record['limit'] = limit",
                        "            elif flag == '-e':",
                        "                encoder = value.lower()",
                        "                if encoder not in ENCODERS:",
                        "                    raise tc.CliError(",
                        "                        'unsupported encoder: ' + value)",
                        "                record['encoder'] = encoder",
                        "            elif flag == '-b':",
                        "                if not value.isdigit() or int(value) < 1:",
                        "                    raise tc.CliError(",
                        "                        'bitrate must be a positive number')",
                        "                record['bitrate_kbps'] = int(value)",
                        "            elif flag == '-r':",
                        "                if not value.isdigit() or int(value) < 1:",
                        "                    raise tc.CliError(",
                        "                        'sample rate must be a positive number')",
                        "                record['sample_rate'] = int(value)",
                        "            elif flag == '-c':",
                        "                if not value.isdigit() or int(value) < 1:",
                        "                    raise tc.CliError(",
                        "                        'channel count must be a positive number')",
                        "                record['channels'] = int(value)",
                        "            continue",
                        "        raise tc.CliError(USAGE)",
                        "    if not argv:",
                        "        raise tc.CliError(USAGE)",
                        "    return 'record', record",
                        "",
                        "",
                        "def read_state():",
                        "    try:",
                        "        with open(STATE_FILE, 'r', encoding='ascii') as handle:",
                        "            state = json.load(handle)",
                        "        return state if isinstance(state, dict) else None",
                        "    except (OSError, ValueError):",
                        "        return None",
                        "",
                        "",
                        "def write_state(staging, destination):",
                        "    try:",
                        "        with open(STATE_FILE, 'w', encoding='ascii') as handle:",
                        "            json.dump({'staging': staging,",
                        "                       'destination': destination}, handle)",
                        "    except OSError:",
                        "        pass",
                        "",
                        "",
                        "def clear_state():",
                        "    try:",
                        "        os.unlink(STATE_FILE)",
                        "    except OSError:",
                        "        pass",
                        "",
                        "",
                        "def duration_text(seconds):",
                        "    hours = seconds // 3600",
                        "    text = '%02d:%02d' % ((seconds % 3600) // 60,",
                        "                          seconds % 60)",
                        "    return ('%02d:' % hours) + text if hours > 0 else text",
                        "",
                        "",
                        "def record(opts):",
                        "    encoder = opts.get('encoder', 'aac')",
                        "    destination = opts.get('file')",
                        "    if destination is None:",
                        "        stamp = time.strftime('%Y-%m-%d_%H-%M-%S')",
                        "        destination = os.path.join(",
                        "            os.path.expanduser('~'),",
                        "            'TermuxAudioRecording_' + stamp",
                        "            + EXTENSIONS[encoder])",
                        "    destination = os.path.abspath(destination)",
                        "    parent = os.path.dirname(destination) or '.'",
                        "    if not os.path.isdir(parent):",
                        "        raise tc.CliError('no such directory: ' + parent)",
                        "    if os.path.exists(destination):",
                        "        raise tc.CliError('file already exists: ' + destination)",
                        "    fd, staging = tempfile.mkstemp(",
                        "        prefix='nusadesk-mic-', dir='/tmp')",
                        "    os.close(fd)",
                        "    params = {'path': staging, 'encoder': encoder}",
                        "    if 'limit' in opts:",
                        "        params['limit_seconds'] = opts['limit']",
                        "    for key in ('bitrate_kbps', 'sample_rate', 'channels'):",
                        "        if key in opts:",
                        "            params[key] = opts[key]",
                        "    try:",
                        "        tc.bridge_call('microphone.record.start', params,",
                        "                       timeout=30.0)",
                        "    except Exception:",
                        "        try:",
                        "            os.unlink(staging)",
                        "        except OSError:",
                        "            pass",
                        "        raise",
                        "    write_state(staging, destination)",
                        "    limit = opts.get('limit', 0)",
                        "    # -l 0 is unbounded upstream; here it selects the",
                        "    # 900 s bridge cap, so report the real duration.",
                        "    effective = limit if limit > 0 else MAX_LIMIT",
                        "    print('Recording started: ' + destination + ' ')",
                        "    print('Max Duration: ' + duration_text(effective))",
                        "    return 0",
                        "",
                        "",
                        "def info():",
                        "    reading = tc.bridge_call('microphone.record.info')",
                        "    out = {'isRecording': bool(reading.get('recording'))}",
                        "    if out['isRecording']:",
                        "        state = read_state()",
                        "        path = (state or {}).get('destination') \\",
                        "            or reading.get('path')",
                        "        if path:",
                        "            out['outputFile'] = path",
                        "    return tc.emit(out)",
                        "",
                        "",
                        "def quit_recording():",
                        "    reading = tc.bridge_call('microphone.record.stop')",
                        "    state = read_state()",
                        "    try:",
                        "        if reading.get('stopped') is not True:",
                        "            print('No recording to stop')",
                        "            return 0",
                        "        staging = (state or {}).get('staging') \\",
                        "            or reading.get('path')",
                        "        destination = (state or {}).get('destination')",
                        "        moved = staging",
                        "        if staging and destination:",
                        "            try:",
                        "                shutil.move(staging, destination)",
                        "                moved = destination",
                        "            except OSError:",
                        "                moved = staging",
                        "        print('Recording finished: ' + str(moved))",
                        "        return 0",
                        "    finally:",
                        "        clear_state()",
                        "",
                        "",
                        "def main(argv):",
                        "    if '-h' in argv:",
                        "        print(USAGE)",
                        "        return 0",
                        "    mode, opts = parse(argv)",
                        "    if mode == 'i':",
                        "        return info()",
                        "    if mode == 'q':",
                        "        return quit_recording()",
                        "    return record(opts)",
                        ""),
                Arrays.asList(
                        "- `termux-microphone-record [-d] [-f FILE] [-l SEC]`",
                        "  `[-e aac|amr_wb|amr_nb|opus] [-b KBPS] [-r HZ]`",
                        "  `[-c N]` - starts a stateful recording (it keeps",
                        "  running after the command exits); `-i` prints",
                        "  `{isRecording, outputFile}`, `-q` finalizes and",
                        "  moves the file to the `-f` destination. `-l` is",
                        "  bounded to 0..900 s (0 selects the 900 s ceiling).",
                        "  Needs the RECORD_AUDIO grant and runs through the",
                        "  foreground host on start."));
    }
}
